### ISSUE TITLE
Difference between import of main in app/__init__.py in 7a and 8e

### ISSUE THREAD

**Issue by priyankamandikal** [miguelgrinberg/flasky#100]
In 7a, it's defined as
from main import main as main_blueprint

in 8e, it's defined as
from .main import main as main_blueprint

Is there a reason the dot was introduced? Won't it work fine without the dot as well?

**Comment by miguelgrinberg** [comment]
I don't see what you see. In 7a I still see the dot: https://github.com/miguelgrinberg/flasky/blob/4987f6caefddd9706e06e5fa1266528e0b80a752/app/__init__.py#L24

The version w/o a dot works on Python 2 and returns an error on Python 3. The version with the dot uses relative imports, which work on Python 2 and Python 3.
