### ISSUE TITLE
Running specific/individual tests

### ISSUE THREAD

**Issue by cassac** [miguelgrinberg/flasky#101]
I'm trying to find a way to run individual tests instead of all of them at once. I tried adding a parameter to the `test` function in `manage.py` so I could specify the test from the command line `python manage.py test 'test_basic'` but couldn't figure out how to use the parameter correctly in the `test` function to access the desirable unit test. The only way I could access a specific test was indexing the list of unit tests inside the `tests` variable - `tests._tests[0]`, `tests._tests[1]` etc...

``` python
@manager.command
def test():
    """Run the unit test."""
    import unittest
    tests = unittest.TestLoader().discover('tests')
    unittest.TextTestRunner(verbosity=2).run(tests._tests[-1])
```

Any suggestions for a more elegant way of doing this?

**Comment by miguelgrinberg** [comment]
Very good question. Here is the modified Flask-Script command to run subsets or individual tests (without including the coverage portions to keep the code short):

@manager.command
def test(coverage=False, test_name=None):
    """Run the unit tests."""
    import unittest
    if test_name is None:
        tests = unittest.TestLoader().discover('tests')
    else:
        tests = unittest.TestLoader().loadTestsFromName('tests.' + test_name)
    unittest.TextTestRunner(verbosity=2).run(tests)

The `test_name` argument can be the fully qualified name of a test module, test suite, or individual test. Examples:

    # run all the tests in a module
    ./manage.py test -t test_api

    # run all the tests in a TestCase
    ./manage.py test -t test_api.APITestCase

    # run an individual test
    ./manage.py test -t test_api.APITestCase.test_404

**Comment by cassac** [comment]
Works like a charm! BTW, your book and blog are amazing learning resources. Thanks Miguel.

**Comment by klameer** [comment]
Hi Miguel,
I learned Flask from your book. I went from not knowing anything to creating a fully functional website with user management and security with a proper data model. 
Although I still have a long way to go, I would like to thank you as your book was a fantastic resource and I don't think I would be any where near my current ability if not for you. 

Thanks and I will be following your work quite closely from now on. 

Karim

**Comment by pdamoune** [comment]
Hi Miguel,
Would you have a solution for the "flask test" CLI ?
I don't know how to custom it

Btw, thank you very much, your book and tuto are awesome

**Comment by miguelgrinberg** [comment]
@pdamoune looks good to me!

**Comment by pdamoune** [comment]
What about the coverage=False you ve put ?

**Comment by miguelgrinberg** [comment]
I've added the option to specify tests to the `flask test` command. Tests need to be specified as a list of dotted import test names. For example:

```
# run all the tests in a module
$ flask test tests.test_api

# run all the tests in a TestCase
$ flask test -t tests.test_api.APITestCase

# run an individual test
$ flask test -t tests.test_api.APITestCase.test_404

# run multiple tests
$ flask test -t tests.test_api.APITestCase tests.test_basics
```
