### ISSUE TITLE
Unable to see post choices

### ISSUE THREAD

**Issue by neela77777** [miguelgrinberg/flasky#102]
I downloaded the final version of the package from Git, with Celery (also tried the version without Celery). I next ran "python manage.py db upgrade". I then tried to register a new user, and get a screen that just says: 

Hello, neela!

    All
    Followers

    «
    »
I don't see any choices to post a blog.

My roles table in the database is empty.
I haven't changed any of the code from Git.

Would appreciate any thoughts on what I could do to get the code working.

Thank you.

**Comment by miguelgrinberg** [comment]
This is explained in the book. There is a deploy step that creates user roles, which is what is missing. Try running `python manage.py deploy` and then create your user, so that it gets assigned the proper role. There's also the configuration, which you should review and edit as appropriate.

**Comment by neela77777** [comment]
Thank you. This worked. I somehow overlooked it.
