### ISSUE TITLE
Email confirmation token function: missing db.session.commit() in app/models.py?

### ISSUE THREAD

**Issue by davidrpmorris** [miguelgrinberg/flasky#104]
Is the confirm function in the User model missing `db.session.commit()` after `db.session.add(self)` on line 157 of app/models.py?

**Comment by miguelgrinberg** [comment]
This project is configured to automatically commit db sessions when the request ends, so explicit commits are not necessary. If Flask-SQLAlchemy wasn't configured to autocommit, then sure, you would need to commit every time you make a change.

**Comment by davidrpmorris** [comment]
Thank you!
