### ISSUE TITLE
Customize email html templates via webpages

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#105]
Hi Miguel,

I want to customize the the HTML templates so that users can send out customized emails - do you know any good in-browser wysiwyg html editor that works with flask?

or is there a better way to do that?

Thanks!

Harry

**Comment by miguelgrinberg** [comment]
Any Javascript based editor that uses a TextArea HTML control should work just fine with flask. For example, take a look at https://ace.c9.io.

**Comment by playgoods** [comment]
MR Miguel i want like editor GitHub . seam seam write comment now :) you can give me any think .
thank you
