### ISSUE TITLE
**kwargs

### ISSUE THREAD

**Issue by masaguaro** [miguelgrinberg/flasky#107]
Hi Miguel

I have been following your book steep by steep, I have enjoyed but I am a bit stuck in page 71 Example 6-3. The code is like this:
#...
def send_email (to, subject, template, **kwargs):
......
......msg.body = render_template( template + 'txt', **kwarg)
......
......mail.send(msg)

In the book says that: "The keyword arguments passed by the caller are given to the render_template() calls so they can be used by the templates that generate the email body."

Sorry for this question, when and how **kwarg values are assigned. ? Do you have a piece of code to clarify this point .. Thank you very much in advanced :)

**Comment by masaguaro** [comment]
In the def parameters is not *kwargs the right parameter is **kwargs.. Does any body has any clue ?

**Comment by miguelgrinberg** [comment]
There are several examples in the code. For example, see https://github.com/miguelgrinberg/flasky/blob/579ecd9435b392df114110985f514ad173a315f2/app/auth/views.py#L59-L60.

The kwargs are used to send variables that the email template can reference, for example a username, or token. By using kwargs for that, the function is completely decoupled from the emails, you can send a variety of emails, each requiring different template variables.

**Comment by masaguaro** [comment]
Thank you very much Miguel !!

**Comment by jeffwidman** [comment]
This can be closed.
