### ISSUE TITLE
problem found on "app/auth/views.py"

### ISSUE THREAD

**Issue by xpleaf** [miguelgrinberg/flasky#109]
line 104, function "password_reset_request()"
@auth.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
....if not current_user.is_anonymous:
........return redirect(url_for('main.index'))
....form = PasswordResetRequestForm()
....if form.validate_on_submit():
........user = User.query.filter_by(email=form.email.data).first()
........if user:
............token = user.generate_reset_token()
............send_email(user.email, 'Reset Your Password',
........................ 'auth/email/reset_password',
........................user=user, token=token,
........................next=request.args.get('next'))
........flash('An email with instructions to reset your password has been '
....................'sent to you.')
........return redirect(url_for('auth.login'))
....return render_template('auth/reset_password.html', form=form)

I think this would be right:
@auth.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
....if not current_user.is_anonymous:
........return redirect(url_for('main.index'))
....form = PasswordResetRequestForm()
.... if form.validate_on_submit():
........user = User.query.filter_by(email=form.email.data).first()
........if user:
............token = user.generate_reset_token()
............send_email(user.email, 'Reset Your Password',
........................'auth/email/reset_password',
........................user=user, token=token,
........................next=request.args.get('next'))
............flash('An email with instructions to reset your password has been '
........................'sent to you.')
............return redirect(url_for('auth.login'))
........else:
............flash('Unknown email address.')
....return render_template('auth/reset_password.html', form=form)

I think the message of send email success should belong to the "if user" block.
After I changing it, it worked.
Have you ever met this problem?

**Comment by miguelgrinberg** [comment]
No, the code is doing the right thing.

If you provide too detailed messages such as "the email was sent" and "the email is unknown", then an attacker can get an idea of who are the members of the site, just by trying different email addresses. This application responds with a generic "the email was sent" message to not give away membership information to strangers.

**Comment by xpleaf** [comment]
Soga, I get it.Thank you very much!
