### ISSUE TITLE
HTTPie test question

### ISSUE THREAD

**Issue by xpleaf** [miguelgrinberg/flasky#110]
Hello, Miguel!
A moment ago, I used the HTTPie to test the API, but I met a problem.

When I use the email and password to get the posts list, the result are as follow:
=============================================================================

(venv)xpleaf@leaf:~/PycharmProjects/flask_blog/flasky$ http --json --auth 429191942@qq.com:123456 GET http://127.0.0.1:5000/api/v1.0/postsHTTP/1.0 301 MOVED PERMANENTLY
Content-Length: 281
Content-Type: text/html; charset=utf-8
Date: Wed, 27 Jan 2016 14:37:21 GMT
Location: http://127.0.0.1:5000/api/v1.0/posts/
Server: Werkzeug/0.11.3 Python/2.7.10

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://127.0.0.1:5000/api/v1.0/posts/">http://127.0.0.1:5000/api/v1.0/posts/</a>.  If not click the link.
=============================================================================

However, when I use the token, it works as you wrote in the book:
=============================================================================

(venv)xpleaf@leaf:~/PycharmProjects/flask_blog/flasky$ http --json --auth eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ1MzkwODYwNiwiaWF0IjoxNDUzOTA1MDA2fQ.eyJpZCI6OTd9.sPK-YNTPCQHekEWEz1-SClGEBrmu49H_B2wBlupM2U8: GET http://127.0.0.1:5000/api/v1.0/posts/
HTTP/1.0 200 OK
Content-Length: 5994
Content-Type: application/json
Date: Wed, 27 Jan 2016 14:31:48 GMT
Server: Werkzeug/0.11.3 Python/2.7.10

{
    "count": 102, 
    "next": "http://127.0.0.1:5000/api/v1.0/posts/?page=2", 
    "posts": [...], 
    "prev": null
}

=============================================================================

Do you know what happens to my test?

**Comment by miguelgrinberg** [comment]
Note that in the first example you did not have a trailing slash. That's what makes these two tests different. The route in the server is defined with the trailing slash, When you send the request to `/posts`, Flask tries to force you to use the correct route, by redirecting you to `/posts/`.

**Comment by kevinbowen777** [comment]
FWIW, your example in your book does not include the trailing slash. Which is why people(myself included) might have issues with this command. You _may_ want to add it to the errata.
