### ISSUE TITLE
A problem when use "git push"

### ISSUE THREAD

**Issue by xpleaf** [miguelgrinberg/flasky#111]
Hello, Miguel.
When I use "git push heroku master", the problem happends:
`Total 504 (delta 274), reused 501 (delta 273)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Using set buildpack heroku/python
remote: 
remote:  !     Push rejected, failed to detect set buildpack heroku/python
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to flaskycn.
remote: 
To https://git.heroku.com/flaskycn.git
 ! [remote rejected] master -> master (pre-receive hook declined)
`
What may happen to my situation？

**Comment by miguelgrinberg** [comment]
That typically happens when you forgot to include a required file in your repository. Check that you have `requirements.txt` and `Procfile`.

**Comment by xpleaf** [comment]
Yes, I sure both of them are available on my folder:

xpleaf@leaf:~/PycharmProjects/flask_blog/flasky$ ls

app         LICENSE     migrations  requirements      venv

config.py   manage.py   `Procfile `   `requirements.txt`

config.pyc  manage.pyc  README.md   tests

I have tried several times just now, but it still returned the same information.

**Comment by miguelgrinberg** [comment]
are they also in your git repository?

**Comment by xpleaf** [comment]
Yes, I cloned them from your GitHub.

**Comment by miguelgrinberg** [comment]
Well, the error that you get indicates something is missing. When Heroku looked at the code that you pushed it found something is missing. Here is the script that does this checking: https://github.com/heroku/heroku-buildpack-python/blob/master/bin/detect. As you can see, Heroku expects a requirements.txt or setup.py file in the root directory, and has found neither. Check again, pretty sure requirements.txt isn't being pushed when you push.

**Comment by xpleaf** [comment]
**I really appreciate your help!!!**

It just like the problem you said.Both the `Procfile` and `requirements.txt` just in the branch of my git repository but not in the master.

I like your book very much, it really helps me a lot!

#  Sincere thanks for your help and guidance,thank you,and wish you success in work!

It is now 2:35am in China, and I have to sleep now.Good night, Miguel.

**Comment by In-vincible** [comment]
Thanks a lot @miguelgrinberg for solving the problem and @xpleaf for asking it...I faced the same problem

**Comment by kitianFresh** [comment]
Wow, Thanks!
