### ISSUE TITLE
How can I implement the function of recording the view of an article(post)?

### ISSUE THREAD

**Issue by xpleaf** [miguelgrinberg/flasky#114]
Hello, Miguel. After learning your book step by setp, I develop a blog system of myself.But I have some difficulties as follow:
`class Article(db.Model):
    **tablename** = 'articles'

```
id = db.Column(db.Integer, primary_key=True)
title = db.Column(db.String(64), unique=True)
content = db.Column(db.Text)
summary = db.Column(db.Text)
create_time = db.Column(db.DateTime, index=True, default=datetime.utcnow)
update_time = db.Column(db.DateTime, index=True, default=datetime.utcnow)
num_of_view = db.Column(db.Integer, default=0)
articleType_id = db.Column(db.Integer, db.ForeignKey('articleTypes.id'))
source_id = db.Column(db.Integer, db.ForeignKey('sources.id'))
comments = db.relationship('Comment', backref='article', lazy='dynamic')`
```

I would like to implement the function that the `num_of_view` will add 1 when a visitor visit the article, 
I have implement it use the view function in Flask.It is OK to use db.event.listen()?
I will appreciate it if you can help me.

**Comment by miguelgrinberg** [comment]
The easiest way to record number of views is to do it in the GET request handler:

    @app.route('/articles/<id>')
    def get_article(id):
        article = Article.query.get_or_404(id)
        article.views += 1
        db.session.add(article)
        db.session.commit()
        return render_template('article.html', article=article)

**Comment by xpleaf** [comment]
Thinks!I will try it.
