### ISSUE TITLE
use git bash and cmd together

### ISSUE THREAD

**Issue by wuchangfeng** [miguelgrinberg/flasky#116]
hello:
    i just follow your course step by step,very thx.
    what i wanna know is that:
    my computer is win,when i tried type:$ venv\Scripts\activate to activate venv.  it can not work. so i googled,find a way:$ source venv/Scripts/activate.it worked.but i can not see: (venv) $. sure i can not run python command in here.so i can not run git command and python command together in git bash.
    i find a way to solve it ,use cmd and git together.but it not convient.
    if you see,and have some time,please give me some guides,
    very thx.
    in the book 5 page

**Comment by miguelgrinberg** [comment]
@wuchangfeng I'm not sure using git bash for any work other than git is a good idea. This is a port of the real bash shell, so a lot of things work the unix way and not the windows way when you are in that shell. Have you tried adding `git` to your `PATH` and then running both git and python from the regular command prompt?

**Comment by wuchangfeng** [comment]
thx for your guides,i will try .with your suggestions.very thx.
