### ISSUE TITLE
can not see TextAreaFiled("What's on your mind?") and the 'submit' button in 11 chapter

### ISSUE THREAD

**Issue by wuchangfeng** [miguelgrinberg/flasky#117]
Sorry, i had question again,just like what i said in 11th chapter , i checkouted  11a,but i can not see the TextArea and submit,just like the following picture.Register and email check is ok.
![question](https://cloud.githubusercontent.com/assets/13432620/13460502/df013cba-e0b5-11e5-8d57-e8a0aa65e9ac.jpg)

**Comment by wuchangfeng** [comment]
oh , i check the code and now i know ,because of  the 'Role' in 9th chapter ,i did not pay attenation to it

**Comment by wuchangfeng** [comment]
but i still have question that why the 'Role' influences the showing of TextArea and Submit?

**Comment by miguelgrinberg** [comment]
A user that does not have the "write articles" role does not see the text area, simply because adding posts is not a valid operation for that user.
