### ISSUE TITLE
Login requirements in API blueprint don't work

### ISSUE THREAD

**Issue by dvb7836** [miguelgrinberg/flasky#119]
All data can be accessed without authentication via API.

**Comment by miguelgrinberg** [comment]
The code that protects the API is: https://github.com/miguelgrinberg/flasky/blob/master/app/api_1_0/authentication.py#L35-L37.

Are you saying this code isn't running, for some reason?

**Comment by dvb7836** [comment]
Yes, @auth.login_required decorator don`t reject anonymous requests to API.
for example: /api/v1.0/posts/ return full list of blog posts whenever you are logged in or not.

**Comment by miguelgrinberg** [comment]
Blog posts in this app are public. Try sending a POST request to add a blog post, and let me know if that goes through. Pretty sure that will fail.

**Comment by dvb7836** [comment]
I thought that blog posts are not public because of this test:
class APITestCase(unittest.TestCase):
# ...
    def test_no_auth(self):
        response = self.client.get(url_for('api.get_posts'), content_type='application/json')
        self.assertTrue(response.status_code == 401)

Unauthorised POST request surely fails because of using another decorator  @permission_required(Permission.WRITE_ARTICLES)

**Comment by miguelgrinberg** [comment]
I think you are looking at an old version of this test, I vaguely remember fixing this a while ago. The current version of this test expects a 200: https://github.com/miguelgrinberg/flasky/blob/master/tests/test_api.py#L40-L43.

**Comment by dvb7836** [comment]
Got it. Thank you for the reply.
