### ISSUE TITLE
Code coverage report, the manage.py integration

### ISSUE THREAD

**Issue by eltonto187** [miguelgrinberg/flasky#121]
Coverage reports: why can't I write directly in the **test** function? and should use environment variables FLASK_COVERAGE, do you want to set this environment variable from the command line

**Comment by miguelgrinberg** [comment]
To get a coverage report you have to run:

    ./manage.py test --coverage

The `FLASK_COVERAGE` env var is internally handled by manage.py, you do not have to set it.

**Comment by eltonto187** [comment]
`import coverage
    COV = coverage.coverage(branch=True, include='app/*')
    COV.start()`
Can not write directly in the test function?Why did you write is so complex that to introduce the environment variables FLASK_COVERAGE?

**Comment by miguelgrinberg** [comment]
Because you want all the imported code at the top of manage.py to be included in the coverage report. That requires coverage to be activated above the imports.
