### ISSUE TITLE
Hardcoded url in selenium tests

### ISSUE THREAD

**Issue by pwfraley** [miguelgrinberg/flasky#122]
In test_selenium.py the url is hard coded, which works fine if you are testing on your local machine, but with Jenkins, where many projects might run and also use port 5000 or if you use grid, this will not work.

Ist there a best practice on how to set the url and port in the selenium tests?

**Comment by miguelgrinberg** [comment]
The standard way is to pass the port number in a `PORT` environment variable. Depending on your testing set up, you may be able to reserve a port for your test, or maybe just get a random port number.
