### ISSUE TITLE
Is "is_authenticated" missing "()"? 

### ISSUE THREAD

**Issue by imnisen** [miguelgrinberg/flasky#123]
When I clone the project, I runserver, as AnonymousUser, It comes with error. So I find, in "app/auth/views.py" line 14, "if current_user.is_authenticated" , it should be "current_user.is_authenticated()" right? 
Also at  "app/templates/base.html" line 35, the same problem.
Please check it, thanks!

**Comment by miguelgrinberg** [comment]
@imnisen Check what version of Flask-Login you have installed in your virtualenv. In versions prior to 0.3.0, `is_authenticated` is a functon. In 0.3.0, for reasons I fail to understand, the author of Flask-Login changed it to a property, causing lot of confusion and problems like the one you have right now.

If you refresh the virtualenv from the requirements file you should be fine, I think.

**Comment by imnisen** [comment]
Ah, thank you, that's the reason!
