### ISSUE TITLE
Flask Can't get the administrator right by set the config.py

### ISSUE THREAD

**Issue by land-pack** [miguelgrinberg/flasky#127]
I have simple modify the config.py to my email, and I can't get the expect result! so I have put some code into the main/views.py `print 'current_app', current_app.config['FLASKY_ADMIN']
    print 'is_admin', current_user.is_administrator()` (inside the index() , and the email is my email which i had set into the config.py but the I have no get the administrator privilege.I don't know this line in the User
` if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(permissions=0xff).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()`
Can you help me to figure it out?

**Comment by miguelgrinberg** [comment]
The admin role assignment happens when the user registers, it is not get applied retroactively when you change the configuration. After you change the config, you need to register with the account you want to be administrator. If that accounts already exists, you may need to manually remove it from the database.

**Comment by land-pack** [comment]
hey! I have do those step below , and it's work for me! 
`from app.models import User,Role` 
and then, I have do the query to get the register user !
`u=User.query.filter_by(email='my-email@abc.com`).first() 
and then I have to run the static method inside the Role `Role.insert_roles()` 
to make the current user have permission, i have get the role id by Query it from data too! So I have do the follow command!
`r=Role.query.filter_by(permissions=0xff).first()` and then assign it 
` u.role_id=r.id` ,last thing is store it to database 
`db.session.add(u)
db.session.commit()`
Thank you for your help! and all your work! and I also have a suggestion, help to see you second version book! Thank you again Mr.miguel

**Comment by miguelgrinberg** [comment]
You are welcome. Glad everything is working!

**Comment by Divyansh-Purohit** [comment]
can't we just automate this task of defining the correct role every time a new user registers...like adding before_request decorator that does the same for us.
