### ISSUE TITLE
Httpie test error in charpter 14. Thank you!

### ISSUE THREAD

**Issue by stoodsteal** [miguelgrinberg/flasky#128]
lcl@TP:~/flasky$ http --json --auth : GET http://127.0.0.1:5000/api/v1.0/posts/

http: error: ConnectionError: ('Connection aborted.', error(111, 'Connection refused')) while doing GET request to URL: http://127.0.0.1:5000/api/v1.0/posts/

But I can see the posts clicking the URL in the browser

**Comment by stoodsteal** [comment]
and I can see the posts clicking the URL in the browser

**Comment by stoodsteal** [comment]
I degraded the modules in the requirements and used venv. But it still did not work!

(venv)lcl@TP:~/flasky$ http --json --auth : GET http://127.0.0.1:5000/api/v1.0/posts/

http: error: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1.0/posts/ (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

**Comment by miguelgrinberg** [comment]
Do other endpoints work?

**Comment by stoodsteal** [comment]
‘Do other endpoints work?‘

They don't work either.

**Comment by miguelgrinberg** [comment]
Did you check in the code if the endpoints for API are implemented? Sounds like you might be using the wrong version of the code, maybe a version from a previous chapter? Look to see if you find the "api" blueprint.

**Comment by stoodsteal** [comment]
i finally found out the problem which  is that i did not run the server. 

No words in the chapter shows "runserver"

i am really new to web programe lol
