### ISSUE TITLE
How to run a single test in tests folder

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#130]
`python manage.py test` runs all tests in the tests folder - how can I just pick on test in that folder to run? Sorry, if this is a naive question. Thanks a lot for your help.

**Comment by miguelgrinberg** [comment]
Here is an example that runs the test named `test_invalid_reset_token` from `UserModelTestCase`.

    python -m unittest -q tests.test_user_model.UserModelTestCase.test_invalid_reset_token

**Comment by harrywang** [comment]
thanks, Miguel. This is exactly what I needed.

**Comment by harrywang** [comment]
Another related question: in manage.py， I have a few functions like the following:

```
@manager.command
def fakedata():
    """Generate fake testing data"""
    else:
        User.generate_test_users()  # create 5 named fake users
        User.generate_fake_users(100)  # create random users
        User.add_self_follows()  # create self-follows for all users
...

@manager.command
def deploy():
    """initialize the database and populate init data"""
    from flask.ext.migrate import init, migrate, upgrade

    upgrade()  # upgrade to the latest db schema
```

How I can run those functions in a test's setUp and tearDown?:

```
    def setUp(self):
        if not self.client:
            self.skipTest('Web browser not available')

    def tearDown(self):
        pass

```

Thanks.

**Comment by miguelgrinberg** [comment]
If you need to call these functions from manage.py and from tests, then I would move them down into the app package. Maybe put them in a app/deploy.py module, then on manage.py you can do something like this:

    from app.deploy import fakedata

    @manage.command
    def fakedata_command():
        fakedata()

And then same from your tests.

**Comment by harrywang** [comment]
Thanks a lot Miguel! I will try.
