### ISSUE TITLE
Question: Permissions not defined

### ISSUE THREAD

**Issue by Mohamad1994HD** [miguelgrinberg/flasky#131]
I have renamed "Permission" class to "Permissions"

`
class Permissions:
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENTS = 0x08
    ADMINISTER = 0x80`

and I didn't face any problem when using that name in python files, however when I used it in "index" for post editor rendering :

`
{% if current_user.can(Permissions.WRITE_ARTICLES) %}
        {{ wtf.quick_form(form) }}
        {% endif %}
`
it gave me error in jinja2 Permissions not defined !! I just tried to change the "Permissions" in the "index" to "Permission" and it worked well !!! , how can that be possible since I have it as "Permissions" in class definition!! ?

Book chapter 11
Thanks

**Comment by miguelgrinberg** [comment]
Did you inject the new class through a context processor? That's what makes the class available to templates. See this: https://github.com/miguelgrinberg/flasky/blob/13b747fb965785b5445796eeb99b4cfefc4c6778/app/main/__init__.py#L11.

**Comment by Mohamad1994HD** [comment]
Aha yes yes, so this context processor injection allow what I pass ( class ) to be available for the templates isn't it ?

**Comment by miguelgrinberg** [comment]
Correct.

**Comment by Mohamad1994HD** [comment]
Thanks
