### ISSUE TITLE
How to Plot a graph using values from database

### ISSUE THREAD

**Issue by hemanth22693** [miguelgrinberg/flasky#132]
![test](https://cloud.githubusercontent.com/assets/18014027/14800759/743381d0-0b09-11e6-845b-e324eda90557.png)
Hi,
   I am following the book "Flask Web Development". Thank you for a wonderful publishing, and I learnt a lot from the book. I have completed till chapter 9. I am working on a project that allows access to the labs from remote locations,  i.e., Remote Labs. I have done everything until chapter 9. Now, what I have done is that, simple interfaces like an LED, button and temp sensor have been connected to the pi. These interfaces will be controlled from the web. I have created a table to log the values of temp sensor in the format [rowid, datetime, temp]. Can you please tell me how to create a graph from the temp database and display it on the website. Are there any tutorials for these? Please let me know how to proceed.

Thanks in Advance,
Hemanth Kumar.

**Comment by miguelgrinberg** [comment]
This is a client-side task. You can use charts.js (http://www.chartjs.org/) or one of the many other charting libraries for the browser. On the server, all you need to do is render the data to the page, so that Javascript can then do the charts.

**Comment by hemanth22693** [comment]
Thanks, I will look into it and let you know if I have any questions.

**Comment by hemanth22693** [comment]
Hi, 
I have got one more question for you. I was successful with the video streaming. But, I was not able to run the other ajax calls simultaneously when the video is streaming. How do I go about it. I have uploaded the views.py and the index.html file. Please tell me how to proceed.
 Thanks in Advance.



[Test.zip](https://github.com/miguelgrinberg/flasky/files/252062/Test.zip)



![untitled](https://cloud.githubusercontent.com/assets/18014027/15071496/bef014d6-1351-11e6-8d5b-f9b3582f72c3.png)

**Comment by hemanth22693** [comment]
The actual output contains the Temperature in 'F below the thermometer, the state of the button whether it is pressed or not is printed below the "The button is" and the LED is controlled through the drop-down menu. But none worked since I called the video_feed() function.

**Comment by miguelgrinberg** [comment]
You need to use a web server that supports concurrency. The Flask development web server by default handles one request at a time, if you start a video feed then there is no way to send additional requests because the one request is always used by the feed.

You can try adding the `threaded=True` option to `app.run()`, that will enable the server to run incoming requests in separate threads. Or a better alternative would be to switch to a more robust web server, such as gunicorn or uwsgi.

**Comment by hemanth22693** [comment]
Thanks for that!!!

I am trying to plot a graph using highcharts in Flask. I have no problems when I give the data in the code itself. But when I retrieve the data from the database, it returns with a ',' in the end like
[(72,),(70.5,),(78.8,),(73,),(76,),(75,),]
So, this is not passing the data to the graph and I have an empty space on the webpage.

This is the code I have used:

views.py
@control.route("/")
def index(chartID = 'chart_ID', chart_type = 'line', chart_height = 350):
    chart = {"renderTo": chartID, "type": chart_type, "height": chart_height,}
    series = [{"data": [tempg()]}]
    title = {"text": 'My Title'}
    xAxis = {"title": {"text": 'xAxis Label'}}
    yAxis = {"title": {"text": 'yAxis Label'}}
    return render_template('control/index.html', uptime=GetUptime(), chartID=chartID, chart=chart, series=series, title=title, xAxis=xAxis, yAxis=yAxis)

def tempg():
    tempgrs = [tempg for tempg in Temperature.query.with_entities(Temperature.tempft).all()]
    return tempgrs

Is it because of the extra comma at the end, that i'm not able to get the chart or is it any other coding fault.

Thanks in Advance.

**Comment by hemanth22693** [comment]
Hi,
  I am stuck here for two weeks. Please help me solve this issue. Thanks in Advance.

**Comment by miguelgrinberg** [comment]
Can't really say for sure, but aren't you wrapping the array returned by `tempg()` into another array in `index()`?
