### ISSUE TITLE
Chapter 11.3 can not  generate some virtual articles

### ISSUE THREAD

**Issue by wuchangfeng** [miguelgrinberg/flasky#136]
hey. sorry to bother you, the problem I had met just like this:

> User.generate_fake(50)
> Post.generate_fake(50)
> Traceback
>  (most recent call last):
> File "<console>", line 1, in <module>
> NameError: name 'Post' is not defined

anything i had missed?

**Comment by miguelgrinberg** [comment]
Did you import the `Post` model?

**Comment by wuchangfeng** [comment]
Oh,the Post is missed in manage.py

thx a lot.
