### ISSUE TITLE
Callback chapter 13

### ISSUE THREAD

**Issue by Mohamad1994HD** [miguelgrinberg/flasky#137]
![q1](https://cloud.githubusercontent.com/assets/11790718/14936552/55e60e6c-0ef8-11e6-8092-9a29ff0e3a54.png)
Why we have the arguments 'oldvalue' , 'initiator' in the method if we don't use it? and how does it know that the first argument will be passed is the target and the second is the value, I think my question is related to the python programming language features.

thanks in advance.

**Comment by miguelgrinberg** [comment]
This is not specifically Python, it is a feature of SQLAlchemy. Here is the documentation for this feature: http://docs.sqlalchemy.org/en/latest/orm/events.html#sqlalchemy.orm.events.AttributeEvents.set
