### ISSUE TITLE
Sending Email with Gmail Config Successfully

### ISSUE THREAD

**Issue by jibolash** [miguelgrinberg/flasky#141]
If you face an issue sending an email with the gmail configurations, follow the following steps.
1. Sign in to your gmail account
2. In the top right corner, click on your profile picture and select "My Account"
3. Click on "Signing in to Google" under "Sign-in & Security"
4. Scroll to the bottom and turn on "Allow less secure apps"

You should be able to send emails successfully now, don't forget to turn it off when you are done, especially if it is your primary email address. 

Setting up an external SMTP email server as Miguel pointed out is the ideal way to do this, but the gmail configuration is good for testing

**Comment by miguelgrinberg** [comment]
Thanks for the summary.

**Comment by fkromer** [comment]
Some additional hint:
When you setup **email support with gmail on heroku** you will get an email "Somebody does know your passord" when the first user registers. You need to follow a hyperlink in this email to verify heroku as "trusted device" (Herokuapp.com is Amazon Technologies located in Ashburn, Virginia, United States).

**Comment by miguelgrinberg** [comment]
Closing this issue, as this is covered in the second edition of the book.
