### ISSUE TITLE
Question about if  the table in db has changed what should do ? 

### ISSUE THREAD

**Issue by wuchangfeng** [miguelgrinberg/flasky#142]
hey.  a question about db and table.

Some  chapter we checked out  and if  the table changed, what  we do is : 

     python manage.py db upgrade

but usually it will get a error just like this:

![](http://7xrl8j.com1.z0.glb.clouddn.com/error.jpg)

and  my friend met this question today.

i usually solve this error by :

     python manage.py db migrate -m"table changed"

     python manage.py db upgrade

and it works.

so i guess mybe every time we changed the table  we should renew a migrate ,just like above.

i do not know it is right or not? 

want to know more about it.

thx a lot.

**Comment by miguelgrinberg** [comment]
If you change a database table, then you need to do a "migrate" and then a "upgrade". If you are following the book using this git repository, the "migrate" portion is done for you as you move through the tags. So when following along with git, all you need to do is the "upgrade".

**Comment by wuchangfeng** [comment]
thank you,i think i get the point.
