### ISSUE TITLE
Some routes of API return in JSON response wrong prev / next URLs?

### ISSUE THREAD

**Issue by itnow** [miguelgrinberg/flasky#144]
Please, help. I didn't understand some routes of API with specified 'id'.

Methods
'get_user_posts(id)'
'get_user_followed_posts(id)'
'get_post_comments(id)'
don't use same method to generate prev/next URLs.
So we can't navigate between pages for specified post id or specified user id.

Why? Maybe it is mistyped?

Please review my pull request #143

I tested manually each route, I think it's now works like it should be by design.

Thank you.

**Comment by miguelgrinberg** [comment]
These fixes have been incorporated into the repository. Thanks!
