### ISSUE TITLE
Flask_files_preview

### ISSUE THREAD

**Issue by Mohamad1994HD** [miguelgrinberg/flasky#145]
Greetings, 

I am trying to add some functionalities to the blog app, by adding the ability to store and view files (pdf), fortunately I figured out how to store files in a static path,,, however when I wanted to preview I ran into some bugs like:
Using this method:
`return send_from_directory(path, filename)`
will sometimes give response HTTP 304 and so long time to wait for view,
I found in the docs another method which is for more safe usage:
`

filename = safe_join(path, filename)

    with open(filename, 'rb') as fd:

        return fd.read()
`

sometimes it will not render the file as shown in the attached picture.
What could be the reason of these errors and how can I handle this issue in a good way.

Thanks.
![err](https://cloud.githubusercontent.com/assets/11790718/15195907/a4705848-17d2-11e6-86ad-dc66c39a5fe2.png)

**Comment by miguelgrinberg** [comment]
First of all, the 304 status code is part of the HTTP caching mechanism. The server returns 304 when the client already has the file it is requesting. So there is nothing wrong with that code, it actually means you can save some bandwidth by not sending a file that the client already has.

The second issue is very likely a result of not setting the proper content type for the response. For a PDF file, the Content-Type header should be set to `application/pdf'.
