### ISSUE TITLE
What is the use of a few packages in the requirements.txt file?

### ISSUE THREAD

**Issue by priyankamandikal** [miguelgrinberg/flasky#157]
In particular, I was wondering what the following few packages are doing in the dependencies:
blinker
dominate
Mako - I read it's a template library that borrows from a few other libraries like Jinja2. If we're already using Jinja2, why do we need this one?
MarkupSafe - needed by Mako?
visitor
wheel

This requirements file was manually constructed right?

Also, in a broader sense, is it possible to reduce the number of dependencies in the app? When building a software system, how do we choose the packages that are suitable for the architecture. I realized that I have blindly been taking a lot of dependencies at face value without giving much thought as to why I couldn't have used another one. If I were to build another Flask app, I would probably end up using the same ones. I would merely be replicating the Flasky app structure in every app that I build, which may not be the best thing to be doing.

**Comment by miguelgrinberg** [comment]
Requirement files do not only store direct dependencies, but also dependencies of the dependencies and so on. And no, requirement files are not generated manually. After you load your virtual environment with all the packages that you need, running `pip freeze > requirements.txt` will generate the correct requirements file.

So it is normal to find packages you don't use or need in requirement files. These are used by the packages you do use. For example, Mako is used by Alembic, which is used by Flask-Migrate, which we use.
