### ISSUE TITLE
Chapter 8 static files

### ISSUE THREAD

**Issue by py-in-the-sky** [miguelgrinberg/flasky#16]
I believe the references to jquery and bootstrap should be moved from flasky/static to flasky/app/static.

**Comment by marti1125** [comment]
in console show an error about js  you can add libs
{{ super() }}
&lt;script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" /&gt;
&lt;script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" /&gt;
