### ISSUE TITLE
how to initialize the "roles" table to insert the data？

### ISSUE THREAD

**Issue by onlyanyz** [miguelgrinberg/flasky#160]
I have encountered some error:
"application not registered on db instance and no application bound to current context"
when I call Role.insert_roles() to initialize the "roles" table. Can you help me to know how to do this in a right way? @miguelgrinberg

**Comment by miguelgrinberg** [comment]
Try this:

```python
from app import app
with app.app_context():
    Role.insert_roles()
```

**Comment by onlyanyz** [comment]
Yes, it works! Thank you very much! I added the following code in my create_app method:
`from models import Role
 with app.app_context():
     db.create_all()
     Role.insert_roles()`

to create database and initialize them. But I wonder whether it is a good idea to do this in 'create_app' method, or should I create a new python file to handle the database creation and initializtion? Wish to hear your suggestion.
