### ISSUE TITLE
Send email with celery has error

### ISSUE THREAD

**Issue by 8cbx** [miguelgrinberg/flasky#163]
I tried using celery to send the email, but one error goes out:
EncodeError: can't pickle thread.lock objects

And the code of email.py is like this:
#encoding: utf-8
from threading import Thread
from flask import current_app, render_template
from flask.ext.mail import Message
from . import mail, celery

@celery.task
def send_async_email(app, msg):
    with app.app_context():
        mail.send(msg)

def send_email(to, subject, template, **kwargs):
    app = current_app._get_current_object()
    msg = Message(app.config['FLASKY_MAIL_SUBJECT_PREFIX'] + ' ' + subject,
                  sender=app.config['FLASKY_MAIL_SENDER'], recipients=[to])
    msg.body = render_template(template + '.txt', **kwargs)
    msg.html = render_template(template + '.html', **kwargs)
    thr = Thread(target=send_async_email.delay, args=[app, msg])
    thr.start()
    return thr

I don't know what's wrong, and could I get some help from you?  thx!

**Comment by miguelgrinberg** [comment]
You are sending data to the celery task that cannot move across processes. In particular, it appears some of the data you are sending to your task includes a Lock object.

**Comment by 8cbx** [comment]
OK, thx, I found another issue you write about sending mails in flask and I define another flask app in this file,  using this app to config celery.
