### ISSUE TITLE
Databased used on heroku

### ISSUE THREAD

**Issue by shajinzheng** [miguelgrinberg/flasky#164]
Just tried to deploy my own app on heroku following your example at https://github.com/miguelgrinberg/flasky/blob/master/config.py#L69

However, I found this https://devcenter.heroku.com/articles/sqlite3, which discourages us to use sqlite on heroku. I was just wondering if there is anything I missed about the deployment.

Thanks!

**Comment by miguelgrinberg** [comment]
Yes, the heroku deployment uses a Postgres database, not sqlite. The book explains how to obtain a database from Heroku.
