### ISSUE TITLE
MySQL server has gone away error

### ISSUE THREAD

**Issue by kilgorejd** [miguelgrinberg/flasky#165]
So if my `__init__.py` has:
`db = SQLAlchemy()`

`def create_app(config_filename):`
    `app = flask.Flask(__name__)`
    `app.config.from_pyfile(config_filename)`
    `db.init_app(app)`

Everything works fine as long as the timeout in MySQL has not been met since the Apache/WSGI server has been restarted. By default that is 8 hours.

What is your recommended approach for dealing with Flask-SQLAlchemy and database timeout?

**Comment by miguelgrinberg** [comment]
Is this a frequent problem? Normally these corner case situations happen once in a long while. A database timeout will make SQLAlchemy raise an exception, which in turn will cause a 500 response to the client. The next time, however, the connection will be reestablished, so the next request will work fine. If this isn't acceptable, you can build retry logic within a request, by caching the SQLAlchemy exception and retrying the query.

**Comment by kilgorejd** [comment]
Yes, unfortunately it happens quite frequently. Since i am not a Flask master  :)   could you please give me an example of where I'd catch the exception and retry?  Are you talking about a try:except block on each query?

**Comment by miguelgrinberg** [comment]
If it happens frequently, then I would invest time addressing the reason why these disconnects occur.

> Are you talking about a try:except block on each query?

A better option would be subclassing the query class, so that you don't have to add a try/except in every query.

**Comment by kilgorejd** [comment]
Thanks, Miguel!  Sorry to bother, but could you give me an example of catching the kind of exception you're referring to?

Cheers!
...John

**Comment by miguelgrinberg** [comment]
Honestly I have not seen this problem myself, but I imagine SQLAlchemy raises one of its exceptions? As I said before, this isn't normal, you should better spend time investigating why these disconnections happen.

**Comment by jdonson** [comment]
Look at mysqld error log.
https://dev.mysql.com/doc/refman/5.5/en/error-log.html

**Comment by kilgorejd** [comment]
Thanks all. I think there's a bug in the flask-sqlalchemy setting that the docs say should prevent this - 'SQLALCHEMY_POOL_RECYCLE' -- I initially thought this had fixed it, but it leads to spotty connections, where sometimes you have to hit refresh on the pages and sometimes not. So following Miguel's suggestion, I did this, which so far seems to work:

```
class Util:
@staticmethod
def query_result(query):
    try:
        result = db.session.execute(query)
    except:
        if exc.DisconnectionError:
            result = db.engine.execute(query)
        elif exc.InvalidRequestError:
            db.session.rollback()
            result = db.engine.execute(query)
        else:
            result = db.engine.execute(query)
```

I tried using 'engine' vs. 'session' because the docs say engine will always return a connection. I'm not sure if the 'db.session.rollback()' would work, actually, since it seems to me the 'session' object is a problem if the connections have gone away. I mainly put it there in case there was a problem elsewhere doing CRUD operations.  

For my CRUD operations, I'm working on this, although it's not 100% yet. The 'tblobject' is the result of ORM adding, like:
```
class Users(db.Model):
...
@staticmethod
def add_user(userDict):
    user = Users(name=userDict['name'])
    user.password = userDict['password']
    Util.exec_crud(user)
```

```
@staticmethod
def exec_crud(tblobject):
    if db.session:
        db.session.add(tblobject)
    else:
        db.engine.connect()
        db.session.add(tblobject)
    try:
        db.session.commit()
    except:
        if exc.InvalidRequestError:
            db.session.rollback()
            raise
```
I say not 100% because if I create a problem, like adding a user that already exists, I get the proper error, but then when I add a new user it adds but I have to refresh the browser to see it.

Thanks for the help!  I think you can close this one out!

cheers,
...john
