### ISSUE TITLE
Can't import object from __init__.py

### ISSUE THREAD

**Issue by Northwood128** [miguelgrinberg/flasky#173]
Hi Miguel! 

I'm using your book to write an app of my own. I'm not writing exactly what you describe in here but I'm using it as an example to I think you might be able to help me. 

```
from flask import Flask, g
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_simpleldap import LDAP
from flask_pymongo import PyMongo
from config import config

bootstrap = Bootstrap()
mail = Mail()
ldap = LDAP()
mongo = PyMongo()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    ldap.init_app(app)
    mongo.init_app(app,config_prefix='MONGO')

    #Here I need to register the Blueprints I create later

    #End of Blueprints

    return app`

Then I have my models.py

`from flask_login import UserMixin
from app import login_manager, mongo
from flask import g

print type(mongo)
print mongo.__dict__

class Permission:

    VIEW_SCENARIOS = 0x01               # 0000 0001
    LAUNCH_SCENARIO = 0x02              # 0000 0100
    EDIT_SCENARIO = 0x04                # 0000 1000
    ADMIN = 0x80                        # 1000 0000

class Role():

#    _client = MongoClient('mongodb://localhost:27017/')
#    _db     = _client.sid

    rolesCollection = mongo.db.Roles

    def roles_collection_in_db(self):
        role_document = self.rolesCollection.find_one()
        if role_document == None:
            print ("""Roles collection does not exists. Is this a fresh """
                  """ install?. You need to run the setup""")
            return False
        else:
            return True

    def assign_role(self,role='Guest'):
        role_document = self.rolesCollection.find_one({'name': role})
        return role_document

    def insert_roles(self):
        """
        Stores Roles on sid.Roles collection
        """

        roles = {
                "Guest":(Permission.VIEW_SCENARIOS, True),
                "User": (Permission.VIEW_SCENARIOS |
                         Permission.LAUNCH_SCENARIOS|
                         Permission.EDIT_SCENARIOS, False),
                "Admin": (Permission.VIEW_SCENARIOS |
                          Permission.LAUNCH_SCENARIOS|
                          Permission.EDIT_SCENARIOS|
                          Permission.ADMIN, False)
                }
        roleDict = {}
        for r in roles:
            if self.rolesCollection.find_one({'name': r}) == None:
                roleDict['_id'] = ObjectId()
                roleDict['name'] = r
                roleDict['permissions'] = roles[r][0]
                roleDict['is_default'] = roles[r][1]
                roles_collection.insert_one(roleDict)
                print "Saved "+r+" role in the database"
            else:
                print "Role "+r+" was already in the DB"
        self._client.close()

myRole = Role()

print myRole.assign_role
```

As you can see, I'm importing mongo from the init file, but when I'm trying to use it, I see that there is not the initialized version. I get this error:

$ python -m app.models
<class 'flask_pymongo.PyMongo'>
{}
Traceback (most recent call last):
  File "/usr/local/pythonz/pythons/CPython-2.7.11/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/pythonz/pythons/CPython-2.7.11/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/arecalde-contractor/development/sid/app/models.py", line 20, in <module>
    class Role():
  File "/home/arecalde-contractor/development/sid/app/models.py", line 25, in Role
    rolesCollection = mongo.db.Roles
  File "/home/arecalde-contractor/development/sid/env/lib/python2.7/site-packages/flask_pymongo/__init__.py", line 276, in db
    if self.config_prefix not in current_app.extensions['pymongo']:
AttributeError: 'PyMongo' object has no attribute 'config_prefix'

I understand that the config_prefix attribute gets set during the init_all call, but that happens after I call create_app. How do I use the initialized mongo object on my models? Sorry If anything of this seems to obvious, I'm just getting started with Flask.. Thanks for writing that book!

**Comment by Northwood128** [comment]
Ok, somehow the Markdown mangled everything

**Comment by miguelgrinberg** [comment]
I fixed your markdown :)

The problem you have is, I think, that you are accessing `mongo.db` in the global context, which is not going to work because that requires have an application and the mongo extension properly initialized.

If you can move all accesses to `mongo.db` to places where there is an application context and/or request context, then you will not see this error.

**Comment by Northwood128** [comment]
So I could store all the DB information under g?

**Comment by miguelgrinberg** [comment]
The app context is not for you, `mongo.db` needs that. If you look at the code that implements this property you'll see that it references `current_app`.

**Comment by Northwood128** [comment]
I'm confused. Cause for example. In flasky/app/models.py you just do

from . import db

And then just use it and it works.

**Comment by miguelgrinberg** [comment]
the `db` object from Flask-SQLalchemy is not implemented in the same way as the mongo one. In the SQLalchemy case, some of the functions of `db` are available without an app context. For example, I can create subclasses of `db.Model` without having an app context. I cannot, however, operate with the database, as any accesses to `db.session` will fail with the 'don't have an app context' error.

**Comment by Northwood128** [comment]
Oh I think I understand. The PyMongo object needs the app context, but the SQLAlchemy does not. Is it like that? If that's the issue here, I'll have to move stuff around to make it work.

**Comment by miguelgrinberg** [comment]
The problem is that you cannot query the db without an app context. That call where you say `mongo.db.Roles` cannot be in the global scope, needs to be in a function and invoked with an app context loaded.

**Comment by Northwood128** [comment]
There. You said it better. Ha. Thanks man! I'll work on my code.
