### ISSUE TITLE
Sending Email: port 587 error

### ISSUE THREAD

**Issue by changediyasunny** [miguelgrinberg/flasky#176]
When I use Port=587 for sending an email from smtp.abc.com" server, it says "SMTPException:STARTTLS not supported by server"
this is my config:
app.config['MAIL_USE_SSL'] = False
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_PORT'] = 587

Is there anything wrong with smtp server? or is there any dummy/alternative port that can be used with falask-mail to send email ?

**Comment by miguelgrinberg** [comment]
Seems your email server does not support TLS, or the configuration you are using is incorrect.
