### ISSUE TITLE
Can't create db

### ISSUE THREAD

**Issue by karl-kallavus** [miguelgrinberg/flasky#18]
Dear Miguel,

thanks you for your book,

I have some troubles, I am on chapter 8a.

I can't create a db, db init, db downgrade etc - it's ok, 
but when I start a server and add some text to form - I have this error:

```
sqlalchemy.exc.OperationalError

OperationalError: (OperationalError) no such table: users u'SELECT users.id AS users_id, users.username AS users_username, users.role_id AS users_role_id, users.password_hash AS users_password_hash \nFROM users \nWHERE users.username = ?\n LIMIT ? OFFSET ?' (u'dfh', 1, 0)
```

**Comment by MrReN** [comment]
@kodemi ,thanks

**Comment by impactanalysts** [comment]
I ran into the same error posted by karl-kallavus. Miguel's solution (upgrade db, then run server) worked for me. Thanks Miguel!

**Comment by Quirel** [comment]
I have same problem as @karl-kallavus.
Tried:
rm data-devsqlite
python manage.py shell db upgrade
It doesn't help.
--------------
Then deactivated venv.
Created another directory and done:
$ git clone https://github.com/miguelgrinberg/flasky.git
$ cd flasky
$ git checkout 8a

- created new venv, activated, installed all from requirements.txt

$ python manage.py db upgrade
$ python manage.py runserver

And result is the same. I tried it on windows and linux (on different machines)
-----------------
Also tried deletint migrations/ and *.sqlite.
Then
$ python manage.py db init
$ python manage.py db migrate (And there were users table and roles table in logs)
$ python manage.py db upgrade
... The result was same. Same error about 'no such table...'

**Comment by miguelgrinberg** [comment]
@Quirel just to make sure other people seeing this don't get confused, this line:

    python manage.py shell db upgrade

should be changed to:

    python manage.py db upgrade

**Comment by Quirel** [comment]
@miguelgrinberg fixed, thank you. (It was about 4:00 am, when I wrote comment)

**Comment by xinqiu** [comment]
Thx, and it helps me very much. I was confused about this for several hours.

**Comment by Morriaty-The-Murderer** [comment]
Hello, @miguelgrinberg 
While creating db on Heroku,why it failed?
```python
File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 76, in run_migrations_online
    **current_app.extensions['migrate'].configure_args)
AttributeError: '_MigrateConfig' object has no attribute 'configure_args'
```

**Comment by miguelgrinberg** [comment]
@Morriaty-The-Murderer My guess is that the version of Flask-Migrate you have in your requirements.txt file does not match the version that is in your local virtualenv. Can you check?

**Comment by Morriaty-The-Murderer** [comment]
@miguelgrinberg 
I specify the version, and it worked, thank you very much!

**Comment by zuizao** [comment]
python manage.py db migrate
python manage.py db upgrade
this works for me, thanks @kodemi

**Comment by spaceled** [comment]
I have a such Error. I tried to upgrade my DB by your instructions. But I does not upgrade my db its just run like as 

> $ python manage.py runserver

Please, check the image I attached here.

[http://tinypic.com/r/2eqco4w/9](url)
