### ISSUE TITLE
__init__ wan't called

### ISSUE THREAD

**Issue by trudger123** [miguelgrinberg/flasky#182]
In sample 10-15, the **init** wasn't called when a user is logged in. I find out that although  User.query.filter_by(xxx).first() returned an User object but it's **init** wasn't called? So that self.avatar_hash wasn't generated. I'm curious that how it's possible? Thank you.

**Comment by miguelgrinberg** [comment]
I don't understand what you mean. The `__init__` method is called when an object is created. This includes when an object is loaded from the database. Have you added a print statement in `__init__` to debug why the avatar hash is not set?

**Comment by trudger123** [comment]
That's where it confused me. The __init__ wasn't called when it's loaded from database like: User.query.filter_by(xxx).first()

I added print to it and here are logs:

```
>>> u1 = User.query.filter_by(username='john').first()
>>> u2 = User()
user init
avatar_hash 3=None
>>> u1
<User u'john'>
```

You can see that u1 is an User object but __init__ wasn't called like u2. I even added a simple log file but nothing in it too. Here is what I did to __init__ procedure:
```
 def __init__(self,  **kwargs):
        logfile = open('./logfile.txt', 'wr')
        logfile.write('user inited 5555')
        logfile.close
        print('user init')
```

**Comment by miguelgrinberg** [comment]
Okay. I stand corrected. It appears that SQLAlchemy does not invoke the `__init__` method when it creates and object and populates it from data read from the database.

But why is that a problem? What's not working?

**Comment by trudger123** [comment]
For the sample itself, it's not working as you said that the hash code will be calculated during model initialization. But I think it's not a big deal, just several more calculations of hash code. 

Actually, the main reason I contacted you is that I want confirm whether I'm right or not about this __init__ procedure since I'm new to Python. Could you please give me a hint that how it's possible __init__ wasn't called when an object is created? I though it's like a constructor in C++ which must be called. Thank you for you time.

**Comment by miguelgrinberg** [comment]
@trudger123 when I said that the hash is created during initialization, that was meant to say that when you create a user, the hash is automatically created. There is actually code elsewhere that handles the case of a user that was created before the avatar functionality was added, by creating a hash on the fly.
