### ISSUE TITLE
unique constraint on the email column of the User model is case sensitive

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/flasky#183]
I am able to create multiple accounts using the same email address by varying the case.

**Comment by coreybrett** [comment]
Can SQL Alchemy be configured to treat a column in a case insensitive manner for queries? And/or always normalize the data on read and write operations? Or would I need to do that in all my client code?

**Comment by miguelgrinberg** [comment]
Doing this at the database level is possible, but each database does this differently.

Doing it at the SQLAlchemy level is also possible, in a couple of ways. You can create a custom data type, say `CaseInsensitiveString` that inherits from the SQLAlchemy text type and overloads the comparison operator. There is an example of this done with integers in the documentation: http://docs.sqlalchemy.org/en/latest/core/custom_types.html#types-operators

Another way to do this with SQLAlchemy is to set up an event that is invoked before data is written to the database. At this time you have the opportunity to normalize the data, for example, by making the string lower case.

**Comment by greyli** [comment]
By the way, to maintain consistency, we also need to lower the email string before query it from the database.

**Comment by unuseless** [comment]
How i handle this is to have 2 columns for email:  one as the user fills it in, e.g. J.Smith@example.com, and a column canonical_email, which is downcased (j.smith@example.com).
This allows to display the email to a user as she expects, and to compare a canonical representation for duplicates etc.
