### ISSUE TITLE
AttributeError: '_AppCtxGlobals' object has no attribute 'current_user'

### ISSUE THREAD

**Issue by wagnerdelima** [miguelgrinberg/flasky#185]
The code was working perfectly untill I reached chapter about API. Now, it points to this file and piece of code:

authentication.py

in line: if not g.current_user.is_anonymous and not g.current_user.confirmed:
error: AttributeError: '_AppCtxGlobals' object has no attribute 'current_user'

**Comment by miguelgrinberg** [comment]
Something must be missing on your version of the app. See below where `g.current_user` is set:

https://github.com/miguelgrinberg/flasky/blob/master/app/api_1_0/authentication.py#L22

**Comment by wagnerdelima** [comment]
Not really. My code is just the same as yours. Actually I though that: As in the before_request method tha call will be made before every request, how would the g.current_user be defined if you call it in the very before_request method?

**Comment by miguelgrinberg** [comment]
The `verify_password` is called automatically by the `login_required` decorator that is attached to the before_request function. That runs first and sets `g.current_user`.

It would be useful if you can debug on your side to figure out why the `verify_password` function isn't setting `g.current_user`.

**Comment by ListenLove** [comment]
Thanks!
I also forgot to set `g.current_user = user`, the `user` is set as `user=User.query.filter_by(email=email_or_token.lower()).first()` before.
