### ISSUE TITLE
I'm able to store data in mysql database but not query it

### ISSUE THREAD

**Issue by bitcoinwale** [miguelgrinberg/flasky#190]
In my model, I have two classes User and Contact. I can query and insert in User without any problem but in Contact I'm only able to insert the data not query it. It gives me the following error:
Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Contact.query has an attribute 'all'
Can you help me to resolve it?

**Comment by miguelgrinberg** [comment]
What's the full stack trace of the error?

**Comment by bitcoinwale** [comment]
I've solved it, actually, I made an attribute named query due to which it
was not responding quite what expected. Thank you for responding quickly.

**Comment by miguelgrinberg** [comment]
Sure, glad you figure it out.
