### ISSUE TITLE
    from six.moves import urllib_parse as urlparse ImportError: cannot import name 'urllib_parse'

### ISSUE THREAD

**Issue by jiapan1984** [miguelgrinberg/flasky#195]
PS C:\Users\Documents\GitHub\flasky> python.exe .\manage.py create_db
Traceback (most recent call last):
  File ".\manage.py", line 4, in <module>
    from app.models import User, Follow, Role, Permission, Post, Comment
  File "C:\Users\Documents\GitHub\flasky\app\models.py", line 6, in <module>
    import bleach
  File "C:\Python34\lib\site-packages\bleach\__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
  File "C:\Python34\lib\site-packages\html5lib\sanitizer.py", line 5, in <module>
    from six.moves import urllib_parse as urlparse
ImportError: cannot import name 'urllib_parse'

**Comment by jiapan1984** [comment]
the six module version is: Version: 1.3.0

**Comment by miguelgrinberg** [comment]
Can you show me the output of `pip freeze` please?

**Comment by jiapan1984** [comment]
Flask==0.11.1
Flask-Bootstrap==3.3.7.0
Flask-HTTPAuth==3.2.1
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Migrate==2.0.0
Flask-Moment==0.5.1
Flask-PageDown==0.2.2
Flask-Restless==0.13.1
Flask-SQLAlchemy==2.1
Flask-Script==2.0.5
Flask-WTF==0.13.1
Jinja2==2.8
Mako==1.0.4
Markdown==2.6.7
MarkupSafe==0.23
SQLAlchemy==1.1.2
WTForms==2.1
Werkzeug==0.11.11
alembic==0.8.8
bleach==1.4.3
blinker==1.4
bottle==0.12.8
caravel==0.11.0
click==6.6
dominate==2.2.1
gunicorn==17.5
html5lib==0.9999999
itsdangerous==0.24
mimerender==0.5.4
parsedatetime==2.0
pydruid==0.3.0
pyhive==0.2.1
python-dateutil==2.1
python-editor==1.0.1
python-mimeparse==0.1.4
requests==2.11.1
simplejson==3.8.2
six==1.3.0
sqlalchemy-utils==0.32.7
sqlparse==0.1.19
thrift==0.9.3
thrift-sasl==0.2.1
visitor==0.1.3

python version is： Python 3.4.2

**Comment by miguelgrinberg** [comment]
Your 1.3.0 version of six is fairly old. Note that this project requires v1.4.1. I think if you upgrade it you'll find this error gone.

Also, as an advice, you should use a virtual environment when you install your packages, it's not a good practice to install on packages system wide.

**Comment by jiapan1984** [comment]
@miguelgrinberg Thank you.
