### ISSUE TITLE
why main blueprint doesn't need 'main/*.html' when render_template function is used?

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/flasky#196]
I'm using your code to integrate into my project. But I'm unable to make the auth blueprint's template working. Then I saw that main blueprint doesn't need to have a subdirectory in the templates folder. Can you explain why auth blueprint needs to have a subdirectory but main doesn't?
Also, help me to find the bug in render the template from templates folder in auth/views.py file

Here is the traceback of the error:

127.0.0.1 - - [23/Oct/2016 15:09:28] "GET /auth/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/www/buyucoin/app/auth/views.py", line 46, in login
    return render_template('auth/login.html', form=form)
  File "/srv/www/env/lib/python3.4/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/srv/www/env/lib/python3.4/site-packages/flask/app.py", line 765, in update_template_context
    context.update(func())
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [23/Oct/2016 15:09:28] "GET /auth/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 15:09:28] "GET /auth/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 15:09:28] "GET /auth/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 15:09:28] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by deveshaggrawal19** [comment]
I don't know what I did, but now all my syntax for render_template are giving me the same error. Please help me to get out of this mess.

**Comment by miguelgrinberg** [comment]
Blueprints do not need to have their templates in a subdirectory, that is merely a choice I've made to keep the templates for each blueprint separate. You don't have to do this if you don't want to.

As far as your error, I'm not sure, but it seems something you are iterating on inside your template isn't set correctly. Are you passing a valid `form` object?

**Comment by deveshaggrawal19** [comment]
Everything was right, but suddenly it broke down. I'll try a template without form object and will get back to you.

**Comment by deveshaggrawal19** [comment]
The template I'm using:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Buyucoin{% endblock %}</title>
</head>
<body>
{% block body %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<h1>{{permission}}</h1>
<p>{% block body1 %}{% endblock %}</p>
{% endblock %}
</body>

It is showing the same error in this as well

**Comment by miguelgrinberg** [comment]
Do you use any context processors in your application?

**Comment by deveshaggrawal19** [comment]
yes I was simply trying the example but then i removed the return syntax and simply put pass
so it looks like this:
@main.context_processor         # to add variables in template scope
def include_template_variables():
    # return {'Permission': 'adf'}
    pass

**Comment by deveshaggrawal19** [comment]
And I'm very thankful for replying so instantly, in a great debt of yours.

**Comment by miguelgrinberg** [comment]
Yeah, putting `pass` will make the function return `None`, while in fact Flask expects that to be a list.

**Comment by deveshaggrawal19** [comment]
ok

**Comment by deveshaggrawal19** [comment]
Thank you so much for solving my problem once again. You are such a life saver. Keep up the good work Sir. Honestly, we beginners need people like you. Thank you once again.
