### ISSUE TITLE
Running flasky in specific tag version

### ISSUE THREAD

**Issue by fkromer** [miguelgrinberg/flasky#197]
I tried to run flasky in tag version 3d (which does not contain a requirements.txt file) by doing the following...

- clone flasky: `~/ws_github $ git clone https://github.com/miguelgrinberg/flasky.git`
- checkout tag 3d: `~/ws_github $ git clone https://github.com/miguelgrinberg/flasky.git`
- create virtualenv and activate it like described on [book first edition 2014 , p. 4]: `~/ws_github/flasky $ virtualenv venv`
- activate venv: `~/ws_github/flasky $ source venv/bin/activate`
- install flask [book first edition 2014 , p. 6]: `~/ws_github/flasky $ pip install flask`
- install flask-script [book first edition 2014 , p. 17]: `~/ws_github/flasky $ pip install flask-script`

... flask and flask-script seems to be installed in the venv properly...

    (venv)florian@florian-desktop ~/ws_github/flasky $ pip freeze
    Flask==0.11.1
    Flask-Script==2.0.5
    Jinja2==2.8
    MarkupSafe==0.23
    Werkzeug==0.11.11
    argparse==1.2.1
    click==6.6
    itsdangerous==0.24
    wsgiref==0.1.2

...but when I try to run flasky I get the following error response [book first edition 2014 , p. 19]:

    (venv)florian@florian-desktop ~/ws_github/flasky $ python hello.py runserver --host 0.0.0.0
    Traceback (most recent call last):
      File "hello.py", line 2, in <module>
        from flask_script import Manager
    ImportError: No module named 'flask_script'

Running flask with the system installation of python (with flask and klask-script installed) does result in the same error response.

**Comment by miguelgrinberg** [comment]
What version of Python are you using? I'm wondering if you have anything older then 2.7.x, which I have never tested.

**Comment by fkromer** [comment]
The Python of the venv is Python 3.4.3. (I switched the system default version from version 2.7.1 to version 3.4.3 some time ago.) For which versions is the code tested? I would prefer to install a Python 3 version into the venv...

**Comment by miguelgrinberg** [comment]
3.4 should be fine. What happens if your start a Python console and type `import flask_script`?

**Comment by fkromer** [comment]
(venv)florian@florian-desktop ~/ws_github/flasky $ python
    Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
    [GCC 4.8.4] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import flask_script
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'flask_script'
    >>>

**Comment by miguelgrinberg** [comment]
Does anything change if you run `pip install flask-script` and then again the above in the python console?

**Comment by fkromer** [comment]
I assumed to use Pythono 2.7.x and installed all packages using `pip`. But as I use Python 3.4.3 I should have used `pip3` instead I guess...

When I run `(venv)florian@florian-desktop ~/ws_github/flasky $ pip3 freeze` the package of interests are not listed.

**Comment by miguelgrinberg** [comment]
No, wait. If you activated the right virtualenv, the `pip` and `python` should invoke the correct version for both Python 2 and Python 3. So something isn't right in your virtualenvs.

**Comment by fkromer** [comment]
You are totaly right. I am just setting up a clean venv...

**Comment by fkromer** [comment]
**With a clean venv** I just did have to install the required packages for **tag 3d**:

(venv)florian@florian-desktop ~/ws_github/flasky $ pip install flask
Downloading/unpacking flask
...
(venv)florian@florian-desktop ~/ws_github/flasky $ pip install flask-script
Downloading/unpacking flask-script
...
(venv)florian@florian-desktop ~/ws_github/flasky $ pip install flask-bootstrap
Downloading/unpacking flask-bootstrap

And I was able to run flasky:

    (venv)florian@florian-desktop ~/ws_github/flasky $ python hello.py runserver --host 0.0.0.0
     * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
    127.0.0.1 - - [24/Oct/2016 08:55:40] "GET / HTTP/1.1" 200 -
    127.0.0.1 - - [24/Oct/2016 08:55:40] "GET /static/favicon.ico HTTP/1.1" 200 -
