### ISSUE TITLE
I'm not able to use fonts in html

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/flasky#199]
I don't know how to add fonts in CSS and HTML so that flask renders it properly

**Comment by deveshaggrawal19** [comment]
and can you please debug a little problem for me.
this the link for repository
https://github.com/deveshaggrawal19/waasle
the problem is that I downloaded a template and it's working fine. I want to integrate it with the flask to make it dynamic but the CSS files are a little messed up I guess.
The website should be like this
![screenshot from 2016-10-25 00 11 52](https://cloud.githubusercontent.com/assets/17562041/19658986/bdb59550-9a47-11e6-8153-595852128ad1.png)
but it is like this
![screenshot from 2016-10-25 00 11 30](https://cloud.githubusercontent.com/assets/17562041/19659003/cc8501b0-9a47-11e6-8bae-cac328756205.png)
now I did some debugging and found out that style.css is not working properly but couldn't understand why because my front-end is weak. Please help me out in this mess

**Comment by miguelgrinberg** [comment]
Look in your browser console for errors such as css or js files that were not loaded.

**Comment by deveshaggrawal19** [comment]
this is the error I don't think this is it.
![screenshot from 2016-10-25 01 06 26](https://cloud.githubusercontent.com/assets/17562041/19660923/494e8e8a-9a4f-11e6-833a-dcfd89ba6662.png)

**Comment by miguelgrinberg** [comment]
You need start by debugging why the images don't load. Sorry, but from looking at the files I can't see what the problem is.

**Comment by deveshaggrawal19** [comment]
can you recommend someone who can i can pursue to correct these mistakes?

**Comment by deveshaggrawal19** [comment]
at least tell me how to add fonts in CSS and HTML

**Comment by miguelgrinberg** [comment]
@deveshaggrawal19 not sure what you are asking. Are you looking to hire someone, or just need advice? As I said, the templates and CSS files look fine overall, you just need to debug it. Maybe start with a simpler design first, once you make that work move up to the complex one.

As far as fonts in css, have you seen the documentation? http://www.w3schools.com/css/css3_fonts.asp

**Comment by deveshaggrawal19** [comment]
No, Now everything is fine, It is working fine now, don't know which debugging triggered it. But thanks anyway.
