### ISSUE TITLE
After login in and not confirming it by email i cannot open any link unless i confirm first!!!

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/flasky#200]
I'm using your code and modifying a little bit. The problem is after I log in any page that I visit only redirects me to the auth.unconfirmed function. I want to make the website visible to unconfirmed users also, not the full website but some part of it like functions that are in the main blueprint. What could I possibly change in before request handler for the requisite outcome?

**Comment by miguelgrinberg** [comment]
The little bit of logic here is what you want: https://github.com/miguelgrinberg/flasky/blob/master/app/auth/views.py#L16-L19.

If you remove that, then unconfirmed users will be able to navigate the website freely. If you change the condition you can control what these users can see.

**Comment by deveshaggrawal19** [comment]
I do not want the unconfirmed users to navigate freely. I just want to limit them. But your code is limiting them too much. I don't know why logged in users who are visiting main.index are redirecting to auth.unconfirmed. What changes should I make so that users are redirected to auth.unconfirmed if only a decorator of @login_required is used?

**Comment by miguelgrinberg** [comment]
The login_required decorator is not related to the confirmed/unconfirmed verifications. I think it would be really convoluted to try to find out if an endpoint has the login_required decorator. A better approach would be to build another decorator that runs the confirmed logic, maybe call it `only_confirmed`. Then you can add this decorator to all the views that you want unconfirmed users to be prevented from. You can use the example decorator from the Flask documentation as a based to build it: http://flask.pocoo.org/docs/0.11/patterns/viewdecorators/.

**Comment by deveshaggrawal19** [comment]
I was thinking that only, but thought there could be another way around. None the less I'll first try to make to make the decorator and will get back to you.

**Comment by deveshaggrawal19** [comment]
Thank you very much Sir, I was able to successfully implemet, using your guide and link, the desired output.
