### ISSUE TITLE
local debugging of flask-mail with Gmail

### ISSUE THREAD

**Issue by fkromer** [miguelgrinberg/flasky#201]
I was just able to get the email support of [flasky (tag 10d)](https://github.com/miguelgrinberg/flasky/tree/10d) working by changing my Gmail settings. It seems like when flasky is run locally it is considered by Gmail as some "less secure app" (like "Some Desktop mail clients like Microsoft Outlook and Mozilla Thunderbird") which [needs to be explicitly allowed to communicate to](https://support.google.com/accounts/answer/6010255?hl=en). I did not set up email support for a website with Gmail for a while. But I can not remember this issue.

Did they change their security policy? I assume that I should be able to restore my settings to "forbid communication with less secure apps" after local debugging?

BTW: The functonality works just fine! But there is some little inconsstency in the book [1st edition, 2014, page 72] which states `(venv) $ export FLASKY_ADMIN=<your-email-address>` for Unix users and `(venv) set FLASKY_ADMIN=<Gmail username>` which could confuse some readers. I am not sure but I think I was able to login into Gmail without "@googlemail.com" or "@gmail.com" in the username.

**Comment by miguelgrinberg** [comment]
@fkromer yes, Gmail changed the security policies around gmail a while after the book came out. When I get a chance to refresh the book I will add the new steps required to set up gmail for testing. As far as I know, the username needs to include the @gmail.com. Maybe it also works without it, but I have always included the full email.

And thanks for pointing out the inconsistency with `FLASKY_ADMIN`, that will also be corrected next time an update to do book is released.

**Comment by fkromer** [comment]
Thanks for the fast response. I did profit from your book soo much that I wanted to give you something back by providing you with this info (for the case you did not catch it by yourself already).

**Comment by whieronymus** [comment]
So if I'm understanding the two of you correctly, the email should work without having to change my google settings to work with "Less secure apps" once I host it properly, but when testing locally I need to update my google app settings. Is that right?

**Comment by miguelgrinberg** [comment]
@whieronymus No. Gmail is only viable as a way to run simple tests in development, it is not a production email solution (and never was, even before these changes were made). If you need to send email from your production server, then you need to run your own email server, or use a third party email service such as mailgun.

**Comment by whieronymus** [comment]
@miguelgrinberg  Ah, I see. This is my first dive into sending emails. My company's email is run through gmail (gsuite), if I wanted to send an email from one of our accounts (info@mycompany.com for example. You're saying I'd need to use a 3rd party app like mailgun? I'm pretty certain we don't have our own email server.

**Comment by miguelgrinberg** [comment]
@whieronymus if you have a paid gmail service then you may be able to use them for production. They have documentation on what their limits are for sending email, make sure that works for you, because as far as I remember their quotas aren't that great.

**Comment by whieronymus** [comment]
@miguelgrinberg Got it, I'll take a closer look. Thanks for your help! I love your book!
