### ISSUE TITLE
how to understand the password passed to User Model

### ISSUE THREAD

**Issue by ecod** [miguelgrinberg/flasky#203]
line 55 of auth/views.py

<pre>
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
</pre>

but in models.py

class User():

<pre>
class User(UserMixin, db.Model):
</pre>

there isn't a password column in table users.

How do it work?

by @property?

**Comment by miguelgrinberg** [comment]
Yes, there is a write-only property that takes the password, applies the hashing algorithm and then saves the result in the `password_hash` column. See https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L136-L138.
