### ISSUE TITLE
Package dependency issue when installing requirements of tag 17c with Python 3.4.3

### ISSUE THREAD

**Issue by fkromer** [miguelgrinberg/flasky#204]
When I try to install the dependencies of the **flasky tag 17c** into a new, clean venv with Python 3.4.3 I get the following error message:

    (venv)florian@florian-desktop ~/ws_github/flasky $ python --version
    Python 3.4.3
    (venv)florian@florian-desktop ~/ws_github/flasky $ pip install -r requirements.txt
    Downloading/unpacking Flask==0.10.1 (from -r requirements/common.txt (line 1))
    ...
    Downloading/unpacking gunicorn==18.0 (from -r requirements.txt (line 3))
      Downloading gunicorn-18.0-py33-none-any.whl (93kB): 93kB downloaded
    Downloading/unpacking psycopg2==2.5.1 (from -r requirements.txt (line 4))
      Downloading psycopg2-2.5.1.tar.gz (684kB): 684kB downloaded
      Running setup.py (path:/home/florian/ws_github/flasky/venv/build/psycopg2/setup.py) egg_info for package psycopg2
    
        Error: pg_config executable not found.
        
        Please add the directory containing pg_config to the PATH
        or specify the full executable path with the option:
        
            python setup.py build_ext --pg-config /path/to/pg_config build ...
        
        or with the pg_config option in 'setup.cfg'.
        Complete output from command python setup.py egg_info:
        running egg_info
    
    creating pip-egg-info/psycopg2.egg-info
    
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    warning: manifest_maker: standard file '-c' not found
    
    
    
    Error: pg_config executable not found.
    
    
    
    Please add the directory containing pg_config to the PATH
    
    or specify the full executable path with the option:
    
    
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    
    
    or with the pg_config option in 'setup.cfg'.
    
    ----------------------------------------
    Cleaning up...
    Command python setup.py egg_info failed with error code 1 in /home/florian/ws_github/flasky/venv/build/psycopg2
    Storing debug log for failure in /home/florian/.pip/pip.log

The log file was not helpful to me.

**Comment by miguelgrinberg** [comment]
This is not a package dependency, it is just failing to install the postgres Python package because you do not have postgres installed on your machine. The 17.c tag is for deploying to Heroku, and this requires Postgres. If you want to bypass the error and install everything anyway, just comment out the `psycopg2` line in the requirements.txt file.

**Comment by fkromer** [comment]
Thanks a lot for the lightning fast answer.
