### ISSUE TITLE
Heroku foreman command is deprecated

### ISSUE THREAD

**Issue by fkromer** [miguelgrinberg/flasky#205]
Like [a Heroku local dev site](https://devcenter.heroku.com/changelog-items/692) states `heroku local` has to be used instead of `foreman`. How do I have to adjust the instructions on [book, first edition, page 223, "Testing with Foreman"] to beeing able to test flasky tag 17c locally?

**Comment by miguelgrinberg** [comment]
First of all, if you want to use foreman you can, the difference is that you have to install it separately, as it isn't included in the toolbelt package anymore.

To use `heroku local` I think nothing needs to change. The configuration still goes in the `.env` file, and the commands in the `Procfile`, so running just `heroku local` should start gunicorn on your machine.

**Comment by fkromer** [comment]
I use **tag 17c** with modified requirements.txt file what you suggested as solution for [issue 204 (psycopg2 line in the requirements.txt file)](https://github.com/miguelgrinberg/flasky/issues/204). Despite of that I did add a local .env file with *FLASK_CONFIG=heroku*, *MAIL_USERNAME=[my username]*, *MAIL_PASSWORD=[my password]* [book, 1st edition, p. 223] and  *SSL_DISABLE=1* [book, 1st edition, p. 224] specified. Then I had to run the commands from [book, 1st edition, p. 223] in a slightly different syntax `heroku local:run python manage.py deploy` followed by `heroku local:start`. Flasky runs on `http://0.0.0.0:5000` just fine now. Thanks.
