### ISSUE TITLE
Authentication not working when deploayed on Heroku using Gmail email

### ISSUE THREAD

**Issue by fkromer** [miguelgrinberg/flasky#208]
I am running a [modified version of flasky tag 17c on heroku](https://npkromer.herokuapp.com). I did set up the hosted environment that one gets an account confirmation email from my Gmail account (admin email). When a new user clicks on the confirmation link the appropriate flash message ("You have confirmed your account. Thanks!") is shown but the user gets redirected to the unconfirmed view ("Hello, Flo! You have not confirmed your account yet. Before you can access this site you need to confirm your account. Check your inbox, you should have received an email with a confirmation link. Need another confirmation email? Click here") on route `.../auth/unconfirmed`. I disabled SSL on heroku (like in the local environment) but the behaviour is the same. Running the website locally using `heroku:local` the authentication process with Gmail is working fine. But I could not identify any differences which could be the root cause for this behaviour.

**Comment by miguelgrinberg** [comment]
I think this could be https://github.com/miguelgrinberg/flasky/issues/58, but to save you time reading the long comment thread in that issue, I determined that to be a Flask bug in release 0.10.1 or older. If you are on that release, try upgrading Flask to 0.11.1, and let me know if that helps.

**Comment by fkromer** [comment]
Thanks @miguelgrinberg, you saved my day!
