### ISSUE TITLE
注册了一个账户，而且邮箱设置了FLASKY_ADMIN，为何不是管理员呢？

### ISSUE THREAD

**Issue by lianfulei** [miguelgrinberg/flasky#209]
怎么编辑文章，修改等等

**Comment by zhouAndy** [comment]
你这个问题问得很怪，而且你确定作者可以看懂中文？请详细叙述你的问题

**Comment by SulphurFH** [comment]
MarkDown可以啊，而且这样子作者看不懂哎

2016-11-07 15:20 GMT+08:00 YaYu <notifications@github.com>:

**Comment by xjr7670** [comment]
给一个不得已之下的解决办法：直接修改sqlite数据库文件，把你的账户的类型修改为管理员。

当然，最好还是要先把代码弄明白、把功能改好

**Comment by palapython** [comment]
你可以参考 flask_web 中设置账号为管理员

**Comment by bjmayor** [comment]
我也遇到这个问题了。Debug发现是User的__init__方法根本没有调用。。
暂时还不知道怎么 解决。

**Comment by bjmayor** [comment]
晓得了。。在Role功能之前的用户，在增加Role功能之后，他的值是空的。但是因为用户已经在数据库了，直接查出来，不会调用__init__方法，所以不会自动设置权限。只有在注册的时候，才会调用__init__，然后自动设置好Role。 我手动给User设置了下Role，然后就可以了。

**Comment by lianfulei** [comment]
谢谢大家回复

**Comment by huo543810492** [comment]
哥们我刚开始学，通过manage runserver能运起来，但是我一注册就报错
sqlalchemy.exc.StatementError
sqlalchemy.exc.StatementError: utcnow() takes no arguments (1 given) (original cause: TypeError: utcnow() takes no arguments (1 given)) 'INSERT INTO users (email, username, role_id, password_hash, confirmed, name, location, about_me, member_since, last_seen, avatar_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' [{'password_hash': 'pbkdf2:sha1:1000$8vGSabau$b638c2e8b25474ee28dfb9d1adbc5f84930d569b', 'username': 'huo543810492', 'role_id': None, 'email': '550300893@qq.com', 'location': None, 'about_me': None, 'name': None, 'avatar_hash': 'c2348ea98e157edcd464a7786f2319c4'}]
你有这个问题不？

**Comment by SulphurFH** [comment]
看报错，可能是utcnow()方法参数的问题，是不是这个方法在一个class里面而没有加self啊？

2017-02-16 21:04 GMT+08:00 huo543810492 <notifications@github.com>:

**Comment by huo543810492** [comment]
这里么？  貌似就这里用了
  def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
然后我加了还是报错，不知道是我下的版本有问题还是怎么
manage test也有18个错

**Comment by SulphurFH** [comment]
self.last_seen = datetime.utcnow()
是给这个class加了一个属性叫last_seen，这个属性的值是datetime.ntcnow(),所以你想db.seesion.add()加入数据的时候，是不是要把这个属性的值放进去呢，就是
db.session.add(self.last_seen)。试一下~我也是猜测

2017-02-16 21:29 GMT+08:00 huo543810492 <notifications@github.com>:

**Comment by huo543810492** [comment]
还是不行~阿西吧

**Comment by WuYiP** [comment]
我也是出现相同的情况，用户已经登录进去了，但是用户的账号还未确认？这个要怎么整？我尝试运行python mange.py shell 
＞＞ｕ＝Ｕｓｅｒ（ｅｍａｉｌ＝＇ｊｏｈｎ＠ｅｘａｍｐｌｅ．ｃｏｍ＇，ｕｓｅｒｎａｍｅ＝＇ｊｏｈｎ＇，ｐａｓｓｗｏｒｄ＝＇ｃａｔ＇）
＞＞ｄｂ．ｓｅｓｓｉｏｎ．ａｄｄ（ｕ）
＞＞ｄｂ．ｓｅｓｓｉｏｎ．ｃｏｍｍｉｔ（）
出现很长的错误提示IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.email [SQL: u'INSERT INTO users (email, username, role_id, password_hash, confirmed, name, location, about_me, member_since, last_seen, avatar_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('john@example.com', 'john', None, 'pbkdf2:sha1:1000$InyGnncC$146f1d5796cff2f7560f3001459d764e3ade587e', 0, None, None, None, '2017-02-16 13:25:46.768745', '2017-02-16 13:25:46.768829', 'd4c74594d841139328695756648b6bd6')]

**Comment by WuYiP** [comment]
我也是出现相同的情况，用户已经登录进去了，但是用户的账号还未确认？这个要怎么整？我尝试运行python mange.py shell对此在ｓｈｅｌｌ中进行注册
＞＞ｕ＝Ｕｓｅｒ（ｅｍａｉｌ＝＇ｊｏｈｎ＠ｅｘａｍｐｌｅ．ｃｏｍ＇，ｕｓｅｒｎａｍｅ＝＇ｊｏｈｎ＇，ｐａｓｓｗｏｒｄ＝＇ｃａｔ＇）
＞＞ｄｂ．ｓｅｓｓｉｏｎ．ａｄｄ（ｕ）
＞＞ｄｂ．ｓｅｓｓｉｏｎ．ｃｏｍｍｉｔ（）
出现很长的错误提示IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.email [SQL: u'INSERT INTO users (email, username, role_id, password_hash, confirmed, name, location, about_me, member_since, last_seen, avatar_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('john@example.com', 'john', None, 'pbkdf2:sha1:1000$InyGnncC$146f1d5796cff2f7560f3001459d764e3ade587e', 0, None, None, None, '2017-02-16 13:25:46.768745', '2017-02-16 13:25:46.768829', 'd4c74594d841139328695756648b6bd6')]

**Comment by huo543810492** [comment]
你可以登陆的？我数据库还有问题，manage db 显示缺少参数啥的，看书看半天还整不明白

**Comment by SulphurFH** [comment]
你这个报错是：UNIQUE constraint failed，应该是数据库里面唯一约束的错误，是不是有主键了但是还有重复数据呢？

2017-02-16 22:13 GMT+08:00 xiaowu <notifications@github.com>:

**Comment by WuYiP** [comment]
@huo543810492 我可以进行登录，但是一直跳出一个界面跟书中95页出现的未确认账户页面一样的情况，不知怎么处理

**Comment by huo543810492** [comment]
@WuYiP 你数据库方面怎么设置的？ 我数据库都不行

**Comment by WuYiP** [comment]
@huo543810492 我数据库没有动呀，就是直接把这个项目git clone到本地，运行python mange.py runserver

**Comment by WuYiP** [comment]
@SulphurFH 我这个是按课本中进行操作的，没有去改动这个项目中的数据库，怎么会出现这情况呀

**Comment by huo543810492** [comment]
@WuYiP 就是注册方面有问题 我不管从shell还是网站注册都会显示
sqlalchemy.exc.StatementError: utcnow() takes no arguments (1 given) (original cause: TypeError: utcnow() takes no arguments (1 given)) 'INSERT INTO users (emai
那你都没法注册 是怎么登陆的？账号密码？

**Comment by WuYiP** [comment]
@huo543810492 我是可以注册登录的，账号跟密码是可以登进去的，但是我用户的账号没有办法通过邮箱确认，所以会出现书中的图8-4未确认账号页面P95页，这种情况

**Comment by huo543810492** [comment]
@WuYiP  你之前不还说在shell中注册会报错么？ 调好了？

**Comment by WuYiP** [comment]
@huo543810492 能加你qq聊吗？感觉我们的问题太low，没有大神回呀

**Comment by huo543810492** [comment]
@WuYiP 正有此意 咱们都有点菜，多一个人还能一起琢磨琢磨 自强一下，我QQ550300893

**Comment by Zhang21** [comment]
作者书上不是说最好清空数据库的吗？你之前注册的它不认

**Comment by WuYiP** [comment]
@Zhang21 我清空数据库了，注册新的账号也是没有办法通过邮箱确认

**Comment by Zhang21** [comment]
@WuYiP     def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(permissions=0xff).first()

代码这里，书上99页。还有 config.py里面FLASKY_ADMIN=xxxx@xxx.com

**Comment by Zhang21** [comment]
记得更新数据库，亲

**Comment by WuYiP** [comment]
@Zhang21 亲，能否加你qq，具体问下你呀

**Comment by WuYiP** [comment]
@Zhang21 send: 'quit\r\n'
reply: '221 Bye\r\n'
reply: retcode (221); Msg: Bye
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xiaowu/share/flask/venv/1/flasky/app/email.py", line 9, in send_async_email
    mail.send(msg)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
    message.send(connection)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 156, in send
    "The message does not specify a sender and a default sender "
AssertionError: The message does not specify a sender and a default sender has not been configured

我现在状况是运行python manage.py runserver，然后在点击确认邮箱那边之后就没有反应，还是未能确认账号登录

**Comment by Zhang21** [comment]
@WuYiP
我觉得你应该是哪儿的代码有错误，我建议不要认证邮箱这部分代码，直接不要这部分代码

**Comment by Zhang21** [comment]
@WuYiP  
"The message does not specify a sender and a default sender "
“邮件未指定发件人和默认发件人”
这就是错误，你自己看错误提示，亲。

**Comment by IvyGongoogle** [comment]
到底该怎么注册管理员账户啊？ how to register admin account?

**Comment by AdamWangDoggie** [comment]
是在User.__init__里进行判断 邮箱是否等于FLASKY_ADMIN的，
也就是说，在config里写好了FLASKY_ADMIN、且Role.insert_roles方法执行完成的情况下，创建新的用户才能进行是否为管理员的判断。
如果在实现判断管理员的功能已经之前注册好的账户，你之后新增这个功能是不会再判断的，因为__init__方法只有在创建实例时执行。
如果你不想清空数据库然后重新注册的话，在shell里连到sqlite改吧。
或者在User类里再写一个方法，对已存在的user进行是否为管理员的判断和修改。

另外建议：在别人的repo里进行讨论，出于对作者的尊重，以及便于作者参与讨论解决你的问题，最好用作者使用的语言。
