### ISSUE TITLE
A bug with markdown.

### ISSUE THREAD

**Issue by x1ah** [miguelgrinberg/flasky#210]
![Imgur](http://i.imgur.com/iIr1mRR.png)
all markdown output in one line? so it can not start a new line? and how tu fix it? THX!

**Comment by miguelgrinberg** [comment]
That is how markdown works, it is not a bug. Documentation regarding line breaks and paragraphs: https://daringfireball.net/projects/markdown/syntax#p

**Comment by x1ah** [comment]
@miguelgrinberg  ah ...get it , THX!
