### ISSUE TITLE
Trying to run the repository....

### ISSUE THREAD

**Issue by leungvb** [miguelgrinberg/flasky#211]
i've downloaded all of the python packages needed to run the script, however i am lost.... what does this code mean and what do i have to do so i can see the fully completed project when i run the server? I run "python manage.py" to have it run on my localhost? if not, which python file do i have to run to see this?

this is the code i get when i run "python manage.py" for the flasky-master: 

http://pastebin.com/i1dsxEY8

**Comment by miguelgrinberg** [comment]
This code is a companion to my book "Flask Web Development" from O'Reilly. Things aren't as simple as "how do I run this script?", really, there is a lot of knowledge that you get by gradually moving from very simple versions of this application (which are hidden in the commit history of this repo) all the way to the final version, which is what you are trying to run. The whole book is what teaches you how to work with this repository.

**Comment by leungvb** [comment]
thanks for the reply

**Comment by leungvb** [comment]
I noticed when i run "git checkout 3b" the code in hello.py does not correspond to the code you refer to on page 31. im referring to the url_for() is not found in the hello.py file. Just wondering if i am doing something wrong because i couldnt find it in 4,a,b,c,d,  either.

Thanks!

**Comment by miguelgrinberg** [comment]
@leungvb I'm probably looking at a different version of the book, because in my PDF, page 31 does not have a hello.py example. And the hello.py version 3b does not have any url_for, here is a direct link to it: https://github.com/miguelgrinberg/flasky/blob/44eab84bb9cf79d126ffc1ad3af3fb215535a8b7/hello.py.
