### ISSUE TITLE
markdown 

### ISSUE THREAD

**Issue by zhao94254** [miguelgrinberg/flasky#212]
If i want insert img,I should add tag in tags?
allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
'h1', 'h2', 'h3', 'p']

And i try use img..but ...
In[52]: allow=['a','img','alt','src','img alt']
In[53]: bb=bleach.linkify(bleach.clean(markdown('![]http://i1.piimg.com/579243/2d3d957a812e9dedt.jpg', output_format='html'),tags=allow))
In[54]: bb
Out[54]: u'&lt;p&gt;<img>&lt;/p&gt;'

**Comment by zhao94254** [comment]
If i want insert img,I should add tag in tags?
allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p']

**Comment by miguelgrinberg** [comment]
Aren't you missing the parenthesis on the image URL?

    ![alt-text](image-url)

**Comment by zhao94254** [comment]
No...
I think problem in here
bleach.clean,  
I don't know what add tag in allowed_tags .
I try add 'img',but can't work..

**Comment by miguelgrinberg** [comment]
You need to debug this to figure it out. Print the markdown html output, then the output of bleach.clean, and then bleach.linkify. That will allow you to see where the img tag is lost.

**Comment by zhao94254** [comment]
>>> mark=markdown('![he](http://i1.piimg.com/579243/2d3d957a812e9dedt.jpg)',output_format='html')
>>> mark
u'<p><img alt="he" src="http://i1.piimg.com/579243/2d3d957a812e9dedt.jpg"></p>'
>>> allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p']
>>> b_c=bleach.clean(mark,tags=allowed_tags,strip=True)
>>> b_c
u'<p></p>'
>>> allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p','img']
>>> b_c=bleach.clean(mark,tags=allowed_tags,strip=True)
>>> b_c
u'<p><img></p>'

I don't know what to tag in allowed_tags...

**Comment by miguelgrinberg** [comment]
If you are going to pass `strip=True`, then you need to whitelist attributes as well. See https://bleach.readthedocs.io/en/latest/clean.html#attribute-whitelist.
