### ISSUE TITLE
no module named sqlalchemy

### ISSUE THREAD

**Issue by pythonkid888** [miguelgrinberg/flasky#214]
when i pip install flask-sqlalchemy and run 

> python manage.py runserver
Traceback: ImportError: No module named sqlalchemy

so i checked  my venv\lib\site-packages. i found that 'sqlalchemy'  was not there
but Command Line  showed 'Successfully installed sqlalchemy-1.1.4'

i only found 'SQLAlchemy-1.1.4.dist-info'

'sqlalchemy' package disappeared

**Comment by miguelgrinberg** [comment]
Did you activate the virtual environment before running `python manage.py runserver`?

**Comment by pythonkid888** [comment]
@miguelgrinberg   
yes,  and just now  i tried to pip install sqlalchemy==1.1.0(not 1.1.4), i successfully solved the problem.
i want to know where is wrong

**Comment by miguelgrinberg** [comment]
@pythonkid888 hard to know. All seems to indicate you did not have sqlalchemy installed, or maybe you had, but then uninstalled.

**Comment by pythonkid888** [comment]
@miguelgrinberg   thank you :)

**Comment by connelevalsam** [comment]
I have this error now

**Comment by gennopp** [comment]
Is it not going to work outside the virtual environment.I am trying it without vagrant.
