### ISSUE TITLE
chap8（User Authentication）

### ISSUE THREAD

**Issue by Zhang21** [miguelgrinberg/flasky#224]
Registering New User
Error:
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: users.email 

In the app/Models,  I have added the email attribute.

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    email = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))
    #在用户模型中加入 密码散列
    #计算密码散列值 的函数通过 password函数 的只写属性实现
    # property 特性； verify 校验

Thanks!

**Comment by Zhang21** [comment]
I upgarde db, but there have no changes in data.sqlite compared to the before。
My migrations folder has less one file compared to yours.

Thans again.

**Comment by Zhang21** [comment]
Why I use command “ python manage.py db migrate -m "initial migration" and " db upgrade"  the app has no problems.

python manage.py db upgrade is invalid？？
I must initiate the database before upgrade, I think my codes are wrong in somewhere.

Your book is amazing！

**Comment by miguelgrinberg** [comment]
The `db init` command creates a brand new migration repository. This is what you would do on a new project that you start. If you are using the code from this repository, you are getting the migration files already, so the init command should not be used (I have used it myself when I created this project). I hope that makes sense. Let me know if you have any other questions.

**Comment by Zhang21** [comment]
How can I updata my database? The command db upgrade does not work. The new property of user models can't commit into database if I don't initialize the migration。

**Comment by miguelgrinberg** [comment]
You need to generate a migration first. Use the `manage.py db migrate` command. That should write a new file to your migrations repository with the database changes. After that, run the `db upgrade` command to actually perform the migration on your database.

**Comment by Zhang21** [comment]
I must use`manage.py  db migrate` before use db upgrade every?  
I use 'manage.py db migrate' command only once, after , when the database has been changes I use db upgrade in my app. Right or Wrong?

**Comment by miguelgrinberg** [comment]
It goes like this:

- When you begin your project, use `db init`, followed by `db migrate`, followed by `db upgrade`.
- When you make changes to your database, use `db migrate`, followed by `db upgrade`.

**Comment by Zhang21** [comment]
I understand.

I forget use the db migrate command before db upgrade.

Thank you.
