### ISSUE TITLE
Flask_script issue

### ISSUE THREAD

**Issue by Insofan** [miguelgrinberg/flasky#225]
I git flasky and installed flask-script but the terminal saied  No module named flask_script

**Comment by miguelgrinberg** [comment]
Show me your complete terminal session, including the entire stack trace of the error, please.

**Comment by Insofan** [comment]
@miguelgrinberg I use PyCharm IDE.From git status 2c, I input python hello.py in terminal it said no moduel, I did install flask-script.
    `HEAD is now at 43d8b2c Chapter 2: Command line options with Flask-Script (2c)
xuhaixiaodeMacBook-Air:flasky haixiao$ python hello.py
Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    from flask_script import Manager
ImportError: No module named flask_script
`

**Comment by miguelgrinberg** [comment]
Are you using a virtual environment? Have you activated it? How did you install flask-script?

**Comment by Insofan** [comment]
Yeah, I using a virtual evn, i installed Flask-Script 0.6.6 version

**Comment by Insofan** [comment]
@miguelgrinberg thx for your reply I fix it myself. Thank you  for your book.
