### ISSUE TITLE
Naming deprecation warning in flask_wtf

### ISSUE THREAD

**Issue by yogin25** [miguelgrinberg/flasky#226]
Flask WTF has changed the name of the flask_wtf.Form to flask_wtf.FlaskForm and the first will be removed in version 1.0 of the extention.
I thaugh that it worth it to metion, so that the reader of your the code of 4b tag can follow allong even if it'll change.

here is the message warning by runserver

hello.py:32: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = NameForm()

**Comment by miguelgrinberg** [comment]
These are now addressed. Thanks!
