### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jkapelus** [miguelgrinberg/flasky#227]
If a user is not yet confirmed and a URL is typed incorrectly the following error occurs:

```
  File "/home/jonathan/Projects/flasky/app/auth/views.py", line 16, in before_request
    and request.endpoint[:5] != 'auth.' \
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The correct result should be a 404 Page Not Found. Any help on solving this would be appreciated!

_PS. I own many of the new flask books and yours is still my first choice. Thanks!_

**Comment by miguelgrinberg** [comment]
What URL did you type to trigger this error? Any URL?

**Comment by jkapelus** [comment]
http://127.0.0.1:5000/moderato

It was a typo when I was testing your /moderator example.

**Comment by jkapelus** [comment]
I just tried to recreate it again using both your flasky code and my code and it's all working fine. I haven't made any changes to my code since posting the Issue so it could be something that cleared itself up after a machine restart. I will keep checking to see if it reappears.

**Comment by jkapelus** [comment]
The URL was http://127.0.0.1:5000/auth/moderator but it happens with any unregistered route after '/auth/'.

It was a typo when testing out the moderator and admin routes. It only happens if the user account is not confirmed yet.

**Comment by Bingmang** [comment]
You should use 
db.session.commit()
after db.session.add(something)

**Comment by miguelgrinberg** [comment]
This is now addressed, Thanks!

**Comment by yarps** [comment]
Hi Miguel,

I got into this issue as well. How was it solved?

**Comment by edgar-humberto** [comment]
Ditto, how was this addressed?
