### ISSUE TITLE
Question about flask_wtf web form handling

### ISSUE THREAD

**Issue by yogin25** [miguelgrinberg/flasky#228]
```
@app.route('/', methods=['GET', 'POST'])
def index():
    form = NameForm()
    if form.validate_on_submit():
      ....
```
When the user sends the POST request to the server with the filled form, the index view handle the request and thats fine for me.

now the index view instanciate a new NameForm class as a form object and i run the validation on that newly crated object! i dont understand what is happening so that the new form object can be checked to see if the user sends a form correctly filled? since, what i understand from the code is that:
at every request handled by the view a new form object is created.

Thanks.

**Comment by miguelgrinberg** [comment]
The `validate_on_submit()` not only validates form data. This method returns `True` if two conditions are met: 1. the request contains form data, and 2) the form data is valid. If either one of these is false, then the method will return `False`.

**Comment by yogin25** [comment]
What i see in the code is that the `validate_on_submit` is colled on the newly created form object.
Is the newly created form object is used as a template for validating data?

**Comment by miguelgrinberg** [comment]
It will probably help you understand this if you go over to the flask-wtf repo and look at the code for the Form class, in particular its constructor and the `validate_on_submit()` implementation.

What you call a `newly created form object` is really an object that initializes itself from data found in the request context. If form data is in the request, the form object will have it. Knowing this, review again the two conditions I mentioned for `validate_on_submit()` to return `True`:

1. there must be form data in the request
2. the data must be valid

So all that call is going to do if the form object is a completely empty form object with no data, is return `False`.

The typical way this method is used is as follows:

```python
if form.validate_on_submit():
    # client sent valid form data
    # process form data here
else:
    # client did not send data, or data sent was invalid
    # display form here
```

**Comment by yogin25** [comment]
According to the explanation you give.
The creation of the form depends on the data sent by the client:
if he send nothing (assuming it's a new request) then the form will be a new object with nothing inside.
if he send a form data in the request (valide or not) the new form object will contain them.
that makes sens
Thank's a lot @miguelgrinberg
