### ISSUE TITLE
Why PostForm can not display?

### ISSUE THREAD

**Issue by mishijun2008** [miguelgrinberg/flasky#229]

**Comment by mishijun2008** [comment]
Hi, I am learning flask now. When I went to chapter 11. I followed everything in the book. Why PostForm can not  be displayed on the home page?? I actually see a long list of random blog on the home page. I try to fixed it. But I failed. Please help me. Thanks.

**Comment by miguelgrinberg** [comment]
Have you corrected the user permissions? My guess is that you are using a user that was created before you got to the part that adds the permissions, so this user does not have permission to write posts, and because of that the post is not displayed.

**Comment by mishijun2008** [comment]
Thank you very much, Miguelgrinberg. I didn't. How to correct the user permission?

**Comment by miguelgrinberg** [comment]
@mishijun2008 Did you see the section in the book that discusses roles and permissions? It's Chapter 9. After you add the roles you have to make sure all users that were created before chapter 9 have a role assigned. You can do that either manually, or by deleting the database and making new users.

**Comment by mishijun2008** [comment]
Hi Miguelgrinberg,

I did review the chapter 9. But I still do not know how to add the roles to the users manually. I also upgraded the db. I appreciate your kind help. Please help me out of this problem. Thanks.

**Comment by miguelgrinberg** [comment]
You can assign roles in a shell session, by working directly with the models.

```
user = User.query.get(<your user id>)
role = Role.query.get(<the role id you want>)
user.role = role
db.session.add(user)
db.session.commit()
```

**Comment by mishijun2008** [comment]
$python manage.py shell
>>> user = User.query.get('Shijun')
>>> role = Role.query.get('Administrator')
>>> user.role = role
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'role'

**Comment by miguelgrinberg** [comment]
The example that I gave you finds users and roles by their numeric id. In your example, both `user` and `role` are `None` because you are not using correct IDs. If you want to locate users and roles by their name you have to build a proper query for that, as explained in the database chapter of the book.

**Comment by mishijun2008** [comment]
Thanks a lot. I think I need study chapters of database and user roles carefully. I am sure I can fix it out.

**Comment by mishijun2008** [comment]
I figured it out. Thanks, Miguelgrinberg. I deleted the database and making a new user. The form is displayed on the home page.
