### ISSUE TITLE
syntactic  struct 

### ISSUE THREAD

**Issue by xcLtw** [miguelgrinberg/flasky#232]
Hello ,everyone.
I encounter a problem with code after.What ' | ' means?when should we use it,and why?
  
The code can be find in 'Your flasky-obj/app/models.py' , about line 25,git branch 9a
```
 roles = {
            'User': (Permission.FOLLOW |
                     Permission.COMMENT |
                     Permission.WRITE_ARTICLES, True),
```

**Comment by miguelgrinberg** [comment]
The `|` is the bitwise OR operator. See https://docs.python.org/2/reference/expressions.html#binary-bitwise-operations.

**Comment by xcLtw** [comment]
See it,thanks!
