### ISSUE TITLE
Why can not use backticks to insert code blocks?

### ISSUE THREAD

**Issue by zhengguanji** [miguelgrinberg/flasky#234]
After I submit the form, the code would become like this:
![screenshot-localhost 5000 2017-01-22 16-24-16](https://cloud.githubusercontent.com/assets/14540039/22181124/ce81a2fc-e0bf-11e6-914c-30c40cbc7309.jpeg)
But if I use indent to insert code block, it was normal.

**Comment by miguelgrinberg** [comment]
This has to do with the way Markdown works. The backtick is for inline code, a code block is done with indentation.

**Comment by zhengguanji** [comment]
But in this https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code, it said
> Blocks of code are either fenced by lines with three back-ticks ```, or are indented with four spaces. 

And the github editor can use back-ticks to insert code block too, what should I do if I want to use backticks to insert code blocks?

**Comment by miguelgrinberg** [comment]
The 3 backticks is an unofficial extension implemented by GitHub, it is not part of the Markdown specification.

**Comment by zhengguanji** [comment]
So that markdown itself does not support this? And if I want to use 3 backticks to insert code blocks, I have to ahieve it by myself?

**Comment by miguelgrinberg** [comment]
There are many Markdown packages for Python. I haven't checked, but it is likely you'll find one that supports the 3-backtick syntax.

**Comment by zhengguanji** [comment]
Ok, I see!

**Comment by zhengguanji** [comment]
I would like to ask you another question, which editor you use on your web https://blog.miguelgrinberg.com/, and how do you manage your blog posts?

**Comment by miguelgrinberg** [comment]
I edit my blog posts in a text editor. I wrote my own blog engine, the admin pages have a simple text editor where I can write Markdown, but often for convenience I write in a regular text editor and then copy/paste it into the blog.

**Comment by zhengguanji** [comment]
Oh, I see! 
And I would like to ask another question, it is that how do you generate the summary for your posts, in the template I use `{{ post.body_html | safe | truncate(300) }}`, it makes the html tags become incomplete, how can I solve this?

**Comment by miguelgrinberg** [comment]
There are many ways to do it. I break the text at paragraph end instead of at a fixed character length.

**Comment by zhengguanji** [comment]
Could you please explain it in more detail?

**Comment by miguelgrinberg** [comment]
In Markdown there is always an empty line between paragraphs. You can find those empty lines and make sure the summary ends in one of those places.

**Comment by zhengguanji** [comment]
Ok, I see! Thanks miguelgrinberg, my english is not very good, some places description is not clear, so sorry! But thanks, your book and your blog is very good, thanks!

**Comment by Beamouser** [comment]
thanks
