### ISSUE TITLE
Chapter 6: Mail folder 

### ISSUE THREAD

**Issue by leungvb** [miguelgrinberg/flasky#235]
Hi,

Was just wondering if the 'mail' directory in 'templates/mail'  needs to be made manually, or if it is automatically generated. I get an error when i run my script but noticed that you had the folders when i checked out the commit. 

Was not sure if it was something created when in the shell, or if it has to be done manually.

thanks again!

**Comment by miguelgrinberg** [comment]
The `mail` folder is simply a location where templates for emails are to be stored. It is not required to organize things that way, I decided to create that folder and store email templates in it to keep them separated from the regular HTML templates.

If you have email templates and want to follow the same application structure that I use, then create the folder, and put your templates there. Like most things with Flask, it is entirely up to you how you organize your project.

**Comment by leungvb** [comment]
Thanks for the reply Miguel. Got it to work.
