### ISSUE TITLE
Fake posts error

### ISSUE THREAD

**Issue by xcLtw** [miguelgrinberg/flasky#236]
Hello,everyone.
I think i find a err about fake posts,the Post object def in models.py does't have an attribute called
'author', there is 'author_id'.

`class Post(db.Model):
    __tablename__ = 'posts'
   ....
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
`

The fake posts function,if run it,AttributeError will be throw
` p = Post(body=forgery_py.lorem_ipsum.sentences(randint(1, 5)),
                     timestamp=forgery_py.date.date(True),
                     author=u)`

Codes on branch 11c

**Comment by miguelgrinberg** [comment]
The `author` field of class `Post` is defined as a backref in the `User` model. See https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L77.

**Comment by xcLtw** [comment]
Ok, thanks.
