### ISSUE TITLE
About url_for?

### ISSUE THREAD

**Issue by zhao94254** [miguelgrinberg/flasky#237]
prev = url_for('api.get_user_posts', page=page-1, _external=True)
BuildError: Could not build url for endpoint 'api.get_user_posts' with values ['page']. Did you forget to specify values ['id']?

**Comment by miguelgrinberg** [comment]
Yes, you are right. I'll fix it. Thanks for letting me know.

**Comment by zhao94254** [comment]
I fix it.....Just add "id=id"
url_for('api.get_user_posts', page=page+1, id=id , _external=True)

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply to the second edition of the book.

**Comment by laggardkernel** [comment]
@miguelgrinberg It seems `_external=True` is dropped from `url_for()` for RESTful API in the 2nd edition. Is there any reason for this move?

**Comment by miguelgrinberg** [comment]
@laggardkernel No specific reason, if your client needs to have full URLs then `_external=True` still makes sense.

**Comment by laggardkernel** [comment]
@miguelgrinberg Thanks for ur response. Sorry to have bothered you with such a petty question.
