### ISSUE TITLE
post view has a little bug

### ISSUE THREAD

**Issue by luog1992** [miguelgrinberg/flasky#241]
Hi Miguel,

I am studying flask using your tutorials. Thanks for your helpful book and codes. 

There I find a little bug in the `post` view in the views.py file in the main blueprint. That is this view doesn't check whether the current user has `Permission.COMMENT`. I noticed that you removed the comment form in the template when the current user has no comment permissions. However I think that the `post` view should have its own validation logic. If an anonymous user send a post request to this view,  an error will be raised.

`AttributeError: 'AnonymousUser' object has no attribute '_sa_instance_state'`

Thanks.

**Comment by miguelgrinberg** [comment]
Okay. But note that an anonymous user sending random POST requests to the application is not going to achieve much. The `AttributeError` obviously prevents anything from happening, but even if that wasn't happening, the CSRF protection in the forms would prevent any data to be posted. So really, when all your forms have a CSRF token, not rendering the form is enough protection to prevent the client to POST directly.

I personally have no trouble with the `AttributeError` above. It will show up in your logs, and it very clearly indicates what happened. In this case this is a "good" error, you want the code to crash and stop the request when the conditions are incorrect. The anonymous user is going to get a 500 error. It would be better that a 401 is returned, and I can improve that, but the code is not vulnerable as it is.

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply to the second edition of the book.
