### ISSUE TITLE
No module pysqlite2

### ISSUE THREAD

**Issue by flj** [miguelgrinberg/flasky#246]
I am running into

from pysqlite2 import dbapi2 as sqlite
ModuleNotFoundError: No module named 'pysqlite2'

from checkout 5a onwards. I am using Python 3.6

How do I get around this. I understand SQLAlchemy is python 3 proof, but not clear why it is using pysqlite2 here.

Cheers

**Comment by miguelgrinberg** [comment]
Did you build your Python 3.6 yourself? I think this error occurs when your Python interpreter was built without native sqlite3 support. If you start a Python 3.6 console and run `import sqlite3`, you should get no errors. If you get an error, you need to install the sqlite dev libraries on your system and rebuild Python.

**Comment by flj** [comment]
indeed, thanks!
