### ISSUE TITLE
Bootstrap doesn't load when offline.

### ISSUE THREAD

**Issue by srseven** [miguelgrinberg/flasky#248]
I am on 3rd chapter of your book and the code works on the server side, bootstrap is rendered in the browser but when I run the app offline it doesn't load, I am using Intellij Idea Ultimate with python plugin for this. Chrome's console shows this: 

![screenshot from 2017-03-03 20 28 20](https://cloud.githubusercontent.com/assets/9510865/23556956/1fc872da-0050-11e7-8054-4120581034d0.png)

why does it need CDN links to load bootstrap when I have `flask-bootstrap` installed in my `virtualenv` and referenced in my `base.html` file as `{% extends "bootstrap/base.html" %}`. IntelliJ IDEA shows `unresolved reference` in `{% extends "bootstrap/base.html" %}`:

![screenshot from 2017-03-03 20 34 09](https://cloud.githubusercontent.com/assets/9510865/23557128/ce3c8a90-0050-11e7-8676-96bde32525e4.png)

**Comment by miguelgrinberg** [comment]
That's expected, because by default Flask-Bootstrap loads the bootstrap files from a CDN. If you set `BOOTSTRAP_SERVE_LOCAL` to `True` in your app, then you can work while offline. See https://pythonhosted.org/Flask-Bootstrap/configuration.html.

**Comment by srseven** [comment]
Thanks!
