### ISSUE TITLE
heroku: No such table Problem

### ISSUE THREAD

**Issue by pythonkid888** [miguelgrinberg/flasky#252]
When i run 

> heroku open

The page shows "internal server error"

Then i run 

> heroku logs

show error"No such table : users"

i think  it is a database problem about migrate. but i don't know how to solve it 

Thank you!

**Comment by miguelgrinberg** [comment]
Did you create the database, and run all the migrations? The book covers the deployment to Heroku step by step, it's all there.

**Comment by pythonkid888** [comment]
i got it.  I omitted a part of codes for convenience in config.py.  
 the code `os.environ.get('DATABASE_URL')`
too stupid!
Thank you
