### ISSUE TITLE
Authenticating Admin on Live Site

### ISSUE THREAD

**Issue by tomnolan95** [miguelgrinberg/flasky#253]
Hey there,
I'm nearly finished your Flask book on Safari and I just had a couple of questions around Authentication. I'm just going to use your own blogging site as my example (as it's a live hosted application).

So I notice on your site you don't have any sort of login/sign up sort of mechanism to allow for users. In the book you go through authenticating users to see who can add/edits posts ect. What I'm wondering is on your own site where you don't have users and it's only you, how do you handle posting/editing your own blog posts? Do you actually do some sort of hidden sign in so you're able to post/edit? If you're creating a new post do you do it locally and then push? Similarly if you want to edit a post do you do that locally and then push it?

I'm just curious as I'm looking to similarly start a blog of my own without users so having visible sign in functionality didn't seem like a good idea and I wasn't sure if making the changes locally to basically a clone of the live application and then pushing them seemed like the best idea either. Apologies if you cover anything like this towards the end of the book as I'm not totally there yet but I said I'd ask while it was fresh on my mind.

**Comment by miguelgrinberg** [comment]
The login page for my site is not public, since I'm the only one that uses it. Other than that, login works in the same way as in the book or my other tutorials.

**Comment by tomnolan95** [comment]
How do you configure something like that? Just have a hidden endpoint or something along those lines?

**Comment by miguelgrinberg** [comment]
There is no concept of hidden endpoints, it's just a regular endpoint, but it's not linked anywhere in the app. I type it in the address bar manually.
