### ISSUE TITLE
Chapter 8 in Page 94 one error

### ISSUE THREAD

**Issue by imesong** [miguelgrinberg/flasky#254]
There is one error in Chapter8 ,Page94. 8-22 the Sample code about ''app/auth/views.py''

```python
@auth.before_app_request
def before_request():
    if current_user.is_authenticated() \
    and not current_user.confirmed \
    and request.endpoint[:5] != 'auth.': and request.endpoint != 'static':
    return redirect(url_for('auth.unconfirmed'))

```
which should be 

```python
@auth.before_app_request
def before_request():
    if current_user.is_authenticated \
    and not current_user.confirmed \
    and request.endpoint[:5] != 'auth.'
    and request.endpoint != 'static':
    return redirect(url_for('auth.unconfirmed'))

```

**Comment by miguelgrinberg** [comment]
Yes. This is noted in the [errata](https://flaskbook.com). The Flask-Login project changed a bunch of methods to properties in a release that came after the book was published. I have updated the code in this repository for this update, and have also plan to have this corrected in new prints of the book.
