### ISSUE TITLE
Problem: relation xx already exists

### ISSUE THREAD

**Issue by pythonkid888** [miguelgrinberg/flasky#255]
Today i add a todolist  function to my blog.
when i git push to  my master and run
 `heroku run python manage.py deploy`

i got this error
>sqlalchemy.exc.Programming Error:  relation 'roles'  already exists

How can i solve it? and why?

Thanks!

**Comment by miguelgrinberg** [comment]
I guess this is a problem in your migration history. Your database state does not match the migrations, so this `roles` relation is being added, but in your database it already exists. You will need to figure out where the disconnect happened and make a correction, either on the database, or on the migration scripts.

**Comment by pythonkid888** [comment]
@miguelgrinberg  You mean that my database already has a `role` relation,and my up-to-date migration scripts makes me add it again?

**Comment by miguelgrinberg** [comment]
That's what it looks like, yes.

**Comment by pythonkid888** [comment]
@miguelgrinberg  i got it . thanks
