### ISSUE TITLE
Hosting on Gandi Simple Hosting

### ISSUE THREAD

**Issue by rolodub** [miguelgrinberg/flasky#256]
Hello,
I'm trying to deploy my app made with your book support (very good book) on Gandi Simple Hosting
Gandi simple hosting needs a wsgi.py which point the app.
https://wiki.gandi.net/en/simple/instance/python
I don't understand how I will use the manage.py in this context.
Thanks!

**Comment by miguelgrinberg** [comment]
You can create a simple wsgi.py file as follows:

    from app import create_app
    application = create_app(os.getenv('FLASK_CONFIG') or 'default')

But unfortunately, this platform does not seem to allow to run custom tasks, such as the `manage.py deploy` task that creates or upgrades the database. You need to ask them how that can be achieved.

**Comment by rolodub** [comment]
Thank you, it works!
For custom tasks, there is an ssh access which permits me to create and upgrade a sqlite database via manage.py.
The here is also a postgresgl database on the virtual host... I'll come back to close my issue when I have succeeded in linking my app to this database.
Thanks

**Comment by rolodub** [comment]
Finally, I think I'm going to deploy it on a vps which seems more configurable than this simple hosting...
