### ISSUE TITLE
Combining two forms into one

### ISSUE THREAD

**Issue by IronFist16** [miguelgrinberg/flasky#257]
It is just a question actually, concerning `EditProfileForm`,
Can't we make one form method for both user and administrator and using `if current_user.is_administrator` we add related fields?,

**Comment by miguelgrinberg** [comment]
Sure, you can combine both forms into one. That will make your code more complex though, you'll have to shower it with if statements to handle the admin parts conditionally.

**Comment by IronFist16** [comment]
Correct, appreciate quick response. :+1:
