### ISSUE TITLE
the keywords 'timestamp' is not arguments in POST？

### ISSUE THREAD

**Issue by labike** [miguelgrinberg/flasky#258]
import datetime
u = models.User.query.get(1)
p = models.Post(body='my first post', timestamp=datetime.datetime.utcnow(), author=u)

in cmd: 
    the result: 'timestamp is an invalid keyword argument for Post'

**Comment by miguelgrinberg** [comment]
Do you have [this line](https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L351) in your model definition?

**Comment by labike** [comment]
thanks! please screen my 'models.py' code:
`from app import db
class User(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    nickname = db.Column(db.String(64),index = True, unique = True)
    email = db.Column(db.String(120), index = True, unique = True)
    posts = db.relationship('Post', backref = 'author', lazy = 'dynamic')

    def __repr__(self):
        return '<User %r>' % (self.nickname)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    body = db.Column(db.String(140))
  
 **timestamp = db.Column(db.DateTime)**

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post %r>' % (self.body)`

the running error:

![Uploading 2017-04-04_154349.png…]()
![Uploading 2017-04-05_103809.png…]()
![Uploading 2017-04-05_104024.png…]()

my project code:https://github.com/labike/flask-timetamp-question

help me, thanks you!  foreign friend
