### ISSUE TITLE
db.Model constructor and password method

### ISSUE THREAD

**Issue by Xiaohong-Deng** [miguelgrinberg/flasky#259]
I noticed in Chapter 8 after the following added to class User
```
@property
def password(self):
    raise AttributeError('password is not a readable attribute')

@password.setter
def password(self, password):
    self.password_hash = generate_password_hash(password)
```
the following in the shell can be done
`>>> u = User(username = 'susan', password = 'cat')`
How the constructor recognize keyword password? By doing so it invokes the setter password(). Or property decorator alone makes this happen? Thanks in advance. I'm stuck.

**Comment by miguelgrinberg** [comment]
Yes, it works automatically, because `password` is defined as a property with a setter method.

**Comment by Xiaohong-Deng** [comment]
But I failed to reproduce this behavior by making a toy class of my own. So I wonder if this also has something to do with an appropriate __init__(). To be specific
`c = Toy(foo='cat')`
doesn't work but
```
c = Toy()
c.foo = 'cat'
```
works as expected.

**Comment by miguelgrinberg** [comment]
Is `Toy` a subclass of `db.Model`? The Model class from SQLAlchemy is the one that provides the logic to initialize the object from constructor arguments.

**Comment by Xiaohong-Deng** [comment]
No and thanks for pointing that out.

**Comment by simanacci** [comment]
Whats the difference in having say `def custom_method()` in a `.py` file and importing them versus in a `db.Model` i.e. `User.custom_method()`? For example `generate_confirmation_token` or a similar custom method.

**Comment by miguelgrinberg** [comment]
@simanacci then it wouldn't be a method, it would be a function, right? The difference is that the way I do it uses object-oriented programming, your solution is based on functions. You can make things work either way, if you prefer functions, then you should use functions.
