### ISSUE TITLE
Post Deployment to Heroku

### ISSUE THREAD

**Issue by trno1an** [miguelgrinberg/flasky#264]
Hey Miguel,

I'm just wondering after deploying to Heroku, how do I run the app locally? Can I only run it using foreman? Every time I attempt to use: `./manage.py runserver` it now attempts to use the HerokuConfig, I assume it's because I'm on the branch that is sync'd with Heroku. It might be a silly question but any help is appreciated.

Tom.

**Comment by trno1an** [comment]
I've tried getting this to run locally using `foreman local` also but even when I try to do that it's trying to use SSL. I have SSL_DISABLE=1 in my .env file but for some reason it seems to ignore it. I'm really not sure what's going on. The deployed version is working absolutely fine and if I comment out the code for activating SSL then it works fine locally also.

**Comment by miguelgrinberg** [comment]
What's the value of your `FLASK_CONFIG` environment variable? If you set that to `dev` or `prod` you should be able to run the normal non-heroku app.

**Comment by trno1an** [comment]
I didn't have that set locally but I've since set it.

![image](https://cloud.githubusercontent.com/assets/11179798/25504002/25e77160-2b94-11e7-9baf-b5b985a728f4.png)

^ That is my current .env file but when I go to run it with ./manage.py it now gives out:
`File "./manage.py", line 14, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/tom.nolan/python_/homeblog/app/__init__.py", line 23, in create_app
    app.config.from_object(config[config_name])
KeyError: '“dev”'`

Appreciate the help!

**Comment by miguelgrinberg** [comment]
Sorry, made a mistake. The value should be `development`. It should match one of the config names [here](https://github.com/miguelgrinberg/flasky/blob/master/config.py#L103-L107).

**Comment by trno1an** [comment]
Okay so that was my own fault I was putting quotes around the 'development' so it was error'ing out. Thanks for your help man!

**Comment by miguelgrinberg** [comment]
@trno1an quotes are fine, bash takes those as string delimiters. But on closer inspection, it looks like you've got the "fancy" quotes, not the regular ASCII quotes in there. So those were interpreted as being part of the string assigned to the environment variable. This happened to me more times that I'm willing to admit. :)

**Comment by trno1an** [comment]
I was going insane! I just kept thinking to myself this was all working last night when I finished up, why aren't you working locally now haha, live and learn!
