### ISSUE TITLE
TypeError: login_user() missing 1 required positional argument: 'user'

### ISSUE THREAD

**Issue by Sonnenuntergang** [miguelgrinberg/flasky#266]
If the logout_user() function is recalled with no arguments, it may occurs the following error: 
TypeError: login_user() missing 1 required positional argument: 'user'
Hence, recalling logout_user() function with current_user arguments may works: 

`from flask_login import current_user
@auth.route('/logout')
@login_required
def logout():
    login_user(current_user)
    flash('You have logged out.')
    return redirect(url_for('main.index'))`

**Comment by miguelgrinberg** [comment]
Not sure I understand what the problem is. The `logout_user()` function does not take any arguments: https://flask-login.readthedocs.io/en/latest/#flask_login.logout_user.

**Comment by Sonnenuntergang** [comment]
I am sorry. That is my fault. In section 8.4.5 of your book "Flask Web Development", there is a function below: 

`@auth.route('/logout')`
`@login_required`
`def logout():`
    `logout_user()`
    `flash('You have logged out.')`
    `return redirect(url_for('main.index'))`

I typed login_ueser() function but did not realize until now. 
I fixed the error. 
I hope you can close this naive issue.
