### ISSUE TITLE
Permission class used in base.html

### ISSUE THREAD

**Issue by vicigel** [miguelgrinberg/flasky#269]
I wondered why Permission can be directly used in templates/base.html
just the following codes

<pre>
&lt;ul class="nav navbar-nav navbar-right">
    {% if current_user.is_authenticated %}
         {% if current_user.can(Permission.MODERATE_COMMENTS) %}
</pre>

And in my environment,it doesn't work
thank you!

**Comment by miguelgrinberg** [comment]
You need to define a context processor function with the symbols that you want available in the templates. Here is where this is done: https://github.com/miguelgrinberg/flasky/blob/9bcab0e17504629b4bfe7ca557f1fc44d920f767/app/main/__init__.py#L9-L11

**Comment by vicigel** [comment]
Thank you very much,I got it!
