### ISSUE TITLE
environment mess up

### ISSUE THREAD

**Issue by dzahedia** [miguelgrinberg/flasky#271]
Hi Miguel,

I recently followed your blog on flask server, after following the first blog, my python is messed up, I cannot use python3 anymore; whichever python I call, python gets invoked. Do you by any chance know what has happened? How can I rollback? 

Thanks
David

**Comment by miguelgrinberg** [comment]
Did you follow my advice of using a virtual environment? That is the proper way to set up a private Python installation for a project. If you were using a virtual environment, then your global Python should not be affected.

If you made changes to the system-wide Python interpreter and something does not work, then reinstalling Python should reset anything that is broken.
