### ISSUE TITLE
test_selenium problem

### ISSUE THREAD

**Issue by fyue** [miguelgrinberg/flasky#272]
Hi, miguel grinberg!
    I encountered a problem when learned the chaper 15. while I checkouted 15d and typed in command "python3 manage.py test", I received a test module output message "test_admin_home_page (test_selenium.SeleniumTestCase) ... skipped 'Web browser not available'''.  Is there something wrong? 
I appreciate it if you give me reply.

**Comment by miguelgrinberg** [comment]
Do you have Firefox installed? If not, you may need to modify the selenium tests to use your favorite browser. See https://github.com/miguelgrinberg/flasky/blob/master/tests/test_selenium.py#L17.

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply to the second edition of the book.
