### ISSUE TITLE
Is the 'seed()’ in the app/models.py  necessary ？？

### ISSUE THREAD

**Issue by sandylili** [miguelgrinberg/flasky#273]
In the chapter 11c ,Model User and Post  have  function 'generate_fake(count=100)',In order to generate random data，import random.seed and forgery_py ,function code is:

        from sqlalchemy.exc  import  IntegrityError
        from random import seed
        import forgery_py
        
        seed()      #why?  
        for i in range(count):
            u = User(email=forgery_py.internet.email_address(),
                     username=forgery_py.internet.user_name(True),
                     password=forgery_py.lorem_ipsum.word(),
                     confirmed=True,
                     name=forgery_py.name.full_name(),
                     location=forgery_py.address.city(),
                     about_me=forgery_py.lorem_ipsum.sentence(),
                     member_since=forgery_py.date.date(True))
            db.session.add(u)
            try:
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

random.seed(）  Initialize internal state of the random number generator

Why should first call seed() function ?what's the effect？Is it necessary?  
Try to delete ‘seed()'，Random data can  alse  be generated normally

Thankes
@miguelgrinberg

**Comment by miguelgrinberg** [comment]
The `seed()` function makes sure that the sequence of random numbers that forgery_py uses to generate random data is different every time. This is normally not necessary, so it is okay to not include, but on some systems, not including it may cause the sequence of random elements generated by forgery_py be the same.

**Comment by sandylili** [comment]
Thanke you very muck!! I have understood it！！
I have read this book more than ten times, Everytimes  can find that did not understand the place，Through google,stackoverflow,github and Source code, most question  can understand.
This question also had searched for a long time,Thanks to your answer that Solved this doubts.
Thankes @miguelgrinberg
