### ISSUE TITLE
Role.insert_roles() raise TypeError: 'Role' object is not subscriptable

### ISSUE THREAD

**Issue by hyolee750** [miguelgrinberg/flasky#276]
When I was learning Chapter 9,and typing `Role.insert_roles()` method in a shell session.
The Interpreter raise this exception,but I didn't know how to solve this problem.

please help me!
Thanks!

**Comment by miguelgrinberg** [comment]
What's the stack trace of the error?

**Comment by hyolee750** [comment]
```python
$ python3 manage.py shell
>>> Role.insert_roles()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/hyolee/PyCharm2017/flasky/app/models.py", line 42, in insert_roles
    role.permissions = role[r][0]
TypeError: 'Role' object is not subscriptable
```

**Comment by miguelgrinberg** [comment]
You have a typo. Instead of:

    role.permissions = role[r][0]

You should use:

    role.permissions = roles[r][0]

**Comment by hyolee750** [comment]
I'm sorry.
I copy that by mistake.
at first,I find this typo,and I correct it like you said,but it's still the same error.
I try to print what `r` is 
```python
        for r in roles:
            print(r)
        #     role = Role.query.filter_by(name=r).first()
        #     if role is None:
        #         role = Role(name=r)
        #     role.permissions = roles[r][0]
        #     role.default = roles[r][1]
        #     db.session.add(role)
        # db.session.commit()
```
and the error:
```python
>>> Role.insert_roles()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/hyolee/PyCharm2017/flasky/app/models.py", line 42, in insert_roles
    #         role = Role(name=r)
TypeError: 'Role' object is not subscriptable
```

**Comment by miguelgrinberg** [comment]
That is a weird error. Are you doing this from inside PyCharm? I bet this is a PyCharm issue, and if you quit and restart it you will not see this error.

**Comment by hyolee750** [comment]
I keep the PyCharm opening when I try it in a shell outside PyCharm,and I close Pycharm,reopen a shell and try it again.
It works miraculously!
That is a weird error indeed :)
But thank you anyway

**Comment by miguelgrinberg** [comment]
In case you want to understand what's going on, the PyCharm shell does not seem to be receiving updates for code changes that you type in the editors. But it does use the editor lines of code when printing stack traces. That is why the error was the same (the compiled Python code did not change) but the source code lines in the stack trace showed the changed code. Sounds like a PyCharm bug to me.
