### ISSUE TITLE
A potential problem in api auth code

### ISSUE THREAD

**Issue by psychoshawny** [miguelgrinberg/flasky#28]
Hello Miguel.

In https://github.com/miguelgrinberg/flasky/blob/master/app/api_1_0/authentication.py, in the `verify_password(email_or_token, password)` function, `g.current_user` is getting set before getting the verification of the password provided : 

    if not user:
        return False
    g.current_user = user
    g.token_used = False
    return user.verify_password(password)

It may be better if it was this way : 

    if not user or not user.verify_password(password):
        return False
    g.current_user = user
    g.token_used = False
    return True

What do you think?

Thank you for your amazing book. Learning a lot!

**Comment by miguelgrinberg** [comment]
@psychoshawny The end result is going to be the same, when the `verify_password` handler returns `False` control will be returned to the client with an authentication error (so no actual application code will be allowed to run).

I think your suggestion is more a safety measure (i.e. less likely to fool the application into thinking it is logged in if the user isn't stored), and from that point of view I agree with you. The only advantage I can think of for doing it the way I did it, is that if the user is stored in `g.current_user` then the application can do something with it in an `after_request` handler. Maybe keeping track of failed login attempts, or blocking the user after some number of failures. Not a super strong argument, I know.

**Comment by psychoshawny** [comment]
Okay. Thank you!
