### ISSUE TITLE
Questions about the file 'error_page.html'  of committing in  Chapter 14a

### ISSUE THREAD

**Issue by sandylili** [miguelgrinberg/flasky#280]
This file 'error_page.html' should be used for general error pages，but the other file of this repository did not seem to quote it？ if yes，how do we  use it ?

Thank you @miguelgrinberg

**Comment by miguelgrinberg** [comment]
@sandylili Hmm. You are correct, looks like I never hooked up `error_page.html`. I should have added a catch-all error handler that uses this template. This will be fixed in the new edition of the book. Thanks!

**Comment by sandylili** [comment]
Thankes for your answer! @miguelgrinberg
If we would use this file ,please help me this code : 
```
app/main/errors.py
...
class ValidationError(ValueError):
    pass  #bad request 400
class  Unauthorized(ValueError):
   pass #Unauthorized 401

def bad_request(message):
    name='error: bad request'
    description = message
    code = 400
    return render_template('error_page.html',name=name,code=code,description=description), 400

@main.app_errorhandler(ValidationError)
def validation_error(e):
    return bad_request(e.args[0])

```
then 
```
app/main/views.py
...
from .errors import ValidationError， bad_request
@main.route('/errortest')
def errortest():
  raise ValidationError('error example ')  # or using  bad_request('error example ')
```
would we use the file ' error_page.html ' like this code ? 
Thanke you !
