### ISSUE TITLE
4 pagination in one page

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/flasky#283]
I cannot understand how can I use your macro for multiple pagination objects on one page. Can you help me to get it done?

**Comment by miguelgrinberg** [comment]
I assume you refer to the `pagination_widget` macro for Jinja2 templates? The macro takes the pagination object as an argument, if your template receives four pagination objects for different queries, you can use this same macro to generate the pagination links to each one, just by passing the correct pagination object in each instance.

**Comment by deveshaggrawal19** [comment]
I did the same, here is the code:
{% macro pagination_widget(pagination, endpoint) %}
<div class='waves-pagination'>
<ul class='page-numbers'>
<li{% if not pagination.has_prev %} class="disabled"{% endif %}><a class="next page-numbers" href="{% if pagination.has_prev %}{{ url_for(endpoint,
page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">previous</a></li>

{% for p in pagination.iter_pages() %}
{% if p %}
{% if p == pagination.page %}
<li><span class='page-numbers current'>{{ p }}</span></li>
{% else %}
<li><a class='page-numbers' href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a></li>
{% endif %}
{% else %}
<li class="disabled"><a href="#">&hellip;</a></li>
{% endif %}
{% endfor %}
<li{% if not pagination.has_next %} class="disabled"{% endif %}>
<li><a class="next page-numbers" href="{% if pagination.has_next %}{{ url_for(endpoint,
page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">next</a></li>
</li>
</ul>
</div>
{% endmacro %}

in template:
{{ macros.pagination_widget(ref_pag, 'auth.account') }}
{{ macros.pagination_widget(log_pag, 'auth.account') }}

in veiws:
page1 = request.args.get('page1', 1)
page2 = request.args.get('page2', 1)
log_pag = LoginLog.query.filter_by(user_id=current_user.id).paginate(page1, per_page=5,error_out=False)
ref_pag = Referral.query.filter_by(refer_id=current_user.refer_id).paginate(page2, per_page=5,error_out=False)

But when I see the links on pagination widget it is showing according to page and not page1, page2

**Comment by miguelgrinberg** [comment]
Oh, right, the widget as it is will not work for multiple paginations, only because it does not generate the correct page links for all your lists. You will need to add an argument to the macro that specifies which of the paginated lists you are rendering (page1, page2, etc.), and then use that to set the page in the links, instead of the hardcoded `page=something`. You will also have to pass the page numbers for all the other lists as kwargs.

For example, if you are using two lists, the usage will be more or less as follows:

```
{{ macros.pagination_widget(ref_pag, 'page1', 'auth.account', page2=page2) }}
{{ macros.pagination_widget(log_pag, 'page2', 'auth.account', page1=page1) }}
```

**Comment by deveshaggrawal19** [comment]
what will be the changes in pagination widget, since there are only arguments in the previous widget, but now there are three. It is giving error

**Comment by deveshaggrawal19** [comment]
Please can you be more descriptive, I am not able to implement it.

**Comment by miguelgrinberg** [comment]
Have you considered using separate iframes for your four lists? That would make each list be on its own page, should be easier and more efficient to manage the four lists combined in a single page that way.

**Comment by deveshaggrawal19** [comment]
That would make the problem even worse. I have at least 15 pages where there are more than one pagination objects. If I create iframe for each, it will make the project extend quite a bit

**Comment by miguelgrinberg** [comment]
I don't see what it would extend. Each paginated listing will be on its own page, so it will be much simpler to create. All you need to do is create the main page with the iframes that invoke each listing in the proper place in the page.

Also consider that if you implement all the listings in a single template, paginating one listing will require all the lists to be regenerated, not just the one you are reviewing. With iframes, each list is in its own page, so you will be saving bandwidth and server effort.

**Comment by deveshaggrawal19** [comment]
can you help me to work your macro widget with multiple pagination objects. I really need that, actually, iframes are not working with the mobile view of the page perfectly. I am not the front end guy. It would really help me if the widget could just work. The only problem I am having is getting different page i.e page1, page2, page3, in {{url_for(endpoint, page = p,  **kwargs)}}

**Comment by miguelgrinberg** [comment]
I explained how the macro needs to be modified above, but it isn't a trivial change unfortunately. The macro needs to know the pages of all the lists, not just the one it is generating the pagination links for, so the argument that you pass to the macro need to include information about all the lists, even though the macro handles a single list per invocation.

Another alternative that you can look into is to save the current page for each list in the user session, and that way the URLs do not need to have the current page for every list. But still, this is a big change that will require some non-trivial work.

**Comment by deveshaggrawal19** [comment]
well, I created four different macros with a different page in url, so that solves the issue, it is not scalable, but a working solution.
