### ISSUE TITLE
database is locked when logining in again in reopen browser after closing browser

### ISSUE THREAD

**Issue by IvyGongoogle** [miguelgrinberg/flasky#286]
hello, I add the user registration of your code to my project. After I register and confirm my email, I can directly visit profile page.  So it is normal.  But after I close my browser and reopen browser, I again log in but can not success and get the error in shell:

`OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: u'UPDATE users SET last_seen=? WHERE users.id = ?'] [parameters: ('2017-07-24 09:21:19.625342', 1)]
`
My code about register and confirm is as follows:

for `/app/auth/views.py`:
```
@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        send_email(user.email, u'确认您的账户',
                   'accounts/auth/email/confirm', user=user, token=token)
        flash(u'确认邮件已经发送到您的邮箱。')
        return redirect(url_for('auth.login'))
    return render_template('accounts/auth/register.html', form=form)
@auth.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('digits.zhuge_home_views.zhugeHomeOne'))
    if current_user.confirm(token):
        flash(u'您已经确认您的帐户。谢谢!')
    else:
        flash(u'确认链接无效或已过期。')
    return redirect(url_for('digits.zhuge_home_views.zhugeHomeOne'))
```

for `/app/models.py`:

```
def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True
```

Above code is mainly as yours.
So where is the problem ? can you give some advises? 
looking forward to your reply.

**Comment by miguelgrinberg** [comment]
The error says that your sqlite database is locked. Could that be related to something else you are doing with your database, outside of the server process?

**Comment by IvyGongoogle** [comment]
@miguelgrinberg I have solved it. I add `db.session.commit()` into function ping. But I am confused why I need add `db.session.commit()` in some function like `ping` of `/app/models.py` or `confirm` of `/app/models.py`
 ```
   def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()
```
but in your code, they will commit to database without adding  `db.session.commit()`

**Comment by miguelgrinberg** [comment]
I'm using the "commit on teardown" option from Flask-SQLAlchemy, which basically triggers a commit after a request ends.

I don't recommend using that option, though, as it has been deprecated since the book came out due to not always working well. For the second edition of the book I'm going to include commits in every view function, as that is safer.
