### ISSUE TITLE
Does the flask-sqlalchemmy session is scoped to every request

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/flasky#291]
Does every request in flask creates a new session for DB or creates only a transaction to combine the changes. Can you please elaborate.

**Comment by miguelgrinberg** [comment]
Each request gets its own connection to the database. During the course of the request there may be one or more transactions issued and committed. Each time you call `db.session.commit()` the transaction is committed.

**Comment by deveshaggrawal19** [comment]
Thank you for clearing this up

*With Regards,*
*Devesh Aggrawal*
