### ISSUE TITLE
Deleting Rows from an Association Table

### ISSUE THREAD

**Issue by trno1an** [miguelgrinberg/flasky#292]
Hey Miguel,

I decided to take it a little further and add categories to blog posts. It's all working fine but for some reason when I try to delete posts using the Postgres command line I'm getting:

`ERROR:  update or delete on table "posts" violates foreign key constraint "has_category_post_id_fkey" on table "has_category"
DETAIL:  Key (id)=(2) is still referenced from table "has_category".`

In my models.py I have:

``` python
has_category = db.Table('has_category',
            db.Column('category_id', db.Integer, db.ForeignKey('categories.id')),
            db.Column('post_id', db.Integer, db.ForeignKey('posts.id')))

class Category(db.Model):
	__tablename__ = 'categories'
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(64), unique=True, index=True)

class Post(db.Model):
	__tablename__ = 'posts'
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(64), unique=True, index=True)
	body = db.Column(db.Text)
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
	categories = db.relationship('Category', 
			secondary=has_category,
			backref=db.backref('posts',lazy='dynamic'),
			lazy='dynamic')
```

I would have thought that when I delete a Post here that the associated row(s) for whatever categories it has in `has_category` would be deleted? I've tried adding in cascades also but I can't figure out what it is that I'm doing wrong exactly.

Any help would be appreciated!

**Comment by miguelgrinberg** [comment]
Are you deleting posts via SQLAlchemy or directly through Postgres queries? I think you should be able to delete from SQLAlchemy, but from the Postgres side there is no cascading configured, so it is expected that this won't work.

**Comment by trno1an** [comment]
So I was trying to delete the rows through Postgres itself. I tried adding `cascade="all, delete-orphan"` to Post models relationship to categories but that also didn't seem to work, it gave me the same error! 

I can just put in a route to delete the Post entries and get rid of them that way.

Thank you!

**Comment by miguelgrinberg** [comment]
The `cascade=`all, delete-orphan'` option is not a Postgres cascade, it is a SQLAlchemy cascade. To do this in Postgres, you need to add `ON DELETE CASCADE` to the foreign key. I believe you can do that from the model definition as `ondelete='cascade'` but check the docs to get the exact syntax.

**Comment by trno1an** [comment]
Absolutely correct. Adding `ondelete='cascade'` to the foreign key in the `has_category` table lets me delete them through the postgres cmd 😄 

Thanks.
