### ISSUE TITLE
Refresh the register page

### ISSUE THREAD

**Issue by alex1007** [miguelgrinberg/flasky#293]
If the form doesn't pass the validation, error messages would be added into the form. However, if I refresh the page, it would cause a duplicate form submission. Using redirect can solve the problem, but error messages will be lost. Is there a better way to solve the problem?

**Comment by miguelgrinberg** [comment]
The only case where this is a problem is if the form is submitted with errors. In this case, a duplicate submission as a result of a refresh is going to fail validation once again, so there is no risk of any duplicate data appearing in the server. In all cases where the form data is valid, the server should respond with a redirect, and I believe this project does.

**Comment by alex1007** [comment]
You are right. It seems like this problem can only be solved by using JS to validate the form.

**Comment by miguelgrinberg** [comment]
You can also write the form errors to the user session and pick them up after the redirect. This is the technique that the flashed messages use to work after redirects. I think it isn't worth the effort though.
