### ISSUE TITLE
I really need help!              AssertionError: The message does not specify a sender and a default sender has not been configured

### ISSUE THREAD

**Issue by WJFQ** [miguelgrinberg/flasky#294]
i was confused with this problem for  1 weeks...

After i finished the User authentication ( the book :<FLASK DEVELOPING> page 95)，and I want to register an account. but i can not receive the confirm email.
Here is the problem:

**Traceback (most recent call last):
  File "i:\apython\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "i:\apython\Lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\WJF\flasky10.1\app\email.py", line 9, in send_async_email
    mail.send(msg)
  File "C:\Users\WJF\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\WJF\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\WJF\venv\lib\site-packages\flask_mail.py", line 178, in send
    "The message does not specify a sender and a default sender "
AssertionError: The message does not specify a sender and a default sender has not been configured
**

I did set the username and password like `MAIL_USERNAME = os.environ.get('MAIL_USERNAME')` in venv
I want to solve it. So i download the source code from 
miguelgrinberg/flasky----Chapter 8: Email address changes (8h)(https://github.com/miguelgrinberg/flasky/commit/786d96ba617c4b36403444e9db05c52b2b1226b0)

After  i changed the(163.com used in china)
    MAIL_SERVER = 'smtp.163.com'
    MAIL_PORT = 25
    MAIL_USE_TLS = True
or
    MAIL_SERVER = 'smtp.163.com'
    MAIL_PORT = 465
    MAIL_USE_SSL = True
but it still wrong 
I have no idea.  
can anyone help me ?
SAD~~

**Comment by WJFQ** [comment]
My English is poor，sorry  !

**Comment by WJFQ** [comment]
i dont know .
 here is the email.py:

`def send_email(to, subject, template, **kwargs):
    app = current_app._get_current_object()
    msg = Message(app.config['FLASKY_MAIL_SUBJECT_PREFIX'] +''+ subject,
                  sender=app.config['MAIL_SENDER'], recipients=[to])
    msg.body = render_template(template + '.txt', **kwargs)
    msg.html = render_template(template + '.html', **kwargs)
    thr = Thread(target=send_async_email, args=[app, msg])
    thr.start()
    return thr
`
is that wrong ?

**Comment by miguelgrinberg** [comment]
What's the value of `app.config['MAIL_SENDER']`. The error is pretty clear, you have to figure out why the sender isn't set.

**Comment by WJFQ** [comment]
thanks a lot !  it actually done after i find the user, password and sender! 
i have received the confirm email !
thank u !~~
