### ISSUE TITLE
[Follower function] List of followers, followed_by still has self user

### ISSUE THREAD

**Issue by tuannv562** [miguelgrinberg/flasky#295]
In chapter 12, show followed posts on the home page, although the number of followers and followed_by was decreased by 1 (because user self-follows), but in list of follower and followed_by users still has self-user. How to remove self-user in that lists?
Sorry for bad English

**Comment by miguelgrinberg** [comment]
The template that renders the list of followers and followed users filter the self user. See https://github.com/miguelgrinberg/flasky/blob/master/app/templates/followers.html#L13.

**Comment by tuannv562** [comment]
I got it, thanks
