### ISSUE TITLE
HTTPie test error

### ISSUE THREAD

**Issue by weqopy** [miguelgrinberg/flasky#296]
Hi,I'm study 14.2.8 now, there seems like a network error when I try a test. I tried google it but no good answer.

I use the anonymous command `http --json --auth : GET http://127.0.0.1:8888/api/v1.0/posts/` and it returns:
`http: error: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1.0/posts/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10991c9b0>: Failed to establish a new connection: [Errno 61] Connection refused',)) while doing GET request to URL: http://127.0.0.1:5000/api/v1.0/posts/`

Even when I clone your code and try it, there is the error. So I think it's because the network is wrong somewhere and I can't find what exactly it is.

Thanks for your help.

**Comment by miguelgrinberg** [comment]
Are you using the correct port number? I see two ports mentioned in your output, 5000 and 8888. My guess is that you have your server listening on a different port than what you are using in the HTTPie command line.

**Comment by weqopy** [comment]
sorry, that's because I tried the two ports 5000 and 8888 in Terminal and copied different command and  return to paste in this issue.

I also tried curl right now, it returns the same error.
`> curl -v http://127.0.0.1:5000/api/v1.0/posts/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 5000 failed: Connection refused
* Failed to connect to 127.0.0.1 port 5000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 5000: Connection refused`

**Comment by miguelgrinberg** [comment]
Are you running the server? The error suggests there is no server running on port 5000.

**Comment by weqopy** [comment]
No, I'm not running the server. Should I?

The book says use `pip install httpie` to install HTTPie, then use an email and password to run the GET request. And the commands run on the terminal directly.
<img width="470" alt="2017-08-26 17 41 20" src="https://user-images.githubusercontent.com/10494196/29740292-b9430046-8a85-11e7-8985-db157bcc63db.png">

I choose the anonymous way `http --json --auth : GET http://127.0.0.1:5000/api/v1.0/posts/`

In fact the only command I know to run a server on port 5000 is `python manage.py runserver`.

There are the commands runs and returns below:
`python manage.py runserver` is OK, `http --json ...` is NOT OK, and a `http ...`test is OK
<img width="569" alt="2017-08-26 17 29 42" src="https://user-images.githubusercontent.com/10494196/29740217-15425510-8a84-11e7-85e3-a8a8b0b74b49.png">

**Comment by weqopy** [comment]
http://blog.csdn.net/huang5487378/article/details/60778293 (Last pic)
Yes it should have two terminal tab to start the server first and then start the http command.

Thank you very much.
