### ISSUE TITLE
[Question] using url_for from within blog post

### ISSUE THREAD

**Issue by Cwittofur** [miguelgrinberg/flasky#297]
First off - thank you for the book, it's been a huge help!

I'm writing a blog/photography site and in my blog posts I'd like to reference galleries, or individual photos. However I'm having a difficulty with getting the url_for to work. It's just being returned as an HTML Encoded string. 

What's the proper way to have the data come back from the database and then have Jinja2 respond to the formatting?

Take Care

**Comment by miguelgrinberg** [comment]
I suspect this has to do with the escaping of HTML entities that Jinja2 does, but can you show me an example of what your URLs look like and how do you use `url_for` in your templates?

**Comment by Cwittofur** [comment]
In the post I added a link as follows: 

`<a href="{{ url_for('main.contact') }}">Contact</a>`

It encoded the braces to %7B and %7D. When retrieving the post it simply added the string literal to the link.

Post Body = 
`This is a test to the <a href="{{ url_for('main.contact_page') }}">Contact Us</a> page`

the HTML received on page:

`<p>This is a test to the <a href="{{ url_for('main.contact_page') }}" rel="nofollow">Contact Us</a> page</p>`

Just looks like it's not parsing it. Thank you for the quick reply!

**Comment by miguelgrinberg** [comment]
And you are sending these templates to `render_template()`? If you are seeing the`{{` and `}}` in the browser, it seems Jinja isn't doing any parsing, which is odd.

**Comment by Cwittofur** [comment]
Yep; I'm calling the route for the individual blog post (outlined in your book). And inside the post itself I have the HTML markup for a link with a Jinja template for a url. I figured it would work but it doesn't seem to. I'm definitely scratching my head on this one!

**Comment by miguelgrinberg** [comment]
I need to see your code. Is that possible?

**Comment by Cwittofur** [comment]
blog/views.py
`@blog.route('/post/<int:id>')
def post(id):
    post = Post.query.get_or_404(id)
    return render_template('post.html', posts=[post], full_post=True)`

posts.html
`{% extends "base.html" %}

{% block title %}ContraDigital - Post{% endblock %}

{% block page_content %}
{% include '_posts.html' %}
{% endblock %}`

_posts.html
`<ul class="posts">
    {% for post in posts %}
        <li class="post">
            <div class="profile-thumbnail">
                
            </div>
            <div class="post-content">
                <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
                <div class="post-title">
                    <a href="{{ url_for('blog.post', id=post.id) }}"><h3>{{ post.title }}</h3></a>
                </div>
                <div class="post-body">
                    {% if full_post %}
                        {% if post.body_html %}
                            {{ post.body_html | safe }}
                        {% else %}
                            {{ post.body }}
                        {% endif %}
                    {% else %}
                        {% if post.body_html %}
                            {{ post.body_html | safe | truncate(100)}}
                        {% else %}
                            {{ post.body | truncate(100) }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="post-author">
                    <a href="{{ url_for('main.user', username=post.author.username) }}">
                        {{ post.author.username }}
                    </a>
                </div>
            </div>
            <div class="post-footer">
                {% if current_user == post.author %}
                <a href="{{ url_for('blog.edit', id=post.id) }}">
                    <span class="label label-info">Edit</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('blog.edit', id=post.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                {% endif %}
                <a href="{{ url_for('blog.post', id=post.id) }}">
                    <span class="label label-default">Permalink</span>
                </a>
            </div>
        </li>
    {% endfor %}
</ul>`

It's very similar to the book; I haven't done much else to it.

**Comment by miguelgrinberg** [comment]
I don't see the `This is a test...` line with the problematic `url_for()` in your template. i think I understand now, you have Jinja2 statements in a template variable? That is not going to work, Jinja evaluates expressions in the template, not in the variable values.

Your posts are not templates, they are just values. If you want them to be parsed as templates there is probably a way, but it is not going to be as simple as calling `render_template()`, you'll have to pass the text of your post as a template source code to Jinja2 for parsing.
