### ISSUE TITLE
user api missing id?

### ISSUE THREAD

**Issue by junfenggood** [miguelgrinberg/flasky#298]
File: flasky/app/api_1_0/users.py,  
Function : get_user_posts(id) and get_user_followed_posts(id)
`prev = url_for('api.get_user_posts', page=page-1, _external=True)`-->22
`next = url_for('api.get_user_posts', page=page+1, _external=True)`-->25
`prev = url_for('api.get_user_followed_posts', page=page-1, _external=True)`-->44
`next = url_for('api.get_user_followed_posts', page=page+1, _external=True)`-->48
      
These lines, I didn't see the pramater `id` in the url_for function.

**Comment by miguelgrinberg** [comment]
Oh yeah, this was already reported, but apparently I forgot to make an update here. It is now fixed. Thanks!
