### ISSUE TITLE
Issue with db init

### ISSUE THREAD

**Issue by SL36** [miguelgrinberg/flasky#299]
I am on chapter 5- Database Migrations with Flask-Migrate and am stuck on this: 

`(venv) My-MacBook-Pro:flasky user$ python3 hello.py db init`
`(venv) My-MacBook-Pro:flasky user$`

The book says that this should create a migration repository, but it doesn't seem to do anything.  I tried "python hello.py db init" as well.

In the above example, I commented out: 

`if __name__ == '__main__': app.run(debug=True)`

in hello.py.  If I don't comment it out, it runs the application on my local host. 

Any idea why the db init command isn't working?  I had an issue earlier in the book with
 `python3 hello.py shell`

which was solved with:
`python3 -i hello.py`

So I'm not sure if something is outdated or I am just interpreting the instructions incorrectly.  Any help is much appreciated.

**Comment by miguelgrinberg** [comment]
@SL36 I assume you are typing the code yourself, correct? Based on what you are showing me, my guess is that you missed to install and configure Flask-Script (end of Chapter 2), which is the tool that is used to provide extra commands such as the `db` that isn't working for you.

**Comment by SL36** [comment]
Re-read that part of the chapter- I had Flask-Script installed, but was missing 
```
if __name__ ==  '__main__':
    manager.run() 
```
in hello.py.  Thank you
