### ISSUE TITLE
hello sir  i am in trouble when i deployed my flask in heroku

### ISSUE THREAD

**Issue by WJFQQQ** [miguelgrinberg/flasky#300]
here is the problem

`$ git push heroku master
Counting objects: 144, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (96/96), done.
Writing objects: 100% (144/144), 130.66 KiB | 0 bytes/s, done.
Total 144 (delta 42), reused 137 (delta 39)
remote: Compressing source files... done.
remote: Building source:
remote:
## remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to yiqihapi.
remote:
To https://git.heroku.com/yiqihapi.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/yiqihapi.git'`

and i open the link try to solved it [https://devcenter.heroku.com/articles/buildpacks#detection-failur](url) 
  i followed the instruction  of the link . but it still get the same problem ...  
:(

**Comment by WJFQQQ** [comment]
windows 10

**Comment by miguelgrinberg** [comment]
Do you have all the expected things? The requirements.txt and Procfile files in the top-level? It seems Heroku thought your project was an Erlang project, not Python. Something must be missing in your project that makes Heroku use the wrong language.
