### ISSUE TITLE
about Models/User.confirm

### ISSUE THREAD

**Issue by DreamHackchosenone** [miguelgrinberg/flasky#302]
when confirm is successful，
db.session.add(self)
but dont commit?
i see the viewfunction->register()
it doesn't have db.session.commit() either
so i think may be you forget db,session.commit()

**Comment by miguelgrinberg** [comment]
This project is configure to automatically commit the session at the end of the request: https://github.com/miguelgrinberg/flasky/blob/master/config.py#L8.

**Comment by DreamHackchosenone** [comment]
thank you for your reply，
I forgot to check  the configure file
I'm sorry to waste your time
and thanks again
