### ISSUE TITLE
from manage import app, mail Traceback (most recent call last):   File "<stdin>", line 1, in <module> ImportError: cannot import name mail

### ISSUE THREAD

**Issue by crakama** [miguelgrinberg/flasky#304]
Any idea what the problem could be?

**Comment by miguelgrinberg** [comment]
do you have a `mail` symbol defined in your `manage.py` module? The error says you don't.

**Comment by crakama** [comment]
I solved it. Thank you. The problem was  I was creating and initializing the mail object at the same time inside the create_app function like this mail = Mail(app). What I did is, separate the two by defining mail = Mail() outside the create function first then initialized "mail" variable inside the create_app function like this mail.init_app(app). Hope this helps a lost soul in future.
