### ISSUE TITLE
from ._compat import iteritems ImportError: No module named _compat

### ISSUE THREAD

**Issue by krantson** [miguelgrinberg/flasky#306]
I dont what's the problem ? 
(second_project) skyla@skyla:~/flask$ python hello.py
Traceback (most recent call last):
  File "hello.py", line 6, in <module>
    from flask_script import Manager
  File "/home/skyla/.pyenv/versions/second_project/lib/python2.7/site-packages/flask_script/__init__.py", line 17, in <module>
    from ._compat import iteritems
ImportError: No module named _compat

**Comment by miguelgrinberg** [comment]
@krantson your install of Flask-Script appears to be bad. Can you try to uninstall and reinstall?

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply to the second edition of the book.
