### ISSUE TITLE
config.py unable to access environment variables

### ISSUE THREAD

**Issue by noisytoken** [miguelgrinberg/flasky#307]
```python
class Config:
    ...
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    ...
```

`MAIL_USERNAME` and `MAIL_PASSWORD` always receive `None`. I am using Windows and I have set the environment variables correctly. All other scripts can read these environment variables but `Config.py` unable to do so.

What could be issue ?

**Comment by miguelgrinberg** [comment]
print `os.environ` to debug this issue. I'm not sure I can help you, `config.py` is not special in any way, it should see the environment.
