### ISSUE TITLE
Email Authentication

### ISSUE THREAD

**Issue by tnolan8** [miguelgrinberg/flasky#309]
Hi Miguel,

I have an odd issue with authenticating users via email. I'm able to send emails just fine and it generates the token for that user all seems to be well. However when the User clicks on the link and it brings them back to the site to log in to confirm their account it always says that the token is invalid. The thing that makes this odd is that when I click the link to resend an email with a new confirmation link it works just fine. I'm not really sure why it's behaving like this i.e. doesn't work the first time but works the second. It looks like to me the first time it runs `data = s.load(token)` runs nothing. 

Any thoughts what might be causing the issue?

**Comment by tnolan8** [comment]
Found the issue, my own fault, hadn't committed the new User before calling `self.id`

**Comment by Thiringai** [comment]
am having the same problem for two days, how do solve it
