### ISSUE TITLE
Why would flask cli break my imports?

### ISSUE THREAD

**Issue by rlam3** [miguelgrinberg/flasky#310]
I've been using flask-script and looking and testing if I should switch over to flask-cli...

However flask-cli doesn't recognize my app structure it seems and continues to say it cannot find extensions file even though it would work in a python manage.py runserver script. Is there something I have to set for a root directory in flask-cli to have my imports follow through correctly? 

```bash
my treee

app/
  --extensions.py
  --application.py
manage.py
cli-manage.py
```

```py
#application.py

from flask_script import Manager, Shell, Server

from app.extensions import ext1, ext2
manager = Manager(create_app())

def create_app():
  register_extensions()
  register_blueprints()

...
etc.
...

```

```py
manage.py

from app.application import create_app

manager = Manager(create_app())

def _make_context():
   return dict(app=manager)

# Access to shell
manager.add_command('shell',
    Shell(
        make_context=_make_context,
        use_ipython=True
    )
)

manager.add_command("runserver",
    Server(
        threaded=True,
        use_reloader=manager.app.debug,
        use_debugger=manager.app.debug,
        host='0.0.0.0',
        port=5000,
    )
)

if __name__ == '__main__':
    manager.run()
```

```py
import click

from app.application import create_app

app = create_app()

@app.shell_context_processor
def make_shell_context():
    return dict(
        app=app
    )

```

ERROR:
```
ImportError: No module named extensions
```

I made a fresh code source and it does the same thing.... Is there something I'm doing wrong here when using factory pattern with flask-cli? I'm feeling a lot of resistance towards using flask-cli if I have to rework all my import statements in my whole project. Really appreciate your help here @miguelgrinberg Thank you! 

https://github.com/rlam3/flaskcli1

**Comment by miguelgrinberg** [comment]
Remove the `__init__.py` and `__init__.pyc` from your top-level directory and then you should be fine. These files make python believe the main directory of the package is one directory above, so that is the directory that is added to the Python path. Usually you want your top-level directory to not be a Python package, so that the current directory goes to the path.

**Comment by rlam3** [comment]
@miguelgrinberg Thank you so much! I guess I can sortof migrate to flask-cli... I've read your blog post on how to migrate and your thoughts on it. And to this day I still think cli should have been seperated from the core. Are you currently still using flask-script or flask-cli? Or a better question is, what can flask-script do that flask-cli cannot do yet and visaversa? Thanks!

**Comment by miguelgrinberg** [comment]
@rlam3 Flask-Script is not being actively developed anymore, judging from the activity on GitHub. So I think you'd want to migrate to the Flask CLI just for that reason alone.

Back when Armin decided to add the Flask CLI I was against it. I still think it was a mistake, I would have preferred a Flask-Click extension that you an install only if you needed a CLI. Both approaches are fairly similar, but there are some problems with the reloader that Flask CLI has addressed and Flask-Script has not. There is also some clunkiness in having to set environment variables to work with the Flask CLI that Flask-Script does not have. So in my view, it is kind of a tie, but given that Flask-Script is unlikely to be maintained in the future, the choice is the Flask CLI.

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply to the second edition of the book.
