### ISSUE TITLE
the  "password_reset_request" has a problem

### ISSUE THREAD

**Issue by auqf** [miguelgrinberg/flasky#311]
the function " password_reset_request" can not checking the email adress if exist, and the form does't do reset if you submit an  error email address.
in the flasky, how to reset the form?

**Comment by miguelgrinberg** [comment]
The email is not validated on that form. That is done on purpose, so that the form cannot be used as a way to find out what emails are registered or not.

**Comment by auqf** [comment]
If I modify the function, and how to reset the form

**Comment by miguelgrinberg** [comment]
What do you mean by "reset the form"? Erase the values of all fields? Just set the fields to empty strings. For example:

    form.email.data = ''

**Comment by auqf** [comment]
I find to do like that is very trouble .
@auth.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
    if not  current_user.is_anonymous:
        return redirect(url_for('main.index'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = user.generate_reset_token()
            send_email(user.email, 'Reset Your Password',
                       'auth/email/reset_password',
                       user=user, token=token,
                       next=request.args.get('next'))
            flash('An email with instructions to reset your password has been '
              'sent to you.')
            return redirect(url_for('auth.login'))
        else:
            flash('Your email %s is not exist'%(form.email.data) )
    return render_template('auth/reset_password.html', form=form)

**Comment by miguelgrinberg** [comment]
This should do it:

```python
    # ...
        else:
            flash('Your email %s is not exist'%(form.email.data) )
            form.email.data = ''
    return render_template('auth/reset_password.html', form=form)
```

**Comment by auqf** [comment]
If there is a global method to reset the form contents?

**Comment by auqf** [comment]
and how to do that, after the user write the email address  before he submits ,it  check the email if exist?

**Comment by miguelgrinberg** [comment]
The server is not going to see the email that the user types until the form is submitted. You can do an asynchronous submission (ajax), which submits the form data but does not load a new page, but I'm not really sure what's the benefit of doing that.

**Comment by simanacci** [comment]
@miguelgrinberg when running tests, I have to edit `expiration=` and `max_age` from 3600 to 1 for it to pass. Why doesn't it use the test value?  
https://gist.github.com/simanacci/128fd94729bb8394b41c9c374ea6da1e

**Comment by miguelgrinberg** [comment]
@simanacci can you be more specific please? What test is this about, and how does it fail?

**Comment by simanacci** [comment]
I'm testing the expired token. I've set it to expire after 1s; in my test I try to verify the new password which should fail since expiration is set to 1s and I called `time.sleep(2)` before reseting.

**Comment by miguelgrinberg** [comment]
But this isn't a bug in the application, you are just telling me that the application does not have an option to generate shorter tokens, which is not a feature that I have intended.

A better way to check for expired tokens would be to mock the time, so that you can get the token, advance the time more than one hour and then ensure the token is rejected. This is also better because you are not required to sleep, so your test will run faster.

**Comment by simanacci** [comment]
@miguelgrinberg I didn't know about mocking time. However, I couldn't find a way to simulate/mock/fasten a 10 second wait so I created a backdated TimestampSigner for testing.
