### ISSUE TITLE
About db.Column some problem

### ISSUE THREAD

**Issue by sandylili** [miguelgrinberg/flasky#312]
I find this code  in  'models.py'
```
 class User(UserMixin, db.Model):
    ...
    about_me = db.Column( db.Text() )
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column( db.DateTime() , default=datetime.utcnow)
    ...
 class Post(db.Model):
    ...
    body_html = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    ...
````
Are there any differences between   db.Text()  and  db.Text  , db.DateTime() and db.DateTime ?

Thank you!
@miguelgrinberg

**Comment by miguelgrinberg** [comment]
See the documentation regarding this here: http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.Column.params.type_

Quoted from that page:

>  If no arguments are required for the type, the class of the type can be sent as well

**Comment by sandylili** [comment]
get!
Thank you !@miguelgrinberg
