### ISSUE TITLE
Why init_app is declared?

### ISSUE THREAD

**Issue by ant-** [miguelgrinberg/flasky#315]
Hi, I can't understand what `init_app` method does for?
It is declared in example 7.3. when we talking about Blueprints.
I commented out the declaration and the invocation and nothing is changed, which is not surprising because the method contains the only one operator `pass`. 
So, why it is declared?

**Comment by miguelgrinberg** [comment]
The `init_app()` method is there as an option to run some configuration specific initialization. In chapter 7 the method isn't used, but it'll be used near the end of the book to specify deployment options.
