### ISSUE TITLE
Want to ask you a question

### ISSUE THREAD

**Issue by Jing-Yan** [miguelgrinberg/flasky#316]
hi sir,I follow your method in the command line test to send mail, and log in to the mailbox found that you can receive the file, but unfortunately when I run the program directly, and register for an account and found the mailbox can not receive the verification file, throw such an error on the terminal
![image](https://user-images.githubusercontent.com/20953101/32718888-8c3f4a4e-c899-11e7-9948-030a4547fe76.png)

**Comment by Jing-Yan** [comment]
And I have been stuck here, can not be verified, really distressed
![image](https://user-images.githubusercontent.com/20953101/32719227-98be50c0-c89a-11e7-9573-9f9172add338.png)

**Comment by miguelgrinberg** [comment]
@Jing-Yan can you send email to the same address from the same machine using a regular email client?

**Comment by Jing-Yan** [comment]
It's really amazing. I didn't get the email yesterday. I just tested it today.
But I also want to ask you, how come after the verification success there is no form?
![image](https://user-images.githubusercontent.com/20953101/32758728-d4c35b16-c920-11e7-99e8-336116cd69d4.png)

**Comment by miguelgrinberg** [comment]
@Jing-Yan review the role assignments for your user. The form does not appear because this user `fenng` does not have the role that gives the user the ability to write blog posts.

**Comment by Jing-Yan** [comment]
It's done, thank you very much!
