### ISSUE TITLE
Suggestion: ENV setup for Chapter 7 Unittest

### ISSUE THREAD

**Issue by ericchou1** [miguelgrinberg/flasky#317]
For Chapter 7, just a suggestion to include a note about setting the FLASK_APP to flasky.py before the unit test output since it has always been hello.py up to this point and one might easily forget that was set and wonder why 'flask test' command throws an error. 

Include this: 

(venv) $ set FLASK_APP=flasky.py

Before this output: 

(venv) $ flask test
test_app_exists (test_basics.BasicsTestCase) ... ok
test_app_is_testing (test_basics.BasicsTestCase) ... ok

.----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK

Thank you.

**Comment by miguelgrinberg** [comment]
Oh, right, this is mentioned a couple sections later, for `flask run`. I'll change it, thanks!

**Comment by miguelgrinberg** [comment]
This is now addressed in the manuscript.
