### ISSUE TITLE
Got the python version wrong when deploy my flask web app to heroku

### ISSUE THREAD

**Issue by GinnyGaga** [miguelgrinberg/flasky#319]
Hi miguel,the problem cost me for many days,it's my pleasure if you can help me...
I use linux and ubuntu17.04,My virtualenv is python3.5.3,and runtime.txt:python-3.5.3,and my app include the requirements.txt and Procfile,I create the runtime.txt and Procfile file by echo "python-3.5.3">runtime.txt,and echo "web: gunicorn manage:app">Procfile,no wrong when I ran the pip install -r requirements.txt.
But when I try to deploy the app to heroku,it happens:

```
(venv3) mo@mo-VirtualBox:~/flasky_1$ git push heroku master
Counting objects: 1178, done.
Compressing objects: 100% (879/879), done.
Writing objects: 100% (1178/1178), 231.05 KiB | 0 bytes/s, done.
Total 1178 (delta 765), reused 428 (delta 262)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote:  !     The latest version of Python 3 is python-3.6.3 (you are using Python-2.7.13, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.3).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing Python-2.7.13
remote:  !     Requested runtime (Python-2.7.13) is not available for this stack (heroku-16).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ginnymo.
remote: 
To https://git.heroku.com/ginnymo.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ginnymo.git'
```

**Comment by GinnyGaga** [comment]
The runtime.txt ,Procfile,requirements.txt are in my  root folder of the project,and I also try to change the runtime.txt to python-3.6.3,try deleting and deploying the app again and again,it seems that the heroku doesn't read my runtime.txt

**Comment by miguelgrinberg** [comment]
Make sure runtime.txt is also added to your git repo. Also note that the two choices you have at this time are 2.7.14 and 3.6.3. You cannot use 3.5 with Heroku.

**Comment by GinnyGaga** [comment]
I know what's wrong , I try to install python 3.6.3 in virtualenv,but failed,it turned out that my ubuntu system was broken,due to long time to find the cause,I reinstall the system,install 3.6.3,and no problems happened on the way on heroku.thank you so much..
--
