### ISSUE TITLE
Logging in flasky

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/flasky#324]
Hi, Miguel.

I notice you change the logger handler's level from `WARNING` to `INFO` in the second edition, why did you do it?

With [#2436](https://github.com/pallets/flask/pull/2436), the default level of Flask's built-in logger (`app.logger`) is `WARNING`. So, the handlers in flasky will not get the log records less than `WARNING` level. Maybe you need to add this line:
```python
app.logger.setLevel(logging.INFO)
```

**Comment by greyli** [comment]
Besides, since Flask provides a default `StreamHanlder` handler, do we need to add another one? Or maybe we should remove the default one with `removeHandler`.

**Comment by miguelgrinberg** [comment]
The change that you refer to is only in master right now. You bring up a good point though, I need to review my logging configuration so that it works both with and without this change.

**Comment by greyli** [comment]
Do we really need to log at `INFO` level in production?

**Comment by miguelgrinberg** [comment]
You are going to have lots of opinions on this. My personal take is that if something were to fail on a production system I want to have as much information as possible, so I prefer to log more.

**Comment by greyli** [comment]
I got it, thanks!
