### ISSUE TITLE
How to use the same wtform class to peform two different actions

### ISSUE THREAD

**Issue by noisytoken** [miguelgrinberg/flasky#325]
Let's say I have a class `Employee` defined as follows:

```python
class EmployeeForm(FlaskForm):
    name = StringField('Username', validators=[DataRequired()])
    email = StringField('Username', validators=[DataRequired()])
    designation = StringField('Username', validators=[DataRequired()])    
    submit = SubmitField("Submit")

    def validate_email(self, field):                
        if db.session.query(Employee).filter(Employee.email == field.data).first():
            raise ValidationError("Email already exists.")
```

The `EmployeeForm` checks duplicate email while adding new records. But it also checks when I update the same record. Obviously I don't want that. How can I prevent it from validating while updating record.

**Comment by miguelgrinberg** [comment]
This situation is actually covered in chapter 10, for the edit profile editor for administrators. See the form class: https://github.com/miguelgrinberg/flasky/blob/master/app/main/forms.py#L22.

**Comment by noisytoken** [comment]
Got it. Thanks
