### ISSUE TITLE
querying User#followed_posts

### ISSUE THREAD

**Issue by qwert2603** [miguelgrinberg/flasky#329]
hello!
would it be easier to use `union` operation to select `followed_posts` for `User` like this:
```
@property
def followed_posts(self):
    return Post.query \
        .join(Follow, Follow.followed_id == Post.author_id) \
        .filter(Follow.follower_id == self.id) \
        .union(Post.query.filter_by(author_id=self.id))
```
so we could avoid "self follows" and don't have to "minus one" in followers/followed count etc.

**Comment by miguelgrinberg** [comment]
Yes, this is easier, but it requires more work for the database to obtain the final query. I actually took this approach on my Flask Mega-Tutorial.
