### ISSUE TITLE
SQLAlchemy error when adding users

### ISSUE THREAD

**Issue by mojochao** [miguelgrinberg/flasky#33]
When running the dev server at git tag '14a' (or later) I encounter the following error when adding a new User into the db:

sqlalchemy.exc.StatementError: utcnow() takes no arguments (1 given) (original cause: TypeError: utcnow() takes no arguments (1 given))

I'm using Python 3.4.  According to http://stackoverflow.com/questions/22481905/sqlalchemy-python-3-default-column-value this is a known issue.

What version of Python should I be using for the flasky app?

Many thanks in advance.

**Comment by miguelgrinberg** [comment]
The issue with default values was fixed long ago. Are you using the latest versions of Python 3.4 and SQLAlchemy?

**Comment by mojochao** [comment]
That was indeed the problem.  I had installed SQLAlchemy 0.8.4 specified in the requirements.txt with my Python 3.4.2 installation.  Upgrading SQLAlchemy to 0.9.8 solved the problem.

Thanks Miguel.
