### ISSUE TITLE
Index Template - Permissions Access?

### ISSUE THREAD

**Issue by track02** [miguelgrinberg/flasky#330]
Hi Miguel,

I've been working through the first edition of your book and maybe it's just something I've missed but I can't seem to figure out how the Index Template has access to the Permission Class (defined in Models.py), would you be able to offer an explanation on how this works?

` {% if current_user.can(Permission.WRITE) %}`

```
class Permission:
    FOLLOW = 1
    COMMENT = 2
    WRITE = 4
    MODERATE = 8
    ADMIN = 16

```
I understand current_user is made available via flask-login as a proxy for the specified User type and additional variables can also be passed when calling render_template but I can't see where this comes from.

Many thanks.

**Comment by miguelgrinberg** [comment]
This is done [here](https://github.com/miguelgrinberg/flasky/blob/9bcab0e17504629b4bfe7ca557f1fc44d920f767/app/main/__init__.py#L9-L11), by installing an app context processor function. The dict that is returned by this function is added to the template context.

**Comment by track02** [comment]
Thanks Miguel, that clears things up.
