### ISSUE TITLE
In models.py ,line 153

### ISSUE THREAD

**Issue by ycngu** [miguelgrinberg/flasky#333]
if i don't add
 “db.session.commit()”
after 
”db.session.add(self)”

I can't enter other pages expect “unconfirmed.html” even if i click confirm link.

Sorry for my poor English ，i am working hard on it.

**Comment by miguelgrinberg** [comment]
Your English is totally fine. :)

See https://github.com/miguelgrinberg/flasky/blob/master/app/auth/views.py#L76. Putting the commit in the view function is better. Check if you have it there.

**Comment by ycneverGU** [comment]
https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L203

the ping method doesn't have commit()

https://github.com/miguelgrinberg/flasky/blob/master/app/auth/views.py#L15

should i add 'db.session.commit()' after 'current_user.ping()' ?
————————————————————————————————————
At my first question，i found that it couldn't work if i putting the commit in the view function,but the application can working if putting commit in modles.py.(my flask version is 0.10.1)

It‘s strange situation.

**Comment by miguelgrinberg** [comment]
The ping should work as it is, with the commit in the view function.
