### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)

### ISSUE THREAD

**Issue by OwiyeD** [miguelgrinberg/flasky#334]
hello Miguel I went through you tutorial and am real grateful because I had never had such experience with python for web.
Kindly I receive the above error when running the test.py. Kindly help because I cannot do other test without the initial test.
Thank you in advance.

**Comment by miguelgrinberg** [comment]
The error seems pretty clear, the db driver is unable to open the sqlite file. Look at the connection URL and make sure it points to the location where your database is. Also make sure the database is created and has been populated with all its tables.

**Comment by OwiyeD** [comment]
Thank you so much I solved it.

**Comment by rip222** [comment]
So what was the solution?

**Comment by developMediaSoft** [comment]
@rip222 I reckon they've made the path in the "URI" relative. You'd expect `sqlite:///tmp/sqlite.db` to mean "An sqlite file at /tmp/sqlite.db", but it actually means "an sqlite file at ./tmp/sqlite.db" - so  in the current working directory, not the root)

**Comment by tashlinr** [comment]
@rip222 In the config.py file 

SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite://' + os.path.join(basedir, 'app.db')

change 'sqlite://'  --> 'sqlite:///' 

worked for me :)

**Comment by pes3** [comment]
@tashlinr  I tried that and now I am getting KeyError: 6116 and at the bottom ValueError: invalid literal for int() with base 10: '\\Users\\*****\\githubb\\Flask\\app.db' - any reason why?

**Comment by xarbi** [comment]
This kind of error can be the result of one single coma (,) or something like it. I always face these problems and try  to fix it repeatedly, most of the time I just fix without realizing.

**Comment by sisayie** [comment]
In case someone gets here again after being greeted by that error, the valid SQLite URL forms are any one of the following:
 sqlite:///:memory: (or, sqlite://)
 sqlite:///relative/path/to/file.db
 sqlite:////absolute/path/to/file.db

**Comment by Mezen45** [comment]
If u are developing under Linux distribution u should give permission to Read and write and maybe execute to the directory and the app.py files chown 600 something like that I changed permission so it's fine

**Comment by kobyfogel** [comment]
following the miniblog tutorial, i got exactly the same issue. but i cannot resolve the problem. i tried all of the solutions above

**Comment by miguelgrinberg** [comment]
@kobyfogel what is your database URL?

**Comment by kobyfogel** [comment]
I just copied the relevant code from your GitHub repo. Solved the issue. Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Mezen45** [comment]
Good Morning

I hope you get use of it
I can just adjust my code for you to work ... if there is a problem tell me

Thanks
-------------
Mezen

**Comment by kobyfogel** [comment]
Hi. I have another problem.
I was testin the login with hash problems and got errors. Visiting GitHub again, I followed instructions and tried to delete my migrations folder in order to try from scratch. Now, after successful db init, I get this error when trying flask db migrate -m "users table":

ERROR [root] Error: Can't locate revision identified by '5d4793a2b032'

I really don’t know whats going on. Trying to google it, I totally got lost. Please help..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by miguelgrinberg** [comment]
You shouldn't be blindly following instructions you find on the Internet without a backing everything up in case you make things worse.

This error means that you have a migrated database, but the migrations on which the database was built have been deleted. If you want to start fresh 100% you have to delete the migrations and the database both, you can't delete just one.

**Comment by ariyo123** [comment]
Dear Friends, I also have the same issue. but while trying to solve, i notice that the column names of my DB differs in terms of case sensitivity with what i have in python objects which caused the error. After correcting by making sure my python objects correspond to my Db column names, the issue was finally resolved.
