### ISSUE TITLE
TypeError: 'unicode' does not have the buffer interface

### ISSUE THREAD

**Issue by gladuo** [miguelgrinberg/flasky#34]
I run the final edition and when I log in it raise 

> TypeError: 'unicode' does not have the buffer interface

It seems that 

> return check_password_hash(self.password_hash, password)

a is str and b is unicode, I'm not sure what to do.

**Comment by miguelgrinberg** [comment]
It looks like there is a bad interaction between Werkzeug 0.9.4 and Python 2.7.7. Back when I tested this Python 2.7.7 wasn't out yet so I did not find this out.

If you upgrade Werkzeug to 0.9.5 or newer the problem will go away.
