### ISSUE TITLE
Invalid field name

### ISSUE THREAD

**Issue by yue-qiu** [miguelgrinberg/flasky#340]
Hi,i am a freshman and i really dont kown why that if i want to register，it always says:
Invalid field name '<UnboundField(PasswordField, ('密码',), {'validators': [<wtforms.validators.DataRequired object at 0x00000214323ADBE0>]})>' After i submit my password.
Thank u（密码 means password）

**Comment by kamyanskiy** [comment]
@yue-qiu can you show your form code ?

**Comment by yue-qiu** [comment]
@kamyanskiy sorry，i forgot to post my code
class RegistrationForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Length(1,64),Email()])
    username = StringField('昵称',validators=[DataRequired(),Length(1,64)])
    password = PasswordField('password',validators=[DataRequired()])
    password2 = PasswordField('Confirm password',validators=[DataRequired(),EqualTo(password,message='两次密码不一致，请再次输入')])
    submit = SubmitField('提交')

    # 如果表单类中定义了以validate_开头，后面跟着字段名的方法，这个方法就和常规的验证函数一起调用。
    def validate_eamil(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email已经存在!')

    def validate_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('该昵称已被占用')

**Comment by kamyanskiy** [comment]
@yue-qiu can you try as suggested in documentation: http://flask.pocoo.org/docs/0.12/patterns/wtforms/#the-forms

And also it would be good to see full error stacktrace.

**Comment by yue-qiu** [comment]
@kamyanskiy  i changed my code to
```
password = PasswordField('password',validators=[DataRequired(),EqualTo('password2',message='两次密码不一致，请再次输入')])
    password2 = PasswordField('Confirm password',validators=[DataRequired()])
```
and the problem be sovled finally,thank u

**Comment by kamyanskiy** [comment]
@yue-qiu your error was that matcher wants string 'password' as first parameter instead of password field like you passed :-)
Happy to help to you :)

**Comment by yue-qiu** [comment]
@kamyanskiy sorry,in fact it is this first time i use github,so actually i dont know how to close the issue,let me try to google it...

**Comment by kamyanskiy** [comment]
@yue-qiu seems we cannot because we are not owners of this project, sorry :)

**Comment by yue-qiu** [comment]
@kamyanskiy you are right! it does work

**Comment by Mwawaka** [comment]
Thanks very much. It was really helpful.
