### ISSUE TITLE
request blocked when press go back

### ISSUE THREAD

**Issue by everest5216cbaok** [miguelgrinberg/flasky#344]
If two users connect to server, and one press the "go back" button and then the other one press any link of the application, no response.How to fix it?
Configuration:
- Web browser and its version: Chrome.(maybe Edge also)
- Operating system and its version:Windows 10(Client)
- Version: 7a, 17b(or annother)
- Server run command: flask run --host 0.0.0.0

Steps to reproduce the problem:
phenomenon1:
1. two users connect to server（BrowserA and BrowserB）
2. After A press a link and then press the "go back" button
3. B press any link of the application
result:no response
and then:
4. A press any link of the application
5. B has response.
A and B are different Browser or from different Computer.
phenomenon2
1. two users connect to server（BrowserA and BrowserB）
2. A press the "go back" button and then press the "go forward" button
3. B press any link of the application
result: it worked, no problem.

screen shoot:
step1:press the 'go back' button
![bbd8ef32-4ac6-8d75-96d8-47a90d8e4920](https://user-images.githubusercontent.com/14087999/37403511-0a8ca4c0-27ca-11e8-9d68-dbdd77f696c6.jpg)
step2:press any link (in another brower)
![pzkda rulmpu ec 8spfv43](https://user-images.githubusercontent.com/14087999/37403546-23a763c8-27ca-11e8-8a2f-5e10a5fd185f.png)
step3:no response
![q7 4l9p 34 du d k2ypwiq](https://user-images.githubusercontent.com/14087999/37403583-3d01e050-27ca-11e8-8579-dd84110b24d2.png)

In server, request cannot reach to route function until A press any link or waiting for a long time.

**Comment by miguelgrinberg** [comment]
The Flask development web server is single threaded, that could be causing problems when you are accessing the site from two browsers. Try running the application as follows to enable multi-threading:

```
$ flask run --with-threads --host 0.0.0.0
```

**Comment by everest5216cbaok** [comment]
Thank you, It works!!!
But I don't know what has happend when press "go back" button. The following is my guess(sorry for my poor knowledge), is it right?
When I press any link of the web, the connection is stoped when finishing job. But if I press "go back" button, connection is keeping until Last for a fixed time. And because single thread, no request (not belong to this connection )can be accepted until the previous connection is stopped.

**Comment by everest5216cbaok** [comment]
Thank you very much!
When we use gunicorn, we can also refer to this link for multithreading:
https://stackoverflow.com/questions/35837786/how-to-run-flask-with-gunicorn-in-multithreaded-mode
