### ISSUE TITLE
Role permission

### ISSUE THREAD

**Issue by ogahozy** [miguelgrinberg/flasky#352]
I was experimenting with flasky and find out has permissions are not assigned to role. If I ran this code at the shell terminal, I got the email I set in my environment. 
>>from flask import current_app
>>flas=current_app.config['FLASKY_ADMIN']
>>print(flash)----give my email.
But the I ran the flasky as it is it doesn't not give me admin permission. That is : current_user.is_administrator () is not working. What do I do to affect this

**Comment by miguelgrinberg** [comment]
Did you set up your roles and permissions in your database? And after that, did you assign the administrator role to your user?

**Comment by ogahozy** [comment]
Yes. When I remove @admin_required from edit_profile_admin view. And login using the email I set in the environ. My role shows as admin. But I don't have permission because the command current_user. is_administrator() is not working

**Comment by miguelgrinberg** [comment]
Sorry, you say that you have the roles and permissions set up, but what you are saying implies that the permissions aren't correctly assigned to the administrator role. Can you double check that? Please dump the contents of the `Role` table to confirm.

**Comment by ogahozy** [comment]
the roles tables is just as it is:
class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permissions is None:
            self.permissions = 0
    @staticmethod
    def insert_roles():
        roles = {
            'User': [Permission.FOLLOW, Permission.COMMENT, Permission.WRITE],
            'Moderator': [Permission.FOLLOW, Permission.COMMENT,
                          Permission.WRITE, Permission.MODERATE],
            'Administrator': [Permission.FOLLOW, Permission.COMMENT,
                              Permission.WRITE, Permission.MODERATE,
                              Permission.ADMIN],
   }
   default_role = 'User'
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.reset_permissions()
            for perm in roles[r]:
                role.add_permission(perm)
            role.default = (role.name == default_role)
            db.session.add(role)
        db.session.commit()

**Comment by ogahozy** [comment]
I got it right. I deleted the data-dev.sqlite and migrations file and re-run flask migration. after which I setup my email in the environ. It is now working

**Comment by simanacci** [comment]
Hi, is Permission created with the intention of having bitwise operations to check for multiple permissions?

**Comment by miguelgrinberg** [comment]
@simanacci Yes. A Role is built as a set of permissions, and the checking is done with bitwise operations.

**Comment by simanacci** [comment]
Is the implementation mainly suitable for scenarios where a user can have overlapping permissions per role? I mean if a Role is restricted to a single task(Permission) then str would work fine.

**Comment by miguelgrinberg** [comment]
The idea is to allow multiple roles to share a permission. You can remove roles and assign permissions directly to users, but then managing these permission flags becomes tedious. The role groups a set of common permissions to simplify assignment to users.
