### ISSUE TITLE
Permalink on post view

### ISSUE THREAD

**Issue by ogahozy** [miguelgrinberg/flasky#354]
Sir on the views @main.route('post/<int:id>'). I change the int:id to slug. At the return render_template, the page does not load with posts=[post] but post=post. Every necessary thing about adding slug and title to models is in place. What could be the problem

**Comment by miguelgrinberg** [comment]
It's hard for me to know, it really depends on how you structure your template. If `posts=[post]` does not work but `post=post` does, then it seems you coded your template to take a single post as an argument, and not a list like mine was designed.

**Comment by ogahozy** [comment]
Do you mean the post.html? I cannot figure which of the templates

**Comment by ogahozy** [comment]
Found my mistake in the detail.HTML template
