### ISSUE TITLE
url_for() in unittest

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/flasky#355]
It seems that we have to push `app.test_request_context` ( or set `SERVER_NAME` ) before using `url_for()` in tests, otherwise you will get the error below:
```pytb
RuntimeError: Application was not able to create a URL adapter for request independent URL generation. You might be able to fix this by setting the SERVER_NAME config variable.
```

**Comment by miguelgrinberg** [comment]
Yes, that is correct, in general you'd want to use `url_for()` when there is a request context active. Have you found a problem with the tests where a call fails?

**Comment by greyli** [comment]
Oh,  I  made a mistake, I should create this issue in flasky's first edition, there are multiple `url_for()` call in [tests](https://github.com/miguelgrinberg/flasky-first-edition/blob/master/tests/test_api.py#L41).
