### ISSUE TITLE
Change SQLite into MySQL database.

### ISSUE THREAD

**Issue by trannhuphuan** [miguelgrinberg/flasky#367]
Hello Miguel!
I'm beginner and I'm trying to create website with MySQL database. I have tried with many ways on the Internet.  But I did not succeed, do have any suggestion for me with this question?
Currently, I'm using XAMPP for running the MySQL server and HeidiSQL for managing the database.
Thank you so much

**Comment by miguelgrinberg** [comment]
There is nothing special regarding MySQL, all you need to do is create your database and then run the migration framework. Do you have the book? The chapter on deployment covers how to use MySQL, actually.

**Comment by royhananwar** [comment]
@trannhuphuan Hallo. in this repository this use Flask-Migrate.
that can handle for creating table for database, the points is you can use MySQL as database server if you configure that.
just install Flask-Migrate, Flask-SQLAlchemy, and Flask-MySQLdb.
you can see https://github.com/royhananwar/biohazard-blog/blob/master/app.py for configure database, but in that file i don't use Flask-Migrate and Flask-SQLAlchemy.
