### ISSUE TITLE
shell_context_processor

### ISSUE THREAD

**Issue by StephenChow93** [miguelgrinberg/flasky#368]
Traceback (most recent call last):
  File "/home/python/e/home/python/PycharmProjects/flasky-master/flasky.py", line 25, in <module>
    @app.shell_context_processor
AttributeError: 'Flask' object has no attribute 'shell_context_processor'

**Comment by StephenChow93** [comment]
how to run this project, i just want to see the result first

**Comment by miguelgrinberg** [comment]
@StephenChow93 my guess is that you are using an old version of Flask. Try to upgrade Flask to the latest version with `pip install --upgrade flask`.

**Comment by sfxdawn** [comment]
I was upgraded  but how to run this in terminal 
(py3_flask05) python@ubuntu:~/Desktop/flask1$ ls
flasky-3a  flasky-3b  flasky-3e  flasky-4a  flasky-4b  flasky-4c  flasky-5a  flasky-5b  flasky-5c
(py3_flask05) python@ubuntu:~/Desktop/flask1$ cd flasky-5c
(py3_flask05) python@ubuntu:~/Desktop/flask1/flasky-5c$ python hello.py shell
 * Serving Flask app "hello" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 334-944-645
