### ISSUE TITLE
Can't run from PyCharm

### ISSUE THREAD

**Issue by jhagege** [miguelgrinberg/flasky#371]
Hi Miguel,
Amazing book ! 

Trying to run from PyCharm without success.
i.e:

```
FLASK_APP = flasky.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder /Users/joachimhagege/Workspace/random_courses/flasky
/Users/joachimhagege/Workspace/random_courses/flasky/venv3/bin/python -m flask run
/Users/joachimhagege/Workspace/random_courses/flasky/venv3/bin/python: Error while finding module specification for 'flask.__main__' (ImportError: cannot import name 'current_app' from 'flask' (/Users/joachimhagege/Workspace/random_courses/flasky/venv3/lib/python3.7/site-packages/flask/__init__.py))

```

Thanks for help :)

**Comment by jhagege** [comment]
Please note when renaming email.py to my_email.py it fixes the issue.
What might it be due to ? 
Thanks

**Comment by miguelgrinberg** [comment]
Weird. You may want to make sure your current directory in the pycharm configuration for this project is set to the top level directory. The email.py file should not cause problems, because it should not be in the python path.
