### ISSUE TITLE
TypeError: <flask_script.commands.Shell object at 0x0000000004D13C88>: 'dict' object is not callable

### ISSUE THREAD

**Issue by zi-l** [miguelgrinberg/flasky#373]
In windows 7 with Pycharm, 
For Chapter 5.10 "**Integration with the Python Shell**",  register make_context:
‘def make_shell_context():     
      return dict(app=app,db=db,User=User,Role=Role)    
manager.add_command("shell", Shell(make_context=make_shell_context()))‘

when i run command "python app/welcome.py shell" in cmd or terminal in Pycharm, this error occurs:

(venv) C:\Users\biont.liu\PycharmProjects\flasky>python app/welcome.py shell
Traceback (most recent call last):
  File "app/welcome.py", line 106, in <module>
     manager.run()
  File "C:\Users\biont.liu\PycharmProjects\flasky\venv\lib\site-packages\flask_script\__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "C:\Users\biont.liu\PycharmProjects\flasky\venv\lib\site-packages\flask_script\__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "C:\Users\biont.liu\PycharmProjects\flasky\venv\lib\site-packages\flask_script\commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "C:\Users\biont.liu\PycharmProjects\flasky\venv\lib\site-packages\flask_script\commands.py", line 304, in run
    context = self.get_context()
  File "C:\Users\biont.liu\PycharmProjects\flasky\venv\lib\site-packages\flask_script\commands.py", line 293, in get_context
    return self.make_context()
TypeError: <flask_script.commands.Shell object at 0x0000000004D13C88>: 'dict' object is not callable

**when i return list/strings in make_shell_context(), it prompts "'list'/'str' object is not callable.”**

**Further step:**
1. For command "python app/welcome.py db init":
Creating directory C:\Users\biont.liu\PycharmProjects\flasky\migrations ... done
Creating directory C:\Users\biont.liu\PycharmProjects\flasky\migrations\versions ... done
Generating C:\Users\biont.liu\PycharmProjects\flasky\migrations\alembic.ini ... done
Generating C:\Users\biont.liu\PycharmProjects\flasky\migrations\env.py ... done
Generating C:\Users\biont.liu\PycharmProjects\flasky\migrations\README ... done
Generating C:\Users\biont.liu\PycharmProjects\flasky\migrations\script.py.mako ... done
Please edit configuration/connection/logging settings in 'C:\\Users\\biont.liu\\PycharmProjects\\flasky\\migrations\\alembic.ini' before proceeding.

2. For command "python app/welcome.py db migrate -m "initial migration":
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.

3. For command "python app/welcome.py db upgrade":
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by miguelgrinberg** [comment]
Did you try removing the `()` after `make_context=make_shell_context()`?

**Comment by zi-l** [comment]
@miguelgrinberg I am sorry to make this foolish mistake due to code completion, I should check it carefully.
Return to normal after I deleted  "()" after “make_context=make_shell_context()”
