### ISSUE TITLE
14a: api test failed

### ISSUE THREAD

**Issue by MarinZhang** [miguelgrinberg/flasky#376]
![image](https://user-images.githubusercontent.com/15984258/44088877-4773564a-9ff7-11e8-8131-c257dd76a88f.png)
when I do the test, the report is as below:

> HTTP/1.1 500 Internal Privoxy Error
> Cache-Control: no-cache
> Connection: close
> Content-Length: 744
> Content-Type: text/html
> Date: Tue, 14 Aug 2018 11:18:30 GMT
> Expires: Sat, 17 Jun 2000 12:00:00 GMT
> Last-Modified: Tue, 14 Aug 2018 11:18:30 GMT
> Pragma: no-cache
> 
> <html>
> <head>
>  <title>500 Internal Privoxy Error</title>
>  <link rel="shortcut icon" href="http://config.privoxy.org/error-favicon.ico" type="image/x-icon"></head>
> <body>
> <h1>500 Internal Privoxy Error</h1>
> <p>Privoxy encountered an error while processing your request:</p>
> <p><b>Could not load template file <code>no-server-data</code> or one of its included components.</b></p>
> <p>Please contact your proxy administrator.</p>
> <p>If you are the proxy administrator, please put the required file(s)in the <code><i>(confdir)</i>/templates</code> directory.  The location of the <code><i>(confdir)</i></code> directory is specified in the main Privoxy <code>config</code> file.  (It's typically the Privoxy install directory).</p>
> </body>
> </html>
> 
Is there any suggestion? Thanks avance.

**Comment by miguelgrinberg** [comment]
You are using a proxy server. The error is not from the Flask app, but from the server. Either fix your proxy server, or disable it for `http://localhost:5000`, so that you can connect to the application directly.
