### ISSUE TITLE
15d: Selenium causes Firefox to launch, but does not visit URLs

### ISSUE THREAD

**Issue by AEAMcNett** [miguelgrinberg/flasky#38]
I have checked out 15d, run `python manage.py db upgrade`, and `pip install -r requirements/dev.txt` prior to initiating the `python manage.py test` command. The latter causes the tests to run, and upon reaching the Selenium tests Firefox launches. However, a blank tab is all that results. The tests appear to hang in the terminal until the `test_admin_home_page (test_selenium.SeleniumTestCase) ... skipped 'Web browser not available' ` error is thrown. This is the only test that throws an error. 

Some cursory googling shows this may be a a Selenium defect, but I do not know how to adjust the Flasky code to rectify it. 

I'm using Firefox 36.0.1 on OS X.

**Comment by miguelgrinberg** [comment]
@AEAMcNett what version of Selenium do you have installed? Try running `pip install --upgrade selenium`. I just updated the required version in requirements/dev.txt a couple of days ago, the latest version works fine for me.

**Comment by AEAMcNett** [comment]
I ran ```pip freeze | grep selenium``` and had ```selenium==2.39.0``` installed.

I then ran ```pip install --upgrade selenium``` per your suggestion and now have ```selenium==2.45.0``` installed. A subsequent attempt at ```python manage.py test``` was successful: Selenium fired up Firefox and the browser tests ran as expected. 

Thank you!

**Comment by xinqiu** [comment]
I use selenium==2.48.0,but still have the problem.

```
test_admin_home_page (test_selenium.SeleniumTestCase) ... skipped 'Web browser not available'
```

I also use webdriver.Chrome(),webdriver.Safari(),but never succeed.

I will be very happy if you could help me.

**Comment by miguelgrinberg** [comment]
@xinqiu I've seen at different times that selenium is unable to control a given version of a browser, things tend to break from time to time. Downgrading Firefox to an old release might help. Also check their bug list to see if you can find your problem there: https://github.com/SeleniumHQ/selenium/

**Comment by xinqiu** [comment]
Ok，Thank you for helping me.

2015年12月16日星期三，Miguel Grinberg <notifications@github.com> 写道：

> @xinqiu <https://github.com/xinqiu> I've seen at different times that
> selenium is unable to control a given version of a browser, things tend to
> break from time to time. Downgrading Firefox to an old release might help.
> Also check their bug list to see if you can find your problem there:
> https://github.com/SeleniumHQ/selenium/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miguelgrinberg/flasky/issues/38#issuecomment-164864649>
> .
>


-- 
感谢您阅读我的这封邮件。
Thanks for reading my email.

by
     Xin Qiu
