### ISSUE TITLE
The CSRF token is missing

### ISSUE THREAD

**Issue by shaoeChen** [miguelgrinberg/flasky#381]
Dear..
i have a question, but it's not flasky's question, hope you can help me..

flask_wtf version: 0.14.2
i create MultiCheckboxField class follow flask_wtf document
```python
#  MultiCheckboxField
class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()
```
then create form
```python
#  Form
class FormRole_Func_manager(FlaskForm):
    all_function_option = MultiCheckboxField('all_function')
    submit = SubmitField('submit')
```
and then it's view function
```python
@main.route('/role_func_manager/<int:role_id>/', methods=['GET', 'POST'])
def role_func_manager(role_id):
    form = FormRole_Func_manager()
    role_func = Func.query.filter_by(id=role_id).with_entities(Func.id).all()
    all_funcs = Func.query.with_entities(Func.id, Func.func_module_name).all()
    form.all_function_option.choices = [(str(id), role) for id, role in all_funcs]
    form.all_function_option.default = [str(role.id) for role in role_func]
    form.process()
    if form.validate_on_submit():
        return 'hello'
    return render_template('main/Role_Func_manager.html', form=form)
```

My Question is ..
While i post the form, the form.validate_on_submit() never success, the error message is 『The CSRF token is missing.』  

no mater use `quick_wtf` or build html to add  `{{form.hidden_tag()}}` by my self , the html source code both have the hidden field about csrf, and the request.form both have the csrf information.

finally i import `flask_wtf.csrf.CSRFProtect` then initial it , i success , i can't understand why, hope you can teach me.

My English is a little weak. sorry.

**Comment by miguelgrinberg** [comment]
In your browser, open the debugger and look at the POST request that is sent when you submit your form. Do this for the case that works and the case that doesn't, and compare the contents of those two POST requests to find out what's different. I think that should give you some pointers into what the problem might be.
