### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_bootstrap'

### ISSUE THREAD

**Issue by lvorcool** [miguelgrinberg/flasky#385]
![image](https://user-images.githubusercontent.com/21286480/46222483-111c4e80-c383-11e8-92f7-b62a3669dce1.png)
![image](https://user-images.githubusercontent.com/21286480/46222491-19748980-c383-11e8-87fd-62b2aa3076d5.png)
Hello, I encountered an exception when practicing this section of knowledge, I activated the virtual environment, and executed `pip  install flask-bootstrap` in the virtual environment, why would you be prompted to find the module flask_bootstrap?

**Comment by miguelgrinberg** [comment]
There is really no reason for this error. I would suspect a mistake on your part. Maybe you are using a different virtualenv than the one you install flask-bootstrap on.

**Comment by bmaca** [comment]
I had the same issue, and I deactivated and re-activated my venv and it worked. 🤷‍♂
