### ISSUE TITLE
smtplib.SMTPSenderRefused smtplib.SMTPSenderRefused: (530, b'5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/?p=WantAuthError r126-v6sm1445775ita.26 - gsmtp', 'noreply@demo.com')

### ISSUE THREAD

**Issue by asgeY** [miguelgrinberg/flasky#386]
''' this is my __init__.py file '''
The app configuration used in a Flask Mail application

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail

app = Flask(__name__)
app.config['SECRET_KEY'] = '5791628bb0b13ce0c676dfde280ba245'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'login'
login_manager.login_message_category = 'info'
app.config['MAIL_SERVER'] = 'smtp.googlemail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = os.environ.get('EMAIL_USER')
app.config['MAIL_PASSWORD'] = os.environ.get('EMAIL_PASS')
mail = Mail(app)

from flaskblog1 import routes

**Comment by miguelgrinberg** [comment]
The error message is pretty specific, in particular the `Authentication Required` part.

**Comment by Yash-s001** [comment]
i too had same error with same code. Anyone there please help me.

**Comment by miguelgrinberg** [comment]
@Yash-s001 the error is clear, the server is asking you to provide authentication.

**Comment by Yash-s001** [comment]
> @miguelgrinberg how sir ?, can you please specify little more in this code.
please sir !

**Comment by Yash-s001** [comment]
> > @miguelgrinberg Finally got understand the problem ,and the error got solved now. Tooks little time but now it's done.
Thank you sir !

**Comment by marseyo** [comment]
> > > @miguelgrinberg Finally got understand the problem ,and the error got solved now. Tooks little time but now it's done.
> > > Thank you sir !

How??((( I can't solve it? Can you explain how have you solved it?

**Comment by miguelgrinberg** [comment]
@marseyo set the correct username/password for the account in the configuration.

**Comment by marseyo** [comment]
> @marseyo set the correct username/password for the account in the configuration.

in the configuration of what and in what place? can you more explain please

**Comment by miguelgrinberg** [comment]
@marseyo If you haven't read the book then none of this will make sense to you.

**Comment by marseyo** [comment]
thanks

**Comment by AMIT9027** [comment]
same problem sir can u help me

**Comment by pranitdubey** [comment]
So i was getting the error because i was not saving and pressing OK in the control panel where i set the environment variables , just ensure that you have saved the environment variables and you restart the text editor.
I also generated a app specific password from Google account.

Try to first see if you can retreive the environment variables in a simple programme like https://www.youtube.com/watch?v=IolxqkL7cD8
