### ISSUE TITLE
a little foolish question

### ISSUE THREAD

**Issue by super-buster** [miguelgrinberg/flasky#387]
Hi, I'm a beginner in learning flask, would you love to answer me some questions? plz< _>
emm,I don't know how to start this project,by flasky file? I have learnt to run manage.py to work that, but 
in the current version, seems this file do not exist.
Then, there is so much config file in the project, looks like so confusing, mystifying for me.I am reading the book for weeks, I find myself always lost in riddles.Need i understand or master them?
TKS.

**Comment by miguelgrinberg** [comment]
This repository is for the 2nd edition of my book. If you have the 1st edition, then use this repository instead: https://github.com/miguelgrinberg/flasky-first-edition.

The manage.py file and the Flask-Script extension are not necessary with newer versions of Flask, for that reason the 2nd edition of the book does not have them.
