### ISSUE TITLE
Chapter 11a,b checkout- "what's on your mind"

### ISSUE THREAD

**Issue by jwesich** [miguelgrinberg/flasky#39]
Hello-everything(minus the smtp error for mail) was working until Chapter 11. It is not pulling the HTML for the blog post box, for some reason. I've reset and updated database, et al, but have as yet to get it to come up. I also checked line my line the code as in the book and everything is there. I did skip forward and implemented the forgery.py examples and it worked, but the box below my username still does not show. Please advise. Thank you!

![flasky](https://cloud.githubusercontent.com/assets/9407106/7109810/bc385474-e16b-11e4-8ec3-5941c03b8307.png)

**Comment by miguelgrinberg** [comment]
@jwesich the application uses roles to know what a user can and cannot do. Check in your database what role is stored in your user and see if it includes the WRITE_ARTICLES role, I bet it doesn't.

**Comment by jwesich** [comment]
Here are my settings in model.py. Also and checked the db setting through python shell and both jwesich and jwesich@gmail are listed as admin. I went through everything again. Am I wrong in assuming Admin, by default, should have write-article permissions? Thank you!
class Permission:
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENTS = 0x08
    ADMINISTER = 0x80


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.FOLLOW |
                     Permission.COMMENT |
                     Permission.WRITE_ARTICLES, True),
            'Moderator': (Permission.FOLLOW |
                          Permission.COMMENT |
                          Permission.WRITE_ARTICLES |
                          Permission.MODERATE_COMMENTS, False),
            'Administrator': (0xff, False)
        }


Here is the db query from command line: >>> User.query.filter_by(role=admin_role).all()
[<User u'jwesisch'>, <User u'jwesich@gmail.com'>]

**Comment by jwesich** [comment]
>>> User.query.filter_by(role=admin_role).all()
[<User u'jwesisch'>, <User u'jwesich@gmail.com'>]

**Comment by jwesich** [comment]
I'll start from scratch in a new virtual environment. I very well could have screwed up my database in the beginning.

**Comment by miguelgrinberg** [comment]
You don't need to recreate your virtualenv, just your database.

**Comment by Kopei** [comment]
Hi, @miguelgrinberg, I have also met this problem. User do not have permission to post..
I think I have insert_roles()

I do not know, maybe User model did not init properly.

@jwesich Have you fix the issue?

**Comment by miguelgrinberg** [comment]
@Kopei the `insert_roles()` function just creates the roles, it does not assign roles to users. If you have users in your database that were created before you added the roles, then those will not have any permissions (their role bits will all be set to zero).

**Comment by Kopei** [comment]
@miguelgrinberg Thank for your reply. As you said, roles will assign after insert_roles() and User.role shoud init at register if I am right. It works sometimes, but sometimes not. The following pic is my sqlite.
![qq 20150429223837](https://cloud.githubusercontent.com/assets/6974344/7393509/da20dbfc-eec0-11e4-8ec2-db2ff497ec6b.png)
 That confuses me!

**Comment by miguelgrinberg** [comment]
Did you recreate your database after adding roles?

**Comment by leonardocintra** [comment]
I'm having the same problem 

![image](https://cloud.githubusercontent.com/assets/5832193/10237701/b8734004-688b-11e5-8c6f-d2d8d3c13020.png)

**Comment by keithalpichi** [comment]
Have you guys recreated the DB like Miguel said?
After Example 9-3 bottom of p. 113

    (venv) $ python manage.py shell #enter shell
    >>> Role.insert_roles()
    >>> Role.query.all() #should yield the roles below
    [<Role u'Administrator'>, <Role u'User'>, <Role u'Moderator'>]

**Comment by xinqiu** [comment]
Is there any methods to fix it when create a new database?

**Comment by miguelgrinberg** [comment]
@xinqiu you can do it like @keithalpichi suggested two comments above.

Later in the deployment section I show you how you can automate all the deployment tasks under a single command, so that you don't have to remember all the tasks that need to be run to set up the application.

**Comment by xinqiu** [comment]
Thank you for helping me.

**Comment by chinadufx** [comment]
because you don't have wirte right! At the same time, you don't build the role. you can do this:
~python manage.py shell
>>>Role.insert_roles()
then you can rebuild user,you can see the form

**Comment by chinadufx** [comment]
because you don't have wirte right! At the same time, you don't build the role. you can do this:
~python manage.py shell
~Role.insert_roles()
then you can rebuild user,you can see the form
