### ISSUE TITLE
"TypeError: unsupported operand type(s) for &: 'int' and 'Undefined' is prompted".

### ISSUE THREAD

**Issue by Chen2358** [miguelgrinberg/flasky#391]
When the has_permission function in modes is called, "TypeError: unsupported operand type(s) for &: 'int' and 'Undefined' is prompted".

**Comment by Chen2358** [comment]
Any help?

**Comment by miguelgrinberg** [comment]
Show me a full stack trace of the error please.

**Comment by Chen2358** [comment]
I solved it when I replaced the '&' in the has_permission function with 'and'，Thank you for your reply
