### ISSUE TITLE
How can I achieve this structure?

### ISSUE THREAD

**Issue by acodercat** [miguelgrinberg/flasky#397]
How can I achieve this structure?
<img width="249" alt="wx20181128-172947 2x" src="https://user-images.githubusercontent.com/16076835/49143545-37844900-f336-11e8-80b3-4b22f77ad754.png">

**Comment by miguelgrinberg** [comment]
I don't understand what you are asking. If you like that structure, just use it, Flask doesn't care what structure you use, just write your app as in your picture.

**Comment by acodercat** [comment]
Thankss, I want to know how to write _init_. py in my app directory.

**Comment by acodercat** [comment]
please

**Comment by miguelgrinberg** [comment]
Here is a working example you can use as a start: https://github.com/miguelgrinberg/flasky/blob/master/app/__init__.py
