### ISSUE TITLE
auth Blueprint has no access to Permission class

### ISSUE THREAD

**Issue by tmeissner** [miguelgrinberg/flasky#399]
How does the auth templates have access to Permissions class?

I get errors when the auth templates try to extend the base.html which use the Permissions class.

```
...
flasky    |   File "/home/flasky/app/templates/auth/unconfirmed.html", line 1, in top-level template code
flasky    |     {% extends "base.html" %}
flasky    |   File "/home/flasky/app/templates/base.html", line 1, in top-level template code
flasky    |     {% extends "bootstrap/base.html" %}
flasky    |   File "/home/flasky/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
flasky    |     {% block doc -%}
flasky    |   File "/home/flasky/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
flasky    |     {%- block html %}
flasky    |   File "/home/flasky/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
flasky    |     {% block body -%}
flasky    |   File "/home/flasky/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
flasky    |     {% block navbar %}
flasky    |   File "/home/flasky/app/templates/base.html", line 33, in block "navbar"
flasky    |     {% if current_user.is_authenticated and current_user.can(Permission.MODERATE) %}
flasky    |   File "/home/flasky/venv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
flasky    |     return getattr(obj, attribute)
flasky    | jinja2.exceptions.UndefinedError: 'Permission' is undefined
```

After I added a similar context processor to the `auth/__init__.py` like in the `main/__init__.py` the error disappears:

```python
from ..models import Permission

@auth.context_processor
def inject_permissions():
    return dict(Permission=Permission)
```

**Comment by miguelgrinberg** [comment]
A context processor is used to add variables to the template context. Without that you can't use any custom classes in your templates.

**Comment by tmeissner** [comment]
Okay, I assumed that. The problem is, no such context processor is defined in auth constructor before I added it by myself. Only the main constructor had such a context processor in the flasky app from this git repository.

**Comment by miguelgrinberg** [comment]
I don't understand what you mean by "auth constructor" and "main constructor". I assume you meant "blueprints"?

Context processors can be defined at the application level, and then they apply to all blueprints. The one that I defined is in the main blueprint, but is defined with the `app_context_processor` decorator, not the `context_processor` one. See https://github.com/miguelgrinberg/flasky/blob/master/app/main/__init__.py#L9-L11.

**Comment by tmeissner** [comment]
Oh. That is it. I forgot the change the context processor in the `main/__init__.py` from `context_processor` to `app_context_processor`. My fault. Thanks for your help.
