### ISSUE TITLE
RuntimeError: No application found. 

### ISSUE THREAD

**Issue by moritzxbe** [miguelgrinberg/flasky#402]
Hello,

I'm trying to get choices from database for my Form but get an error:
"RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/."

Do you know what happens here?

I worked with the code of your book till chapter 8. now I tried to do it like they have done it in my "forms.py" script.

https://stackoverflow.com/questions/35314102/get-choices-from-a-database-query-in-wtforms-and-flask-sqlalchemy

thanks mate

**Comment by moritzxbe** [comment]
The code works fine till I write the line Users.query.all() in my forms.py. Then I get this error message.
"RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/."
I have imported all models (from ..models import *).

**Comment by miguelgrinberg** [comment]
Yes, the problem is that you can use the database in the global scope of the application, because that code runs when the module is parsed. That early there is no application and no application context, so Flask-SQLAlchemy does not have access to the database configuration.

**Comment by moritzxbe** [comment]
thanks for your support! What can I do to get this running? I can see that flasky is also importing User and Roles in forms.py

**Comment by moritzxbe** [comment]
Hi, thanks for advise. I found a solution for this error. I moved the query to the views.py script and added the choices from there `form.user_items.choices = choices`. Thank you for your support!
