### ISSUE TITLE
I set "FLASKY_ADMIN" env var, But registered user have no role "Administrator", why?

### ISSUE THREAD

**Issue by carrison** [miguelgrinberg/flasky#405]
echo $FLASKY_ADMIN^M
susan@xxx.com^M
>>>u = User.query.filter_by(username='susan').first()^M
>>>u.email^M
'susan@xxx.com'^M
>>>u.is_administrator()^M
>>>False^M

**Comment by carrison** [comment]
and have no "What's on your mind?" form shown on homepage, why?

**Comment by carrison** [comment]
![flasky01](https://user-images.githubusercontent.com/24284212/51733562-92f25f00-2079-11e9-9940-d4020da2c43b.png)

**Comment by carrison** [comment]
yes, I set 
export FLASK_APP=flasky.py
export FLASKY_ADMIN=susan@xxx.com
in ~/.profile and it works in term window, My linux is ubuntu 18.10
I received and activated confirmed mail, But I found the admin user have no role assigned, Its role is None.

**Comment by miguelgrinberg** [comment]
Did you initialize the roles table?

**Comment by carrison** [comment]
how to nitialize the roles table? Do it in flask shell ?>>> Role().insert_roles()
I just git clone your code, then
- set env vars and source them
- rm -rf folder "migrations"
- flask db init; flask db migrate; flask db upgrade
- flask run

**Comment by miguelgrinberg** [comment]
@carrison Are you following this project from the book? Not sure from where you obtained those instructions, but they are not in the book.

**Comment by carrison** [comment]
I follow microblog project on your blog first, then found flasky project :-)

**Comment by carrison** [comment]
your project is absolutely awesome!

**Comment by miguelgrinberg** [comment]
This project is tied to the book, and is designed to be worked on in very specific steps, which are in the commits. You can try running `flask deploy` if you want to give it a shot, but really, you'll make the most if you get the book.

**Comment by carrison** [comment]
it works now. After steps below applied:
>>> r = Role.query.filter_by(name='Administrator').first()
>>> r
<Role 'Administrator'>
>>> u.role = r
>>> u.role
<Role 'Administrator'>
>>> db.session.commit()
Thank you, Miguel.

**Comment by ogahozy** [comment]
After push the app to heroku hobby. i am am trying to insert roles using the heroku run command:
$ Role.insert_roles()
but i got this error:
bash: -c  line 1;:syntax error: unexcepted end of file. 
pls how to activate the roles for admin miderator and user

**Comment by miguelgrinberg** [comment]
@ogahozy I think you are trying to run a python command, but `heroku run` is for scripts. Wrap your Python in a python script, then run `heroku python your_script.py`, for example. Or add a custom `flask` command that runs what you want. Or add this to the `flask deploy` command if you have it in your project.
