### ISSUE TITLE
Question in 9a: the test_****_role function failed

### ISSUE THREAD

**Issue by TianHongZXY** [miguelgrinberg/flasky#408]
When I run test, it reports error as the picture shows:
![qq 20190221234859](https://user-images.githubusercontent.com/39355004/53181822-46c41b80-3633-11e9-8237-e119ff29a465.jpg)

but when I copy the code in the function to run in the flask shell, it's just ok as follow shows:
![qq 20190221234722](https://user-images.githubusercontent.com/39355004/53181851-50e61a00-3633-11e9-8c2f-a1c5ca1392b6.jpg)
 I have no idea why. Please help me. Thank you!

**Comment by miguelgrinberg** [comment]
Is this with code cloned from this repository, or did you type it yourself? Have you done a comparison against my code if the latter? I can't really tell what's wrong just from seeing the test output.

**Comment by TianHongZXY** [comment]
Oh, after comparing every single line, i found the cause. I didn't write the `Role.insert_roles()` after `db.create_all()` in the test_user_model.py, thank you!
