### ISSUE TITLE
Image not appearing on post

### ISSUE THREAD

**Issue by ogahozy** [miguelgrinberg/flasky#409]
I got cloned the flasky tutorial and git  checkout 11h. When I type this link -> img src="/static/logo.png with other text. I saw the image  and the text at the pagedown  view. But when I click submit. I do not see the image on the post but only the text. What do I do make the image appear together with the text.

**Comment by miguelgrinberg** [comment]
The `<img>` tag is not allowed as a valid tag. See https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L300-L302. You can add it to the list so that it isn't filtered.

**Comment by ogahozy** [comment]
After adding the <img>:

allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p','img']

Result remains the same

This is the write up and the pagedown

![screenshot from 2019-02-27 18-05-18](https://user-images.githubusercontent.com/22278698/53508976-25dc4a00-3abb-11e9-852d-0b5a983b672f.png)

this is the post result
![ppp](https://user-images.githubusercontent.com/22278698/53508948-16f59780-3abb-11e9-8333-1005d0c44a84.png)

**Comment by miguelgrinberg** [comment]
Can you check what was stored in your database?

**Comment by ogahozy** [comment]
this is the content of the database
![try](https://user-images.githubusercontent.com/22278698/53522098-ff79d700-3ad9-11e9-8aa2-7fd02c0e227d.png)

**Comment by miguelgrinberg** [comment]
Okay, the issue is that bleach also needs a white list for attributes. You can see an example specifically to allow images in the documentation: https://bleach.readthedocs.io/en/latest/clean.html#as-a-dict.

You would need to also add a `attributes={'img': ['src']}` argument to the `bleach.clean()` call.

**Comment by ogahozy** [comment]
Here is the result, Up and running
def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p','img']
        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, attributes={'img':['src']},strip=True))

![sec](https://user-images.githubusercontent.com/22278698/53555339-0b00e880-3b42-11e9-8693-57d3edbc62f9.png)

THANKS A LOT

**Comment by miguelgrinberg** [comment]
Great. And thank you for updating the post with your final solution for others to benefit as well.
