### ISSUE TITLE
"sqlalchemy.exc.OperationalError"

### ISSUE THREAD

**Issue by qasimalbaqali** [miguelgrinberg/flasky#41]
So I am reading the book and coding and coding it at the same time and look at the clones sometimes. So now I'm creating a user to try out the current_user.is_authenticated() in chapter 8 to see if does it shows that I am logged in or not. When I try to sign it with the user that I have created through the shell i get the following error 

**sqlalchemy.exc.OperationalError**

OperationalError: (OperationalError) no such table: users u'SELECT users.id AS users_id, users.email AS users_email, users.username AS users_username, users.password_hash AS users_password_hash, users.role_id AS users_role_id \nFROM users \nWHERE users.email = ?\n LIMIT ? OFFSET ?' (u'name@example.com', 1, 0)

and this error from the traceback

File "/home/cycrups/Desktop/Flask/asghaal/app/auth/views.py", line 11, in login

user = User.query.filter_by(email=form.email.data).first()

Any idea where I might went wrong?

**Comment by miguelgrinberg** [comment]
@qasimalbaqali you probably missed the fact that after the restructure in chapter 7 the name of the database has changed. Post chapter 7 the application has multiple configurations, and each configuration uses a different database. So you are probably using an empty database that has no tables. If you run `manage.py db upgrade` you should get the tables added to your database.

**Comment by qasimalbaqali** [comment]
@miguelgrinberg I already ran the upgrade for the databases. I usually do it after every other change in the code. I ran it one more time. I have two databases **data.sqlite** and **data-dev.sqlite** , I guess this mean the upgrade for the database has worked. I tried again creating a new user and when I commit I get 

*
OperationalError: (OperationalError) no such table: users u'INSERT INTO users (email, username, password_hash, role_id) VALUES (?, ?, ?, ?)' ('gasmee811@msn.com', 'gasmee811', 'pbkdf2:sha1:1000$rVS4pyEj$13ac4a0ec69f175807cfc91aa56fa1742e7340e8', None)
*
I guess this means the tables aren't added to my database yet? I am a newbie with Flask so I appreciate all the help you can give me :).

PS. You're book is amazing, I have learned a lot with from it and I am just half way through it!

**Comment by miguelgrinberg** [comment]
Do you have the `sqlite3` command line utility? Try the following in a shell:

    $ sqlite3 data-dev.sqlite
    sqlite> .schema

The output should be the tables that exist in the database. See if you have a `users` table or not.

**Comment by qasimalbaqali** [comment]
All I got was 
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL
);

I deleted the database and have upgraded again, so a new one was created and still the same problem. I am afraid that it's just a small problem that I have while typing the code and have made a mistake. The best solution for me if I would just replace each of the files with the latest checkout git and see which would fix it and then see what went wrong. I appreciate your help, I am just afraid of taking too much of your time with troubleshooting my problem.

Thanks again.

**Comment by miguelgrinberg** [comment]
Check your migration scripts, compare them against those in this repository. My guess is that your migrations aren't doing anything.

**Comment by qasimalbaqali** [comment]
@miguelgrinberg Okay so I have removed the migration script and did it again and now it's working fine! Thank you.

**Comment by jedidiahasare** [comment]
The problem is with .py files in the migrations/versions folder. If its empty, then you got a problem
