### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [miguelgrinberg/flasky#413]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by miguelgrinberg** [comment]
There is no CI for this project. The commits in this repo are aligned with my book, this isn't your typical github project that is constantly improved.

**Comment by gustavosizilio** [comment]
Oh, Thank you for your time!
