### ISSUE TITLE
sqlalchemy.exc.OperationError: near "DROP": syntax error

### ISSUE THREAD

**Issue by TianHongZXY** [miguelgrinberg/flasky#414]
Today when I delete one column of users table in the models, then I run `flask db migrate`, it works. But when I run `flask db upgrade`, it reports error like the picture shows. I search on the Internet , some people says `SQLite` doesn't support `drop`, but just several days ago, I still can delete one column and run the `flask db upgrade`  just right. I don't know what causes this. I use `flask-sqlalchemy 2.3.2` and `alembic 1.0.8`.
![微信图片_20190324160126](https://user-images.githubusercontent.com/39355004/54876656-5743fd80-4e4e-11e9-8fb2-39bc249456eb.png)

**Comment by miguelgrinberg** [comment]
It's true, SQLite does not drop columns. If you think that worked for you previously, then either you are mistaken, or the project that you were using is configured with batch migrations, which basically copy the entire table to a new table to be able to delete a column. Here is an issue where batch migrations are discussed: https://github.com/miguelgrinberg/Flask-Migrate/issues/61

**Comment by TianHongZXY** [comment]
I got it, thank you.

**Comment by SebastianOpiyo** [comment]
Facing the same problem with, hope to have it solved soon.
