### ISSUE TITLE
Bug Found in the Test case of checkout 8a.

### ISSUE THREAD

**Issue by Great-Li-Xin** [miguelgrinberg/flasky#415]
Directly calling the property instead of calling the function would break the preciseness of the code.

> Fix here 👇
@@ class UserModelTestCase(unittest.TestCase):  
```
def test_no_password_getter(self):
    u = User(password='cat')
    with self.assertRaises(AttributeError)
    > -     u.password
    > +     u.password()

def test_password_verification(self):
    u = User(password='cat')
```

**Comment by miguelgrinberg** [comment]
Can you explain what is the problem with the current test? `password` is a property, you do not need parenthesis when you refer to it.

**Comment by Great-Li-Xin** [comment]
@miguelgrinberg 
Broadly speaking, your statement is acceptable. Defining a property with `@property` is legal in python. However, in most cases, we use automation tools to format, auto-complete and even review the code. Thus I prefer calling the `@property` defined 'property' with parenthesis.

In a nutshell, Thank you for your help.
