### ISSUE TITLE
win10 pycharm can't run flask test on Chapter 7

### ISSUE THREAD

**Issue by XingDongZhe** [miguelgrinberg/flasky#417]
File "C:\Users\F1334694\Desktop\python\flasky\app\__init__.py", line 18, in create_app
    config[config_name].init_app(app)
KeyError: <flask.cli.ScriptInfo object at 0x05548D50>

i can't figure out why this happened. i have set the FLASK_APP=flasky.py.
but when i set FLASK_APP=flasky.py, it worked.
pls help me solve this problem,thx

**Comment by miguelgrinberg** [comment]
Does it work from the command line?

**Comment by XingDongZhe** [comment]
when work from the command line, it need set FLASK_APP=flasky.py first

**Comment by miguelgrinberg** [comment]
That is also required for PyCharm.

**Comment by XingDongZhe** [comment]
thanks

**Comment by Washington-DC** [comment]
Thank you

**Comment by nirob07** [comment]
KeyError: <flask.cli.ScriptInfo object at 0x7f35046f8d30>
only problem solved for FLASK_APP=flasky.py or FLASK_APP=wsgi.py  in config file not working if i use app.py or anything else

**Comment by eduardohangel2018** [comment]
Hello guys, 
I had an error similar to the one reported. 
When i tried to access flask shell typing: 'flask shell' after i declared 'FLASK_APP=main.py' in my terminal i had the same error as follow:
File "/Users/eduardorangel/Desktop/PythonProjects/SMSCode-generate_project/app/__init__.py", line 22, in create_app
    app.config.from_object(config[config_name])
KeyError: <flask.cli.ScriptInfo object at 0x7f91d72c0310>

Follow is my code:
https://github.com/eduardohangel2018/SMSCode.git

Please, can anyone help me?

**Comment by Alcord** [comment]
> KeyError: <flask.cli.ScriptInfo object at 0x7f91d72c0310>

Maybe you are doing the exercise locally and no in an env.
I exported the FLASK_APP environment variable. I used this:
$ export FLASK_APP=flasky.py
