### ISSUE TITLE
email authentication

### ISSUE THREAD

**Issue by Thiringai** [miguelgrinberg/flasky#418]

**Comment by Thiringai** [comment]
i just started working with python and flask, am trying to confirm new users, but i keep getting following...the confirmation link is invalid or expired... what could be the issue

**Comment by miguelgrinberg** [comment]
It's impossible for me to know. There's lots of things that can be wrong. Do you get the problem when you use this application as well?

**Comment by 1000sprites** [comment]
\app\models.py：
1.def generate_confirmation_token(self, expiration=3600)：s.dumps({'confirm': self.id}).decode('utf-8')
2.def confirm(self, token)：data = s.loads(token)
