### ISSUE TITLE
About tests/test_client.py line 52

### ISSUE THREAD

**Issue by polar9527** [miguelgrinberg/flasky#421]
I'm confused by line 52 "user.confirm(token) " in tests/test_client.py.  I think there is no need to call user.confirm(token) again in line 52, because after you called "self.client.get('/auth/confirm/{}'.format(token),follow_redirects=True)" in line 51, the server side had already call user.confirm(token) in "def  confirm(token)"  of  auth/view.py . 
Am I right?
`# send a confirmation token`
`user = User.query.filter_by(email='john@example.com').first()`
`token = user.generate_confirmation_token()`
`response = self.client.get('/auth/confirm/{}'.format(token), follow_redirects=True)`
### `# why confirm again here ?`
`user.confirm(token)`
`self.assertEqual(response.status_code, 200)`
`self.assertTrue(b'You have confirmed your account' in response.data)`

**Comment by miguelgrinberg** [comment]
Yes, I believe you are right, that confirm call in that test doesn't do anything.
