### ISSUE TITLE
About function get_api_headers() in tests/test_api.py

### ISSUE THREAD

**Issue by polar9527** [miguelgrinberg/flasky#422]
`    def get_api_headers(self, username, password):`
`        return {`
`           'Authorization': 'Basic ' + b64encode(`
`              (username + ':' + password).encode('utf-8')).decode('utf-8'),`
`              ......`
`          }`

I think it maybe better like this for clarity
` from werkzeug.http import byte,s_to_wsgi, wsgi_to_bytes`
` bytes_to_wsgi(b64encode(wsgi_to_bytes(username + ':' + password)))`

because codes in function parse_authorization_header() of werkzeug.http use bytes_to_wsgi 
 and wsgi_to_bytes for encoding and  decoding.

**Comment by miguelgrinberg** [comment]
I'm not sure what benefit do you see in using the Werkzeug function, but I don't think what I'm doing is wrong, in fact it might be even better from an I18n point of view since it uses utf-8 encoding and not latin1 as Werkzeug does.
