### ISSUE TITLE
Running Flask server using run_simple instead of app.run

### ISSUE THREAD

**Issue by dongsibo** [miguelgrinberg/flasky#423]
I know that it has been brought up before that attempting to run a server in newer versions of Flask using `app.run` in places like the Selenium test case and in the `flask profile` command results in a warning that `app.run` will be silently ignored.

What has worked for me is to instead use Werkzeug's `run_simple` function to start the server as indicated [here](https://stackoverflow.com/a/52299918) and [here in the documentation](https://werkzeug.palletsprojects.com/en/0.15.x/serving/).

Here is what I have in `flasky.py`:
```{py}
# ...
from werkzeug.serving import run_simple
# ...
@app.cli.command()
@click.option('-h', '--host', default='127.0.0.1',
              help='The interface to bind to.')
@click.option('-p', '--port', default=5000,
              help='The port to bind to.')
@click.option('--length', default=25,
              help='Number of functions to include in the profiler report.')
@click.option('--profile-dir', default=None,
              help='Directory where profiler data files are saved.')
def profile(host, port, length, profile_dir):
    """
    Start the application under the code profiler.
    """
    from werkzeug.contrib.profiler import ProfilerMiddleware
    app.wsgi_app = ProfilerMiddleware(app.wsgi_app, restrictions=[length],
                                      profile_dir=profile_dir)
    run_simple(host, port, app, use_debugger=False)  # use run_simple instead of app.run()
```

**Comment by miguelgrinberg** [comment]
Thanks, this is a good workaround. There is a bug logged with Flask regarding this problem that I hope one day will be fixed.

**Comment by invegat** [comment]
werkzeug locks my console after 10 loops, it is a virus
