### ISSUE TITLE
alembic not generate changes after add a column

### ISSUE THREAD

**Issue by huajianjiang** [miguelgrinberg/flasky#424]
After autogenerate first  'add contracts table' migration script and upgrade head , add a column in contact table model and  autogenerate again , almbic generate ' create table ' script again, not 'add column' statement.  
![1](https://user-images.githubusercontent.com/12984573/57570307-02c30480-7433-11e9-99cb-5e2637a0a3ee.png)
![2](https://user-images.githubusercontent.com/12984573/57570308-02c30480-7433-11e9-96e6-26bda7e98fd8.png)
![3](https://user-images.githubusercontent.com/12984573/57570309-035b9b00-7433-11e9-8e30-579dedfc52aa.png)

**Comment by miguelgrinberg** [comment]
Let me see the output of all the commands that you are running, including the `migrate` and `upgrade`.

**Comment by huajianjiang** [comment]
@miguelgrinberg Hi, in order to describe this problem clearly, I replay this problem.
![env py](https://user-images.githubusercontent.com/12984573/57570732-d1006c80-7437-11e9-810d-4aa0c0a0aaaf.png)
![alembic ini](https://user-images.githubusercontent.com/12984573/57570733-d1990300-7437-11e9-9e14-289a62cab9a2.png)
![first_migration_and_upgrade](https://user-images.githubusercontent.com/12984573/57570734-d2ca3000-7437-11e9-8486-9c4d4b52db56.png)
![second_migration](https://user-images.githubusercontent.com/12984573/57570736-d3fb5d00-7437-11e9-808a-3f75d04dda90.png)

**Comment by huajianjiang** [comment]
@miguelgrinberg 
Hello: 
Finally  I found that Alembic seems not detect changes because of  8.0 MySQL , and I don't konwn how to solve the problem.

**Comment by huajianjiang** [comment]
@miguelgrinberg 
Thanks for your reply.
After I research, I found the cause of the problem is the DBAPI driver(mysql-connector) that not support new MySQL 8.0 and not raise a exception. 
It make me crazy. my god!

**Comment by miguelgrinberg** [comment]
Glad you figured it out!

**Comment by zhipengfan97** [comment]
@huajianjiang Hi, really thanks, I just met the same problem. I have been manually upgrading the db(withou autogenrate) for several months until I find this article today. I found the alembic don't detect the db change as well, but how do you know the problem comes from the DBAPI driver? I just curious the process of analyzing this problem, not sure you remember it or not, thank
