### ISSUE TITLE
Login Testing

### ISSUE THREAD

**Issue by fondxy** [miguelgrinberg/flasky#425]
After registing a new user using flask shell, I always got a "Email already registered." message in my browser when I test the login fuction.
`(venv) $ flask shell
>>> u = User(email='john@example.com', username='john', password='cat')
>>> db.session.add(u)
>>> db.session.commit()`

**Comment by miguelgrinberg** [comment]
Are you trying to login or to register a new user? If the user is already in the database, the login function should work, and the register user function should fail, since the user is already registered.
