### ISSUE TITLE
Running test_api/test_no_auth,return 403?

### ISSUE THREAD

**Issue by zhengjiani** [miguelgrinberg/flasky#426]
Hi , When I trying this testcase:

```
 def test_no_auth(self):
        response = self.client.get('/api/v1/posts/',content_type='application/json')
        self.assertEqual(response.status_code,401)
```

The response status_code is 403
```
Traceback (most recent call last):
  File "/var/www/microblog/microblog/tests/test_api.py", line 43, in test_no_auth
    self.assertEqual(response.status_code,401)
assertionError: 403 != 401

```
I guess it is already  authenticated?Thx.

**Comment by miguelgrinberg** [comment]
Are you using an exact copy of my code? The 403 status code is for users that are logged in but try to do an operation they don't have permission to do. A request that does not have authentication credentials should return 401.
