### ISSUE TITLE
debug the flasky

### ISSUE THREAD

**Issue by MammadTavakoli** [miguelgrinberg/flasky#427]
when I set the debug True the it dose not work. how can I correct this problem?

**Comment by miguelgrinberg** [comment]
Can you be more specific? What did you change, and how it did not work? Include screenshots if necessary.

**Comment by MammadTavakoli** [comment]
in the flasky.py, in the profile function ; and in  app/__init__.py , in the create_app function. but they don't work.

**Comment by Fumitus** [comment]
I have the same problem with DEBUG mode. With FLASK_DEBUG=1 I get a message:

```
(venv) D:\Andriaus\personal_coding_projects\Flask_web\flasky\app>flask run
 * Serving Flask app "flasky.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
d:\<my directory>\flask_web\flasky\app\venv\scripts\python.exe: Error while finding module specification for 'flask.__main__' (ImportError: cannot import name 'Flask' from 'flask' (d:\andriaus\personal_coding_projects\flask_web\flasky\app\venv\lib\s
ite-packages\flask\__init__.py))
```

**Comment by miguelgrinberg** [comment]
@Fumitus probably related to your virtualenv and your current directory being inside the app package, instead of outside. Recreate your virtualenv in the Flasky directory, and then start the app from there.
