### ISSUE TITLE
Unable to add about_me and last_seen field in chapter 6 of The Flask Mega Tutorial.

### ISSUE THREAD

**Issue by codewithyogi** [miguelgrinberg/flasky#428]
Hello Miguel. Thank You for the tutorials. 

I was following chapter 6. I created two new fields and executed 
"flask db migrate -m "some text here" and "flask db upgrade"  commands. All was well.

But when I restarted my server and reload my page. I got this error.

```
sqlalchemy.exc.OperationalError

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.about_me
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('idreamofghouls', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

And I seriously don't know how to counter it. I did "export FLASK_APP=appname" and "export FLASK_DEBUG=1" as well. 

Please help me Miguel. I can't seem to find the solution anywhere and I'm still a beginner.

**Comment by miguelgrinberg** [comment]
You need to check the migration script. It seems it did not include the addition of the `about_me` field for some reason.

**Comment by codewithyogi** [comment]
You are right. It isn't allowing these two fields for some reason. When I removed both these fields, my application started working again. I'm stuck and confused.

**Comment by miguelgrinberg** [comment]
Well, try generating the migration again. If you added those columns to your model, they should be found by Alembic.

**Comment by codewithyogi** [comment]
Not only that. When I open Sqlite3 terminal and type .schema nothing happends. No output. Also I delete my migrations folder and database file and recreated the migrations, but this time with both the fields. It still showed me the same error.

**Comment by miguelgrinberg** [comment]
If you want me to help you troubleshoot this I need to see your model definitions and your generated migration scripts. Please reopen if you can provide those.
