### ISSUE TITLE
Tutorial on deploying flasky to Amazon Elastic Beanstalk?

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#43]
Hi Miguel,

I enjoyed your book and thanks a lot. We are trying to deploy flasky to EB by following the tutorial found at https://medium.com/@rodkey/deploying-a-flask-application-on-aws-a72daba6bb80 but have lots of trouble. Are you planning to write a tutorial on deploying flasky to Amazon Elastic Beanstalk? I really like your writing style. 

Thanks!

Harry

**Comment by miguelgrinberg** [comment]
I wasn't planning on writing about that. I have written about deploying Flask on Rackspace a while ago, here are the scripts I used: https://gist.github.com/miguelgrinberg/d9f1fcafc012f3fb3f03. The first of the two scripts might give you some ideas, this is the script that runs in the instance to set everything up.

The article you referenced seems fairly complete, what is specifically the issue with AWS?

**Comment by harrywang** [comment]
Thanks, Miguel. The tutorial using $python application.py and Flasky uses $python manage.py runserver, Amazon EB default WSGIPath is application.py. I have no idea how to setup EB to run $python manage.py runserver

**Comment by miguelgrinberg** [comment]
@harrywang oh, actually I missed the fact that they use `manage.py runserver`. That's not a good way to deploy, that uses the development web server, which has really bad performance. See the script I referenced above. For my deployment I use nginx+gunicorn, which is a production ready stack.

**Comment by harrywang** [comment]
@miguelgrinberg Thanks! I will study your script and hope to consult you if we run into trouble.
