### ISSUE TITLE
current_app.logger.info streamhandler

### ISSUE THREAD

**Issue by smuratk** [miguelgrinberg/flasky#430]
Dear Miguel,

Trying log info but can not do it.
@main.route('/', methods=['GET', 'POST'])
def index():
    current_app.logger.info('infoo')
    current_app.logger.warning('warningg')

warning Works but not info. I think info should also work since streamhandler level is info.
Thanks in advance

**Comment by miguelgrinberg** [comment]
You should set the level also on the logger, not just the handler.
