### ISSUE TITLE
Why not use super() in config.py?

### ISSUE THREAD

**Issue by Orenoid** [miguelgrinberg/flasky#431]
In config.py, the "init_app" method is invoked with the parent class name. Why not just use super() here? It seems to work too.

**Comment by miguelgrinberg** [comment]
init_app is a class method. While the `super()` function does work for class methods, it is more commonly used for regular methods. But you are correct, it's not a problem to use super in this situation.

**Comment by Orenoid** [comment]
Got it, thanks!
