### ISSUE TITLE
How to save variables between requests?

### ISSUE THREAD

**Issue by lilianabrandao** [miguelgrinberg/flasky#441]
Hi,
With the help of your book (a life-saver!), I’m developing a Web App.  However, I got stuck in an issue and I haven’t been able to overcome it.

When the Client makes a request, the Server calls a customized function to output 2 results that are stored in 2 local variables. I need to save one of those variables between requests (in order to reuse it in a new request). How can I do it?

I’ve tried to use the Session object but without success. I get the error message: 

`TypeError: Object of type 'rectangle' is not JSON serializable`

Can you help me?
Thanks

**Comment by miguelgrinberg** [comment]
The session can only hold objects that are compatible with JSON, so basically dictionaries, lists, strings, booleans or numbers. You need to add methods in your `rectangle` class to convert to one of these types, put that in the session, then convert back into the object when you retrieve it.

**Comment by lilianabrandao** [comment]
Thank you Miguel!
