### ISSUE TITLE
multiple redirects

### ISSUE THREAD

**Issue by amirhb9472** [miguelgrinberg/flasky#442]
hey 
I'm looking for a solution on multiple redirects.
here is what I mean: suppose i have a form with multi fields which are for example some courses like programing, algorithm , ...
user can select some of these courses and then some same questions should be asked about each of these selected courses.
i have put these questions in a template and i want to redirect to this template for each of the courses. (i use the course name as a parameter for the function call)
here is my stupid solution which will never work:

for course in courses:
      return redirect(url_for('questions', course=course))

any suggestions to do this?

**Comment by miguelgrinberg** [comment]
Keep the list of courses in the user session as a list. Redirect to the first course in the list, and as soon as you land on the redirected route remove the first item, so that the next time you redirect you go to the second course and so on.
