### ISSUE TITLE
Question about this line 'def on_changed_body(target, value, oldvalue, initiator)'

### ISSUE THREAD

**Issue by Tankruslan** [miguelgrinberg/flasky#444]
Hello Miguel. I'm learning Flask by your wonderful book. I read until the middle and everything was clear. But in chapter 11 I had a question about this line 
`def on_changed_body(target, value, oldvalue, initiator)`
I really don’t understand where (target, value, oldvalue, initiator) arguments come from. How this method gets these arguments. And why do we need oldvalue and initiator if we don't use them?
Please, any help.

**Comment by miguelgrinberg** [comment]
This is actually dictated by SQLAlchemy. The arguments are in the [documentation](https://docs.sqlalchemy.org/en/13/orm/events.html#sqlalchemy.orm.events.AttributeEvents.set).

**Comment by Tankruslan** [comment]
Thanks a lot. Now everything is clear)
