### ISSUE TITLE
AttributeError: 'Role' object has no attribute 'has_permissions'

### ISSUE THREAD

**Issue by DimitrisLK** [miguelgrinberg/flasky#447]
![image](https://user-images.githubusercontent.com/32920285/67884785-141ddb80-fb4f-11e9-831e-a18dd39c5147.png)

I'm trying to insert the roles in the table via shell and I'm met with this error. 
Checking with Google was met with a probable indentation error but I checked extensively and it was not it. 
Code is here: https://pastebin.com/xsVEhtcn
Any help?

**Comment by miguelgrinberg** [comment]
The method is called `has_permission`, in singular. In this particular usage you entered `has_permissions` in plural.

**Comment by DimitrisLK** [comment]
Damn, I completely missed that.
Thanks for your quick reply!

**Comment by simanacci** [comment]
@miguelgrinberg Other than having permissions as strings, Is their a work around or a similar alternative when using bits as permissions in case you have more than 63 permissions?
