### ISSUE TITLE
Can’t connect to container on localhost

### ISSUE THREAD

**Issue by vital1312** [miguelgrinberg/flasky#448]
I cannot access flasky app on localhost:8000 or even on http://192.168.99.100:5000/. Containers are running, but in my browser I get this error:
_This site can’t be reached 
localhost  refused to connect._

Containers:
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                  PORTS                    NAMES
acc3dbe4dbaf        flasky_flasky            "./boot.sh"              2 minutes ago       Up 2 minutes            0.0.0.0:8000->5000/tcp   flasky_flasky_1
1525087845e4        mysql/mysql-server:5.7   "/entrypoint.sh mysq…"   10 hours ago        Up 10 hours (healthy)   3306/tcp, 33060/tcp      flasky_mysql_1

My OS is Window Home. I use DockerToolbox
The code is from checkout 17f. I am doing every step as described in your book, but getting no success.

Containers started both with docker run  and docker-compose give the same bad result.
Also, I attach the result of **docker-compose log** command, if it can be useful.
[docker-compose logs.txt](https://github.com/miguelgrinberg/flasky/files/3795323/docker-compose.logs.txt)
Could you please help in this? Thank you in advance

**Comment by miguelgrinberg** [comment]
You are using Docker Toolbox, which isn't as convenient as the newer Docker for Windows.

With Docker Toolbox the Docker host is running in a VM, so the ports that you export from your containers do not map to localhost, they map to the IP address of this VM, which I believe is 192.168.99.100. So try to connect to your application at `http://192.168.99.100:5000`.

**Comment by vital1312** [comment]
I use Docker Toolbox because Windows Home does not support Hyper-V technology.
 Docker for Windows requires Windows 10 64-bit: Pro, Enterprise, or Education. I learned that from the official docker install manual
Yes, I tried the mentioned adress, too. And I am getting this error when connecting to http://192.168.99.100:5000 : dial tcp 192.168.99.100:5000: connect: connection timed out
![2019-11-01](https://user-images.githubusercontent.com/48630438/68033319-1a839300-fcc8-11e9-8054-1bf81fd68e31.png)

**Comment by miguelgrinberg** [comment]
I understand why you use Docker Toolbox, that is perfectly fine. What you need to figure out is what is the IP address on which your Docker host VM is. Unfortunately I do not have a Windows machine at hand right now, but I believe you should be able to see all the network connections with their IP addresses if you run the `ipconfig` command in the command prompt. I think the virtual network interface used by your Docker VM should be listed there.

**Comment by vital1312** [comment]
I ran command **docker-machine ip**, and it returned the address 192.168.99.100.

192.168.99.100:8000 or 192.168.99.100:5000 does not work,
**ip config** returns 3 IPs:
Adapter Ethernet VirtualBox Host-Only Network: **192.168.56.1**
Adapter Ethernet VirtualBox Host-Only Network #2: **192.168.99.1**
My desktop's physical address: **192.168.1.186**

And all variations of the mentions addresses combined with ports 5000 or 8000 do not work, too.
Maybe i should make some changes in port mapping in Dokerfile and docker-compose files?(so far all coding is pull from your repository of flasky)

**Comment by miguelgrinberg** [comment]
You may need to edit the port mappings in the VM in VirtualBox. Unfortunately Docker Toolbox isn't as sophisticated as the newer Docker for Windows.
