### ISSUE TITLE
how can I create table for flasky 

### ISSUE THREAD

**Issue by huanghaoran1989** [miguelgrinberg/flasky#453]
My branch is origin/master,and .
Now run flasky.py ,always "Internal Server Error".
See the error is "sqlalchemy.exc.ProgrammingError:", because I use my local database(use mysql), but can not find the script for create tables for flasky quicky ,please help, Thanks

**Comment by miguelgrinberg** [comment]
Please provide the complete error, including the stack trace. ProgrammingError can happen for a lot of different issues.

**Comment by fsejdovic** [comment]
Sir, I am facing the same error(I installed rackspace file):

OperationalError: (sqlite3.OperationalError) no such table: posts [SQL: u'SELECT posts.id AS posts_id,
		posts.body AS posts_body, posts.body_html AS posts_body_html, posts.timestamp AS posts_timestamp,
		posts.author_id AS posts_author_id \nFROM posts ORDER BY posts.timestamp DESC\n LIMIT ? OFFSET ?'] [parameters:
		(20, 0)] // Werkzeug Debugger

**Comment by miguelgrinberg** [comment]
@fsejdovic you have not created the `posts` table. The error is pretty clear:

    OperationalError: (sqlite3.OperationalError) no such table: posts

**Comment by werg09** [comment]
Dont forget to run 

$ flask db migrate -m "initial migration" 
$ flask db upgrade

**Comment by sanix-sandel** [comment]
Hello Miguel ! I'm very grateful for what you provide through your
tutorial. I have a problem with my flask web app I'm developing, already
one month, I trying my best, striving to run background tasks with celery
but no results, always Runtime error, I have to use app_context(). Even
though I read your article about celery and flask factory pattern, but it
doesn't work out. Please, I need your help, it's my first project, and I
want to achieve it. Thank you in advance.

**Comment by miguelgrinberg** [comment]
@sanix-sandel can't really help you with the little information you provided. I suggest you take the code from my article, make sure it works for you, then modify it to suit your needs.
