### ISSUE TITLE
Question on calling python programs on other server using Celery

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#46]
@miguelgrinberg I want to call some python programs from Flasky using Celery for data analysis - ideally those programs should be on a different server than Flasky - what's the best practice to do that? Thanks for your help.

**Comment by miguelgrinberg** [comment]
Can you put the Celery worker(s) in the server where these programs are? That is the simplest solution, Celery takes care of the communication between hosts.
