### ISSUE TITLE
A question about code

### ISSUE THREAD

**Issue by liyangtxwd** [miguelgrinberg/flasky#460]
hi,i'm followingthis book to learn,and find a question in branch '12b', function follow and unfollow is not commit before return,but next branch was modify。

**Comment by miguelgrinberg** [comment]
This is explained in the book. It is a bad practice to issue commits in internal functions of the application. The commit is done in the view function, when all the actions for the request are complete.

**Comment by liyangtxwd** [comment]
very much agree with you,but i mean  in  views.py with out commit(follow,unfollow),please checkout 12b and check it.

**Comment by liyangtxwd** [comment]
![image](https://user-images.githubusercontent.com/48709342/75837346-8b19f800-5dff-11ea-995c-2d92d3531cfa.png)

**Comment by liyangtxwd** [comment]
![image](https://user-images.githubusercontent.com/48709342/75837378-a422a900-5dff-11ea-8553-66f42404fda7.png)

**Comment by miguelgrinberg** [comment]
Oh, sorry, now I see what you mean. The commit is incorrectly added in 12c, should have been in 12b. I'll fix it, thanks.

**Comment by miguelgrinberg** [comment]
This is now fixed. Thanks.
