### ISSUE TITLE
How can I get tables after finished the "models.py"?

### ISSUE THREAD

**Issue by PURE-1-HEART** [miguelgrinberg/flasky#462]
Hi Miguel, your book realy help me a lot in learning flask, I am realy appreciate for that. But now I get lost in a question that I have finished two class "User" and "Post"  in "models.py"
```` from. import db
from datetime import datetime


class User(db.Model):
    __tablename__ = 'User'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.Text,unique=True,nullable=False)
    password = db.Column(db.Text,nullable=False)


class Post(db.Model):
    __tablename__ = 'Post'
    id = db.Column(db.Integer,primary_key=True)
    author_id = db.Column(db.Integer,db.ForeignKey('User.id'),nullable=False)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    title = db.Column(db.Text,nullable=False)
    body = db.Column(db.Text,nullable=False)

db.create_all() 
````
and the code in "__init__.py" is :
````
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(test_config=None):
    #创建一个app 并对它进行设置
    #第二个参数是为了从一个被git忽略的
    # instance文件夹中加载config文件
    app = Flask(__name__,instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY = 'dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
        SQLALCHEMY_DATABASE_URI='sqlite:///' + os.path.join(app.instance_path,'flaskr.sqlite'),
        # SQLALCHEMY_COMMIT_ON_TEARDOWN=True,
    )
    # print('*'+app.config['SQLALCHEMY_DATABASE_URI'])
    if test_config is None:
        #为了使测试设置和开发设置分离 便于同时进行
        app.config.from_pyfile('config.py',silent=True)
    else:
        app.config.from_mapping(test_config)

    #确定现在的文件夹存在 这个现在的文件夹代表了
    #数据库等比较机密的文件的存储路径
    try:
        os.mkdir(app.instance_path)
    except OSError:
        pass

    #一个返回简单hello的page
    @app.route('/hello')
    def hello():
        return 'hello'


    # from . import db
    # db.init_app(app)


    db.init_app(app)


    from flaskr import auth
    app.register_blueprint(auth.bp)
    from flaskr import blog
    app.register_blueprint(blog.bp)


    app.add_url_rule('/',endpoint='index')

    return app
````
But when I call "http://127.0.0.1:5000/" ,it raise a error:
"RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.".
 It realy confuse me what had happend to my app?

**Comment by PURE-1-HEART** [comment]
First, I have use "db.init_app(app)" in "__init_.py" . Why the error is "No application ..."?  How could I solve this question?
Second, should I create tables in "models.py" useing "db.create_all()"? If not , where shuold  I create these tables?  If I delete "db.create_all()" ,it will raise a error 
"no such table Post...". Why this error happen?

**Comment by miguelgrinberg** [comment]
Have you seen the database migration solution proposed in the book? That's one option.

If you prefer to use `db.create_all()`, then run it inside an app context:

```python
with app.app_context():
    db.create_all()
```

**Comment by PURE-1-HEART** [comment]
> Have you seen the database migration solution proposed in the book? That's one option.
> 
> If you prefer to use `db.create_all()`, then run it inside an app context:
> 
> ```python
> with app.app_context():
>     db.create_all()
> ```

Thank you for your adcice. I will cheack the book later. But where `db.create_all()` should be in? The "models.py" or "__init__.py" or another file ?

**Comment by miguelgrinberg** [comment]
It can be anywhere you like, as long as the models and the application are imported.

**Comment by PURE-1-HEART** [comment]
> It can be anywhere you like, as long as the models and the application are imported.

OK, thanks. Maybe, what realy puzzle me is that after define tables in models.py useing these code:
````
from . import db
from datetime import datetime

class User(db.Model):
    __tablename__ = 'User'
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.Text,unique=True,nullable=False)
    password = db.Column(db.Text,nullable=False)


class Post(db.Model):
    __tablename__ = 'Post'
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer,primary_key=True)
    author_id = db.Column(db.Integer,db.ForeignKey('User.id'),nullable=False)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    title = db.Column(db.Text,nullable=False)
    body = db.Column(db.Text,nullable=False)

````
What should I do to create table User and Post? I think it is the realy reason why I got error.

**Comment by miguelgrinberg** [comment]
This is covered in very good detail in the book you said you were going to pick up later.

**Comment by PURE-1-HEART** [comment]
> This is covered in very good detail in the book you said you were going to pick up later.

Of course, I will.  Thank you very much for your time！
