### ISSUE TITLE
Flasky does not run in terminal

### ISSUE THREAD

**Issue by Brahim-zr** [miguelgrinberg/flasky#468]
Hi there,

I am trying to run the flasky app after having installed everything, but the app just won't run.... 
This is how my terminal looks like: 

PS C:\Users\Brahi> cd documents
PS C:\Users\Brahi\documents> cd flask
PS C:\Users\Brahi\documents\flask> venv\Scripts\activate
(venv) PS C:\Users\Brahi\documents\flask> cd ..\github
(venv) PS C:\Users\Brahi\documents\github> cd oreilly-intro-to-flask-video
(venv) PS C:\Users\Brahi\documents\github\oreilly-intro-to-flask-video> cd flasky2
(venv) PS C:\Users\Brahi\documents\github\oreilly-intro-to-flask-video\flasky2> py flasky.py
(venv) PS C:\Users\Brahi\documents\github\oreilly-intro-to-flask-video\flasky2>

So as you can see in the last line, the app doesn't run. Do you have any idea what the problem could be? 
Thank you very much for your time and consideration! 

Best,
Brahim

**Comment by miguelgrinberg** [comment]
Are you following the book? Flasky is an application that is created in layers, it was designed to be used as a tool in learning Flask with the Flask Web Development book. It is not a standalone script that you install and run right away, you have to set up your requirements, database, initial data, and so on.

**Comment by Brahim-zr** [comment]
Okay, that makes sense! I have the book, but I just wanted to run the app to have an idea what I was working towards (to have a visualization of the final result)... But I'll start layer by layer now. Thank you for your prompt response!

**Comment by miguelgrinberg** [comment]
@Brahim-zr at the end of chapter one you will have the first version of the application running. You will not have to wait long.
