### ISSUE TITLE
Generate fake users and posts (11c)

### ISSUE THREAD

**Issue by 277090010** [miguelgrinberg/flasky#47]
>>> User.generate_fake(100)
>>> Post.generate_fake(100)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Post' is not defined
![wrong](https://cloud.githubusercontent.com/assets/12638972/7897499/52f9f966-0710-11e5-8e0a-d45e6d4137fb.jpg)

What's wrong maybe?Thanks!

**Comment by miguelgrinberg** [comment]
As discussed in the other thread, the problem is that `Post` was not being set in the shell context, so it needs to be imported manually or added to the context.

**Comment by hyolee750** [comment]
add some code in `manage.py`
```python
from app.models import User, Role, Post
...
def make_shell_context():
    return dict(app=app, db=db, User=User, Role=Role,Post=Post)
```
it works!
