### ISSUE TITLE
why db session commit  in views?

### ISSUE THREAD

**Issue by IvesFeng** [miguelgrinberg/flasky#474]
I saw db.session.commit() always write in views, why not write in the method of models after db.session.add?

**Comment by miguelgrinberg** [comment]
Because it is more efficient to do a single commit when a view reaches the end.

**Comment by straeter** [comment]
I also came across this. For me, the "last_seen" is only updated if I fill out a form, write a comment or do anything else that explicitly causes a db.session.commit(). Is this wanted?

It would be nice to see when the user was last active - but of course without committing 100 times a minute. Any ideas? I guess I would for myself go with a solution, where committing is caused in the ping() function if the day in the date has changed

**Comment by miguelgrinberg** [comment]
@straeter You can add a `db.session.commit()` after the ping call in the before_request handler.

**Comment by straeter** [comment]
yes @miguelgrinberg , thank you, I was considering this. I think this will cause a lot of commits for each user session, so it should be used with caution. For my app it is enough to update the last_seen once a day

**Comment by miguelgrinberg** [comment]
@straeter you can always check the previous `last_seen` value and only do the ping and the commit when 24 hours or more have passed.
