### ISSUE TITLE
I want to know how to initialize the database now, as is not stated in the second edition of the book.

### ISSUE THREAD

**Issue by tom-rgb** [miguelgrinberg/flasky#478]
#299 

-  want to know how to initialize the database now, as is not stated in the second edition of the book.`class ```
```
DevelopmentConfig(Config):

    DEBUG = True
    pymysql.install_as_MySQLdb()
    SQLALCHEMY_DATABASE_URI = 'mysql://root:cfs119@localhost:3306/flasky?charset=utf8'
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SECRET_KEY = os.urandom(24)
    # SQLALCHEMY_DATABASE_URI = os.environ.get('DEV_DATABASE_URL') or \
    #     'sqlite:///' + os.path.join(basedir, 'data-dev.sqlite')`
```

**Comment by miguelgrinberg** [comment]
Here are some notes:

- Do not hardcode your database credentials in your configuration. The book teaches a better and more secure way of doing this, which you have commented out.
- The answer to your question is in the code you commented out, actually. Why did you do that? Put your database URL in the environment variable and that should be it. Also, I'm confused about your claim this isn't in the book. In fact it is.

**Comment by tom-rgb** [comment]
> 这里有一些注意事项：
> 
> * 不要在配置中对数据库凭据进行硬编码。这本书讲授了一种更好，更安全的方法来执行此操作，您已经注释掉了。
> * 问题的答案实际上是在您注释掉的代码中。你为什么这么做？将数据库URL放在环境变量中，应该是它。另外，我对您的说法不知所措，这不在书中。其实是。



> Here are some notes:
> 
> * Do not hardcode your database credentials in your configuration. The book teaches a better and more secure way of doing this, which you have commented out.
> * The answer to your question is in the code you commented out, actually. Why did you do that? Put your database URL in the environment variable and that should be it. Also, I'm confused about your claim this isn't in the book. In fact it is.

I don't know a lot, i'm a novice, and it's more friendly to run this project if you have a series of steps to do after cloning this project and then need to do those configuration and initialization databases to run this project.

**Comment by tom-rgb** [comment]
> Here are some notes:
> 
> * Do not hardcode your database credentials in your configuration. The book teaches a better and more secure way of doing this, which you have commented out.
> * The answer to your question is in the code you commented out, actually. Why did you do that? Put your database URL in the environment variable and that should be it. Also, I'm confused about your claim this isn't in the book. In fact it is.

I don't know a lot, i'm a novice, and it's more friendly to run this project if you have a series of steps to do after cloning this project and then need to do those configuration and initialization databases to run this project. 
Thank you very much for your reply.

**Comment by miguelgrinberg** [comment]
This project is designed to be used when following the book from start to end. It is not designed to learn Flask without the book. Sorry.

**Comment by tom-rgb** [comment]
I learned based on the Flask Web Development I bought: Python-based Web Application Development (Version 2), but I didn't see how to initialize the way to run this project in the window 10 system...

**Comment by miguelgrinberg** [comment]
Go back to the book and visit chapter 2. At the end of it you will know how to have the first version of this project running. Each chapter that follows adds some more features, and you'll learn how to work with them and keep the project running.

As I said, this is not a project that you install and run. It is supposed to be used in the specific way indicated in the book to learn.
