### ISSUE TITLE
when build a docker,Error: [Errno 13] Permission denied: '/home/flasky/venv'

### ISSUE THREAD

**Issue by edisontcd** [miguelgrinberg/flasky#479]
`docker build -t flasky:latest .`
`Sending build context to Docker daemon  208.9kB`
`Step 1/14 : FROM python:3.6-alpine`
 `---> db62bff79f1e`
`Step 2/14 : ENV FLASK_APP flasky.py`
 `---> Using cache`
 `---> 9546ef63ce09`
`Step 3/14 : ENV FLASK_CONFIG production`
 `---> Using cache`
 `---> 5ae9673ccfec`
`Step 4/14 : RUN adduser -D flasky`
 `---> Using cache`
 `---> ac749d989f8e`
`Step 5/14 : USER flasky`
 `---> Using cache`
 `---> e369fb0b41a4`
`Step 6/14 : WORKDIR /Home/flasky`
` ---> Using cache`
` ---> 16e84e396e4f`
`Step 7/14 : COPY requirements requirements`
 `---> Using cache`
 `---> fd70e0aa8c0f`
`Step 8/14 : RUN python3 -m venv venv`
 `---> Running in 30559bab663b`
`Error: [Errno 13] Permission denied: '/home/flasky/venv'`
`The command '/bin/sh -c python3 -m venv venv' returned a non-zero code: 1
`

**_when build a docker, can't RUN python3 -m venv venv, and the error_** 
`Error: [Errno 13] Permission denied: '/home/flasky/venv'`
`The command '/bin/sh -c python3 -m venv venv' returned a non-zero code: 1
`

**Comment by miguelgrinberg** [comment]
Do you get the same problem if you add the `--no-cache` option to your build command?

**Comment by edisontcd** [comment]
`#!/bin/sh`
`source venv/bin/activate`

`while true; do`
   ` flask deploy`
    `if [[ "$?" == "0" ]]; then`
        `break`
    `if`
    `echo Deploy command failed, retrying in 5 secs...`
    `sleep 5`
`done`

`exec gunicorn -b :5000 --access-logfile - --error-logfile - --no-cache - flasky:app`

yes, command like this, still get the same problem

**Comment by miguelgrinberg** [comment]
The `--no-cache` option is not for gunicorn, is for the docker build command.

**Comment by edisontcd** [comment]
`docker build --no-cache -t flasky:latest .`
`Sending build context to Docker daemon  208.9kB`
`Step 1/14 : FROM python:3.6-alpine`
 `---> db62bff79f1e`
`Step 2/14 : ENV FLASK_APP flasky.py`
` ---> Running in 4bef69f13366`
`Removing intermediate container 4bef69f13366`
 `---> 429a060c0440`
`Step 3/14 : ENV FLASK_CONFIG production`
 `---> Running in 3b19a4207e28`
`Removing intermediate container 3b19a4207e28`
 `---> 9390c6a60ec5`
`Step 4/14 : RUN adduser -D flasky`
 `---> Running in 92124f796574`
`Removing intermediate container 92124f796574`
 `---> 5ba4821cd4ff`
`Step 5/14 : USER flasky`
 `---> Running in c2eabf23c129`
`Removing intermediate container c2eabf23c129`
 `---> c98e4e7740f5`
`Step 6/14 : WORKDIR /home/flasky`
 `---> Running in 902a017cca47`
`Removing intermediate container 902a017cca47`
` ---> dc580ac91512`
`Step 7/14 : COPY requirements requirements`
 `---> d0912c76279f`
`Step 8/14 : RUN python3 -m venv venv`
 `---> Running in 381baf19c97b`
`Error: [Errno 13] Permission denied: '/home/flasky/venv'`
`The command '/bin/sh -c python3 -m venv venv' returned a non-zero code: 1`

**_still get the problem like this_**

**Comment by miguelgrinberg** [comment]
@edisontcd I honestly don't know. I just retested building this image here with the current `3.6-alpine` image and it builds just fine for me. I suggest you start from scratch, with a new Flasky repository and a re-downloaded 3.6-alpine image, not sure what can be causing this problem for you.

**Comment by edisontcd** [comment]
thanks，I'll try it by u way

**Comment by michaelmcguire** [comment]
Just in case someone in the future comes across this and happens to make the same mistake I did, my `Dockerfile` had:

```
RUN useradd -create-home --shell /bin/bash <myuser>
```
instead of the correct
```
RUN useradd --create-home --shell /bin/bash <myuser>
```
That missing dash seems to have caused the home directory to not be created so when the `Dockerfile` references `/home/<myuser>` later it was creating that directory without the correct permissions and I got this exact error when trying to run `RUN python -m venv venv`. 

I have no idea why this worked locally on my Mac using Docker Desktop for Mac, but it didn't stop working until I was running Docker on a Linux host.
