### ISSUE TITLE
I want get username from session instead of parameter what is in url

### ISSUE THREAD

**Issue by dayiguizhen** [miguelgrinberg/flasky#48]
@main.route('/about')
    def user():
         return '<h1>Hello,%s</h1>' %user.email;
    
    @main.route('/about/<username>')
    def user(username):
        user = User.query.filter_by(username=username).first();
        return '<h1>Hello,%s</h1>' %user.email;

can I get username from session or browser cookie?So I can set route concise. What should I do?

**Comment by miguelgrinberg** [comment]
Sure, you can do it that way if you want. Just create your route without the `username` argument, and use `current_user` instead.

**Comment by dayiguizhen** [comment]
Thanks! I succeed did this.
