### ISSUE TITLE
Title block duplication in templates. Chapter 03 (Tag 3c)

### ISSUE THREAD

**Issue by dragi-ns** [miguelgrinberg/flasky#481]
Hi Miguel!

In the `templates/base.html` you have declared a title block with `Flasky` text inside it.
https://github.com/miguelgrinberg/flasky/blob/19997c8cf54323a01948b77c1187017591a7b6d8/templates/base.html#L3

In the `templates/index.html` and `templates/user.html` that title block is repeated with the same text, so it's redundant.
https://github.com/miguelgrinberg/flasky/blob/19997c8cf54323a01948b77c1187017591a7b6d8/templates/index.html#L3
https://github.com/miguelgrinberg/flasky/blob/19997c8cf54323a01948b77c1187017591a7b6d8/templates/user.html#L3

In the `templates/404.html` and`templates/500.html` we can use `{{ super() }}` instead of repeating `Flasky`.
https://github.com/miguelgrinberg/flasky/blob/19997c8cf54323a01948b77c1187017591a7b6d8/templates/404.html#L3

```html
{% block title %}{{ super() }} - Page Not Found{% endblock %}
```

https://github.com/miguelgrinberg/flasky/blob/19997c8cf54323a01948b77c1187017591a7b6d8/templates/500.html#L3

```html
{% block title %}{{ super() }} - Internal Server Error{% endblock %}
```

BTW, I'm loving the book so far.

**Comment by miguelgrinberg** [comment]
I would not go as far as calling super() to just get the `Flasky` part, but the idea is that each page can override the title. The index and user pages should have used a more specific title instead of the same Flasky default.
