### ISSUE TITLE
flask_sqlalchemy; db.session.commit() does not save changes in database

### ISSUE THREAD

**Issue by kirilgeorgiev82** [miguelgrinberg/flasky#483]
Hello,

First, thank you very much for reviewing my request!

The issue is as follows: a flask app running on Ubuntu 18.04 (currently using the development server); in a view, a database record is retrieved, updated and then commited. However, the changes are not saved to the record and when it is next retrieved it still has its old values. For example:

```
@main_bp.route('/select-option', methods = ['GET', 'POST'])
def select_option():
...................
if request.method == 'POST':

       selected_value = request.form['whatever_key_is_relevant']

       record = Record.query.get(id)

       record.value_of_interest = selected.value

       try:
                db.session.add(record)

                db.session.commit() 
  
        except Exception as e:

                db.session.rollback()
                logging.exception(e)
```

So, the problem is that next time I retrieve the record, the changes are not persisted there. 

Thank you very much in advance and your advice is very highly appreciated!

**Comment by miguelgrinberg** [comment]
This isn't really enough information for me to tell you what the problem is. The problem is likely not in this code, but instead in the configuration or set up of the application or the database.

**Comment by kirilgeorgiev82** [comment]
Hi Miguel,

Thank you very much for your prompt answer! Indeed, probably this would be the case. I am using a PostgreSQL service from GCP. Another weird behaviour I see is that the following: the column I am trying to update is of db.PickeType where I want to keep a dictionary, which dictionary is supposed to help with maintaining user state. When I want to make updates in this dictionary like:

```
record = Record.query.get(id)
state = copy.copy(record.state)
state['new_thing'] = some_new_things
db.session.commit()
```
It works!

However, if I try to update this dictionary again, I get:

 ```
File "/home/kiril...../app/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 628, i
n _collect_update_commands
    value, state.committed_state[propkey]
  File "/home/kiril....../app/venv_dev/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1699, in 
compare_values
    return x == y
**ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()**
```

When I use the query.get() method I am not sure whether I receive the actual object or some copy (or proxy of it) which might be influencing the whole process. Would you have any idea what could be triggering this behaviour!

Very much appreciated! 

Kind regards,
Kiril

**Comment by miguelgrinberg** [comment]
> I am not sure whether I receive the actual object

There is no concept of objects in the database. SQLAlchemy creates an object representation of the data stored in your database, so in a way all model instances are proxies that represent the real data.

What would be the purpose of doing these strange operations with copy on attributes of the model?

**Comment by kirilgeorgiev82** [comment]
Hi Miguel,

Thank you for coming back to me. Let me try to create an example. Again, in a view:

```
@main_bp.route('/my-troubled-route'):
def my_troubled_route():
      state = UserState.query.get(the_unque_identifier)
    
      new_info = request.form['the_new_info_from_the_form']
      state.user_state_that_is_just_a_dictionary['new_info'] = new_info
      try:
              # db.session.add(state) - with or without this - it won't work
              db.session.commit()
      except Exception as e:
               logging.exception(e)
```
Result: 1) No errors whatsoever; 2) When I retrieve the respective user_state again, it is just not updated

So, if this is done:

```
@main_bp.route('/my-troubled-route'):
def my_troubled_route():
      state = UserState.query.get(the_unque_identifier)
      
       _temporary_state = copy.copy(state.user_state_that_is_just_a_dictionary)
      
      new_info = request.form['the_new_info_from_the_form']
      _temporary_state['new_info'] = new_info
      
      state.user_state_that_is_just_a_dictionary = _temporary_state

      try:
              db.session.commit()
      except Exception as e:
               logging.exception(e)

```
It _does_ get saved in the db.

For me just making it work this way is far from enough and I would like to understand why I get this behaviour. An re the question why I tried with a copy, I had a similar problem with memory views in OpenCV (I know they are very, very different from what we have here, but I found an analogy with getting only access to proxies rather than the underlying data and decided to just try it out). 

This is a frustrating one. Thank you very much once again, and for the book, and the tutorials....

**Comment by miguelgrinberg** [comment]
What is the type of the dictionary attribute in your model?

**Comment by kirilgeorgiev82** [comment]
It is state = db.Column(db.PickleType). My understanding is that it does pickle.dump and pickle.load automatically.

**Comment by miguelgrinberg** [comment]
Did you read the SQLAlchemy docs? There is a page specifically about this issue: https://docs.sqlalchemy.org/en/13/orm/extensions/mutable.html.

**Comment by kirilgeorgiev82** [comment]
Thank you very much Miguel! Unfortunately, I had not come across this one (otherwise I did my fair share of reading before asking for your time, I presume how busy you are). I will have a very good look at this and will come back to you and maybe draf a better explanation so other users can benefit from it. Please let me know what you think?

Kind regards,
Kiril

**Comment by miguelgrinberg** [comment]
@kirilgeorgiev82 yes, if you can post your working code here when you have it that would be awesome, as others will find it when they face the same problem. Thanks!

**Comment by kirilgeorgiev82** [comment]
Thank you very much Miguel! Yes, let me read the documentation you referenced, sort it out and I will post the solution here. Thank you and speak to you soon.

Best regards,
Kiril

**Comment by kirilgeorgiev82** [comment]
Hi Miguel,

Please allow me to share the way I solved (or in my case it would be more accurate to say managed to avoid) the issue. As you pointed out to the specific part of SQLAlchemy [documentation](https://docs.sqlalchemy.org/en/13/orm/extensions/mutable.html), in my understanding the problem was related to mutation tracking and establishing mutability of a python dictionary which is persisted in the database that way. Apart from the examples in the documentation above, there seems to be also a post by [Frankster](https://stackoverflow.com/users/9428990/frankster) on StackOverflow with an example of implementing [this](https://stackoverflow.com/questions/55669649/update-sqlalchemy-orm-object-with-changed-python-dict).

In my case, I am creating an ephemeral user state which is created upon login and destroyed upon logout (I am familiar with Flask-Session but in my case I want something simpler and which I have full control over); further, it is fairly small and sufficiently fast to retrieve from the database; moreover, updates are fairly infrequent (e.g. once every few seconds or minutes, per user). So, I decided to avoid the relative complexity of the solution above and applied the following:

```
class State(db.Model):
     id = db.Column(db.String(32), index=True, primary_key=True)
     user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
     created_timestamp = db.Column(db.DateTime)
     modified_timestamp = db.Column(db.DateTime)
     closed_timestamp = db.Column(db.DateTime)
     state = db.Column(db.PickleType)  # This is where the dictionary is kept

     def some_method():
            ........
     def some_other_method():
           ........

def update_state(dictionary_with_state_updates, state_unique_id):
       current_state = State.query.get(state_unique_id)
       old_state_dictionary_which_will_be_updated = current_state.state
       old_state_dictionary_which_will_be_updated.update(dictionary_with_state_updates)
       
       refreshed_user_state = State(id=the_old_unique_id, 
                                                     created_timestamp=the_old_time_of_creation_timestamp,
                                                     modified_timestamp=datetime.datetime.utcnow(),
                                                     state =  old_state_dictionary_which_will_be_updated)
        db.session.delete(current_state)
        db.session.add(refreshed_user_state)
        try:
              db.session.commit()
       except Exception as e:
              db.session.rollback()
              logging.exception(e)
```

Whilst I acknowledge it is a 'C-' solution in a broader sense, for my case is proved the best complexity / fitness-for-purpose trade off. Thanks once again!

Best regards,
Kiril

**Comment by richie312** [comment]
you select this:

    user = Users.query.filter_by(username='foo').first()

and save this

    db.session.add(user)

It is never gonna happen.

when you select, i think that's using some flask-sqlalchemy syntactic sugar to select the session.  a 'raw' sqlalchemy approach would typically be:

    db.session.query(Users).filter_by(username='foo').first()

Source: https://groups.google.com/g/sqlalchemy/c/v8CURVXTkGA?pli=1

Answer by Jonanthan Vasco
