### ISSUE TITLE
(530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError k5sm7432040pfu.77 - gsmtp', 'None')

### ISSUE THREAD

**Issue by msMohit20** [miguelgrinberg/flasky#484]
i am middle of the project and i was connecting django with gmail and i got this type of error.....

settings.py code for :

 EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

what should is in this !!!?

**Comment by miguelgrinberg** [comment]
You have a problem with a Django project. This is a Flask project, you've come to the wrong place to ask your question.

**Comment by msMohit20** [comment]
> You have a problem with a Django project. This is a Flask project, you've come to the wrong place to ask your question.

thank you for notify me.
