### ISSUE TITLE
There was errors in docker compose runing.

### ISSUE THREAD

**Issue by franklili3** [miguelgrinberg/flasky#485]
Dear miguelgrinberg,
When I have checked out 17f, and completed docker compose running, there was logs :

> flasky_1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
> flasky_1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade  -> 38c4e85512a9, initial migration
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 38c4e85512a9 -> 456a945560f6, login support
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 456a945560f6 -> 190163627111, account confirmation
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 190163627111 -> 56ed7d33de8d, user roles
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 56ed7d33de8d -> d66f086b258, user information
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade d66f086b258 -> 198b0eebcf9, caching of avatar hashes
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 198b0eebcf9 -> 1b966e7f4b9e, post model
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 1b966e7f4b9e -> 288cd3dc5a8, rich text posts
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 288cd3dc5a8 -> 2356a38169ea, followers
> flasky_1  | INFO  [alembic.runtime.migration] Running upgrade 2356a38169ea -> 51f5ccfba190, comments
> flasky_1  | [2020-09-21 13:43:55 +0000] [1] [INFO] Starting gunicorn 19.7.1
> flasky_1  | [2020-09-21 13:43:55 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
> flasky_1  | [2020-09-21 13:43:55 +0000] [1] [INFO] Using worker: sync
> flasky_1  | [2020-09-21 13:43:55 +0000] [28] [INFO] Booting worker with pid: 28
> flasky_1  | 172.18.0.1 - - [21/Sep/2020:13:55:59 +0000] "GET / HTTP/1.1" 200 3133 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"
> flasky_1  | 172.18.0.1 - - [21/Sep/2020:13:55:59 +0000] "GET /static/styles.css HTTP/1.1" 200 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"
> flasky_1  | 172.18.0.1 - - [21/Sep/2020:13:56:00 +0000] "GET /static/favicon.ico HTTP/1.1" 200 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"

Home page works. But I have not received confirm email after registering. I remembered I have input correct mail username and password. What's the matter?

**Comment by miguelgrinberg** [comment]
You may want to run your application in debug mode, so that Flask-Mail generates logging.

**Comment by franklili3** [comment]
I modified&nbsp;MAIL_SERVER and&nbsp;FLASKY_MAIL_SENDER, and have&nbsp;received confirm email. Thanks.



世界充满希望 机会就在眼前 &nbsp;李力


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miguelgrinberg/flasky"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 晚上10:23
收件人:&nbsp;"miguelgrinberg/flasky"<flasky@noreply.github.com&gt;;
抄送:&nbsp;"李力"<348104201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miguelgrinberg/flasky] There was errors in docker compose runing. (#485)





 
You may want to run your application in debug mode, so that Flask-Mail generates logging.
