### ISSUE TITLE
url_for() parameters issue - trying to redirect from one template to another -

### ISSUE THREAD

**Issue by P26Puteaux** [miguelgrinberg/flasky#487]
I belive that I m mixing @route, function call and how a template can send back some parameters.
Hope someone can explain me in code below what is my mistake

I m looking for: start edit_author(id), which call its template with a form. It goes back to edit_author in order to validate the inputs. Once validated it call one_author function to display result (on its own template)

More than having a solution, I m trying to understand how to jump from one template to another by passing correctly parameters
I believe that mistake im doing means I didnt get it properly

```python
class AuthorForm(FlaskForm):
    id = HiddenField('id')
    name = StringField('Nom', validators=[DataRequired()])

@app.route("/edit/book/<int:id>", methods=("POST",))
@app.route("/edit/author/<int:id>")
def edit_author(id):
    a = get_author(id)
    f = AuthorForm(id=a.id, name=a.name)
    if f.validate_on_submit():
        a.name = f.name.data
        db.session.commit()
	    return render_template("one_author.html")
    return render_template("edit_author.html", author=a, form=f)


@app.route("/show/author/<int:id>")
def one_author(id):
    a = get_author(id)
    lbooks = get_author_books(id)
    f = AuthorForm(id=a.id, name=a.name )
    return render_template("show_author.html", author =a, books=lbooks, form=f
    ) 
```
 
Attached templates

Thanks a lot for your time

**Comment by NZ26-06** [comment]
[issue.txt](https://github.com/miguelgrinberg/flasky/files/5322098/issue.txt)

**Comment by miguelgrinberg** [comment]
You haven't said what is the issue or error that you have.

**Comment by NZ26-06** [comment]
True, sorry !
Right now I have:
jinja2.exceptions.UndefinedError: 'id' is undefined

File "/home/pedro/web-serveur/tuto-flask/web-serveur/TP3/tuto-flask/tuto/views.py", line 47, in edit_author
return render_template("edit_author.html", author=a, form=f)

**Comment by miguelgrinberg** [comment]
Your edit_author.httml template refers to `id`, which is not a variable you have defined in the call to render_template.

**Comment by P26Puteaux** [comment]
Thanks Miguel !
I had a check on id parameter
Also change render_template into return redirect(url_for("one_author", id=id ))
Now it works well :-) Finally !

Thank you very much
