### ISSUE TITLE
Using an EmailField instead of a StringField in forms.py for email fields.

### ISSUE THREAD

**Issue by dragi-ns** [miguelgrinberg/flasky#488]
I think that the `EmailField` would be a better choice for email fields in `forms.py` instead of the `StringField`.
`EmailField` is located in `wtforms.fields.html5`.

**Comment by miguelgrinberg** [comment]
It's a matter of preference, not something that I would consider a bug.

**Comment by dragi-ns** [comment]
It's more an enhancement, rather than a bug or matter of preference.

`StringField` will generate an `input` element of type `text`, and it will not have html5 email validation on the client.
`EmailField` will generate an `input` element of type `email`, and it will check if it contains a valid email address, before sending it to the server.

I'm aware that we are using `Email` validator on the server side.
