### ISSUE TITLE
Question about advanced API design

### ISSUE THREAD

**Issue by seanlaff** [miguelgrinberg/flasky#49]
What is the best way to design the API so that it can be used by both the client and the server? My view methods are getting cluttered and I was thinking a lot of my logic should be moved into the the API.

I changed the existing flasky API blueprint so that it acts like a thin middleman.
````
@api.route('/posts/<int:id>')
def get_post(id):
    return apiLogic.get_post(id)
````
I did this with the assumption that if I needed to access a post from the client-side I could use jQuery to send an HTTP request to the endpoint `/posts/<int:id>`. Additionally, if I wanted to render a page server side I could directly call `apiLogic.get_post(id)`.

However, calling `apiLogic.get_post(id)` directly from a separate blueprint means I lose the permission-checking logic from blueprint_before_request. Would it be poor design to issue HTTP requests from the backend onto itself to get around this problem?

Perhaps I'm thinking about API design in flask incorrectly, do you have any advice?

**Comment by miguelgrinberg** [comment]
The needs of an API route vs. a traditional web application are different, so if you try to create API routes that can be used for both purposes you are going to always have trouble making these routes work well for both use cases.

For example, for API use the return value of your routes should be a rendered JSON blob, what you get back from calling `jsonify()`. But if you call the route internally from the server, this format is very inconvenient, the server will probably need the data in a Python data structure, maybe a dictionary, or the database model object.

So my recommendation is that you add another layer with a set of helper classes or functions that are generic enough to work for both types of situations. You can implement these as a separate package or module, or maybe you can use the database models directly for this layer, that is largely up to you. The REST API and web app routes can invoke functions/methods in this new layer to get the data, then each can render the data as appropriate and return it to clients. When modifying the data the same concept applies, this intermediate layer takes calls from REST and web apps and records the data changes generically.

I hope this helps!

**Comment by seanlaff** [comment]
Thanks Miguel, that clears up a lot of my confusion! I did have one more question about the API versioning you designed in the book though. 

In the `api_1_0` directory the init file creates the API blueprint with `api = Blueprint('api', __name__)`.
Then, the blueprint is registered to the app in the app's init file with 
````
from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
````

Yet, in the models file, the comment's to_json function refernces the api without the version

````

    def to_json(self):
        json_comment = {
            'url': url_for('api.get_comment', id=self.id, _external=True),
            'post': url_for('api.get_post', id=self.post_id, _external=True),
````

Is flask implicitly reconciling that `api.get_comment` refers to the 1.0 version of the API? How would it differentiate between multiple versions of the API?

**Comment by miguelgrinberg** [comment]
The `'api'` that is referenced in the `url_for()` call refers to a blueprint name. Note that I used `'api'` as name in the `Blueprint()` constructor.

When supporting multiple API versions that serialization to JSON will have to become version aware. One way to do this would be to build a wrapper for `url_for()` that looks at the request URL, finds the version, then uses the correct blueprint name for the version the client is using.

**Comment by seanlaff** [comment]
Thanks for added insights!
