### ISSUE TITLE
Sharing forms between blueprints

### ISSUE THREAD

**Issue by dragi-ns** [miguelgrinberg/flasky#491]
Lets say i have an `auth` blueprint with the following form:

```c++
class RegistrationForm(FlaskForm):
    username = ...
    email = ...
    password = ...
    password_confirm = ...
    submit = ...
```

In a different blueprint, `manage` blueprint,  I have an `AddUserForm` form, which inherits from the `RegistrationForm` and adds two more fields:

```c++
class AddUserForm(RegistrationForm):
    role_id = ...
    confirmed = ...
```

Is it a good idea to share forms between blueprints?
Should I avoid having blueprints depend on each other?

**Comment by miguelgrinberg** [comment]
Forms do not need to be inside blueprints. If you have forms that can be used in multiple blueprints, just put them in a common place within your application structure so that both blueprints can import them without having to reference each other.

**Comment by dragi-ns** [comment]
That makes sense. Thank you.
