### ISSUE TITLE
Testing Chapter - Selenium Code is not executing via unittest test runner 

### ISSUE THREAD

**Issue by ParthiBa** [miguelgrinberg/flasky#494]
Code version Tag 15d 
File path :  tests/test_seleninum.py

![image](https://user-images.githubusercontent.com/3818623/101475760-c7701b00-3972-11eb-94e8-8dfceeea7292.png)

Unit test runner is not executing app.run() . So I have headless chrome opened and as per selenium script . URL is changing as per script . But Since application is not started and entire test script fails

**Comment by miguelgrinberg** [comment]
Unfortunately this is an issue in Flask. See https://github.com/pallets/flask/issues/2776.

**Comment by ParthiBa** [comment]
Is there any way to overcome this issue and execute the test_selenium ? Is there any other code that I can change and exexute that file ?

**Comment by miguelgrinberg** [comment]
You can make it work if you revert to an older version of Flask that does not have this bug. The version in the requirements works fine, if I remember correctly.

Aside from that, you can manually start the server via `flask run`, and then run your test suite while the manually started server is active.
