### ISSUE TITLE
Fix error

### ISSUE THREAD

**Issue by smlee729** [miguelgrinberg/flasky#497]
Hi, I found one issue on the auth view.

https://github.com/miguelgrinberg/flasky/blob/924913ce6c3556267c25e61c2a14e1b6f528febc/app/auth/views.py#L93

The route should use underscore instead of hyphen.

**Comment by miguelgrinberg** [comment]
Why? The URL does not matter, since the application always uses `url_for()` to generate them in HTML templates.

**Comment by smlee729** [comment]
Oh sorry you're right. Maybe web browser has obsolete cache or something. It's working fine as you say. Thanks!
