### ISSUE TITLE
How could I update chinese language(like 我) to MySQL 

### ISSUE THREAD

**Issue by dayiguizhen** [miguelgrinberg/flasky#50]
@main.route('/edit-about',methods=['GET','POST'])
    @login_required
    def edit_about():
        form = EditAboutForm();
        if form.validate_on_submit():
            current_user.about_me = form.about_me.data;
            try:
                db.session.add(current_user);
            flash('Your about has been updated');
        form.about_me.data = current_user.about_me;
        return render_template('edit_about.html',form=form)

The error is like this.
OperationalError: (OperationalError) (1366, "Incorrect string value: '\\xE6\\x88\\x91' for column 'about_me' at row 1") 'UPDATE users SET about_me=%s, about_me_html=%s WHERE users.id = %s' ('\xe6\x88\x91', '<p>\xe6\x88\x91</p>', 1L)

Is SQLite support Chinese.But MySQL doesn't?

**Comment by ZhangBohan** [comment]
You can run `show create table users` in your mysql, it's charset problem on your mysql, change your table to utf8 will fix this issue.

--------------------------
可能是你的MySQL数据库的编码有问题， 在MySQL中运行一下`show create table users`看一下你的表编码是不是utf8的，把你的表编码修改为utf8应该就可以解决这个问题了。

**Comment by dayiguizhen** [comment]
Yes.You are right.Thanks!
