### ISSUE TITLE
sqlalchemy.exc.ArgumentError: Textual SQL expression '' should be explicitly declared as text('')

### ISSUE THREAD

**Issue by Makeem1** [miguelgrinberg/flasky#503]
Hello Miguel, thanks for writing your web development with flask book. It has helped me a lot. I'm working on clone project and i was stucked on it because i'm getting an sqlachemy error. Anytime i called on the route, i usually get the error. The error, route  and my database are below. Thanks

Database:
from snakeeyes.extensions import db
import datetime
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin
from snakeeyes.extensions import login_manager
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer
from collections import OrderedDict
from sqlalchemy import or_

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    ROLE = OrderedDict([
        ('member', "Member"),
        ("admin", "Admin")
    ])
    
    # Unique idntification number
    id = db.Column(db.Integer, primary_key = True)

    # User credentials
    role = db.Column(db.Enum(*ROLE, name = 'role_type', native_enum = False), nullable = False, default='member')
    username = db.Column(db.String(24), nullable=True, unique=True)
    email = db.Column(db.String(128), nullable=False, unique = True)
    active = db.Column(db.Boolean, default = True, nullable=False)
    hash_password = db.Column(db.String(240), nullable=False)
    confirmed = db.Column(db.Boolean, default = False)

    # User tracking information 
    sign_in_count = db.Column(db.Integer, default=0)
    current_sign_in_on = db.Column(db.DateTime(), default=datetime.datetime.utcnow)
    current_sign_in_ip = db.Column(db.String(24)) 
    last_sign_in_on = db.Column(db.DateTime(), default=datetime.datetime.utcnow)
    last_sign_in_ip = db.Column(db.String(24)) 

    # User run time
    created_on = db.Column(db.DateTime(), default = datetime.datetime.utcnow)
    updated_on = db.Column(db.DateTime(), default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    @property
    def password(self):
        raise AttributeError('Password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.hash_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.hash_password, password)

    def is_active(self):
        return self.active

    @classmethod
    def search(cls, query):
        """Help to filter search in the from the database"""

        if not query:
            return ''

        search_query = '{0}'.format(query)
        search_chain = (User.email.ilike(search_query), User.username.ilike(search_query))

        return or_(*search_chain)

    @classmethod
    def sort_by(cls, field, direction):
        """This help to sort the user base on the field column and direction. """

        if field not in cls.__table__.columns:
            field = "created_on"
        
        if direction not in ('asc', 'desc'):
            direction = 'asc'

        return field, direction

    
    @classmethod
    def is_last_admin(cls, user, new_role, new_active):
        """This particular method will help to check if this particular user is the last admin."""

        is_changing_role = user.role == 'admin' and new_role != 'admin'
        is_changing_active = user.active is True and new_role is None

        if is_changing_role or is_changing_active :
            admin_count = User.query.filter(User.role == 'admin').count()
            active_count = User.query.filter(User.is_active is True).count()

            if admin_count == 1 or active_count == 1:
                return True
                
        return Falses

    def track_user_activities(self, ip_address):
        self.sign_in_count = +1

        self.last_sign_in_on = self.current_sign_in_on
        self.last_sign_in_ip = self.current_sign_in_ip

        self.current_sign_in_ip = ip_address
        self.current_sign_in_on = datetime.datetime.utcnow()

        return True

    
    def generate_token(self, expiration=3600):
        s = TimedJSONWebSignatureSerializer(current_app.config["SECRET_KEY"],  expires_in=expiration)
        return s.dumps({"confirm": self.id}).decode('utf-8')

    def verify_token(self,token):
        s = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False

        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        user = User.query.filter_by(id = data.get('confirm')).first()
        return user.email

    def generate_reset_token(self):
        s = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'])
        return s.dumps({'user_id': self.id})

    @staticmethod
    def confirm_reset_token(token):
        s = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False

        user = User.query.get(data.get('user_id'))

        return user.id

      

Route causing the error:
@admin.route('/users')
def users():
    """Fucntion to list all users in the database."""
    form_search = SearchForm()

    page = request.args.get('page', 1, type =int )

    sort_by = User.sort_by(request.args.get('sort', 'created_on'), 
                                            request.args.get('direction', 'desc'))

    order_values = '{0} {1}'.format(sort_by[0], sort_by[1])

    paginated_users = User.query \
        .filter(User.search(request.args.get('q', ''))) \
        .order_by(User.role.asc(), text(order_values)) \
        .paginate( page = page , per_page =current_app.config[FLASKY_POSTS_PER_PAGE] , error_out = False )

    return render_template('admin/user/index.html', form = form_search , users = paginated_users )

 

Traceback (most recent call last):
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\flask_debugtoolbar\__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\snakeeyes\admin\views.py", line 39, in users
    .filter(User.search(request.args.get('q', ''))) \
  File "<string>", line 2, in filter
    
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\orm\query.py", line 1878, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\sql\elements.py", line 4707, in _expression_literal_as_text
    return _literal_as_text(element)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\sql\elements.py", line 4730, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\sql\elements.py", line 4716, in _literal_as
    return text_fallback(element)
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\sql\elements.py", line 4766, in _no_text_coercion
    replace_context=err,
  File "C:\Users\Makeem\Desktop\snake-app-restructuring\env\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression '' should be explicitly declared as text('')

**Comment by miguelgrinberg** [comment]
Your `User.search` method returns an empty string. You are then passing this empty string as an argument to `filter()`, which is invalid.

**Comment by Makeem1** [comment]
Thanks Miguel, I've been able to solve the issue. Yes, I think it is the version of sqlalchemy i'm using in my project. When i use SQLAlchemy==1.2.0, the code work as expected. Thanks
