### ISSUE TITLE
Importing config from parent folder

### ISSUE THREAD

**Issue by dcfwight** [miguelgrinberg/flasky#507]
Forgive me if this is a beginner question!
In app/main/__init__.py 
you import config from the parent folder.

I've been running the code as I go and it won't import from the parent - am I missing something?
I've seen a work-around as:

`import sys
sys.path.append('..')

Thanks, Doug.

**Comment by miguelgrinberg** [comment]
This works if the current directory is the parent, because the current directory is in the import path. It will not work if the current directory is somewhere else.

**Comment by dcfwight** [comment]
Thanks for the quick response.
So I guess I have to move config.py down to the /main folder, so that when __init__.py is run (which is in the /main folder), it can locate config.py, also in the /main folder.

**Comment by dcfwight** [comment]
Thanks for the quick response.
And I was confusing myself, but my main point was still relevant.
I was actually referring to the file: app/__init__.py
This file was trying to import config from the parent folder - flasky

So if I understand you, I need to either move config.py down to the app folder, so that when __init__.py runs, then both it and config.py are in the same import path, OR amend the import path by this code, so that it looks in the parent folder too?
`import sys
sys.path.append('..')

Thx, Doug.

**Comment by miguelgrinberg** [comment]
No, I think I did not make myself clear.

When you have `import config` in `app/__init__.py`, you are seeing an import from a parent directory, but this is an incorrect interpretation. This is an import from the current directory (which happens to be the parent directory of this particular file, but that is irrelevant). Basically any Python file in your project regardless of location can do `import config` and it will work, as long as the current directory is the directory where `config.py` is located.

**Comment by dcfwight** [comment]
Ah, ok. Thx for the explanation. I think I see now.
