### ISSUE TITLE
Heroku deployment fails to install markupsafe

### ISSUE THREAD

**Issue by bkline** [miguelgrinberg/flasky#510]
Here's the relevant portion of the build log.

```
       Collecting MarkupSafe==1.0
         Downloading MarkupSafe-1.0.tar.gz (14 kB)
           ERROR: Command errored out with exit status 1:
            command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wwuzjgrj/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wwuzjgrj/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vgq2je9f
                cwd: /tmp/pip-install-wwuzjgrj/markupsafe/
           Complete output (5 lines):
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-install-wwuzjgrj/markupsafe/setup.py", line 6, in <module>
               from setuptools import setup, Extension, Feature
           ImportError: cannot import name 'Feature' from 'setuptools' (/app/.heroku/python/lib/python3.9/site-packages/setuptools/__init__.py)
           ----------------------------------------
       ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

According to https://github.com/pallets/markupsafe/issues/57, bumping up the version 1.1.1 of markupsafe should solve the problem

**Comment by miguelgrinberg** [comment]
You must be using an outdated version of this repo, because I've made that change a while ago.

**Comment by bkline** [comment]
Well, I can see that what GitHub has for tag `17d` has the latest version for `MarkupSafe` but my clone, after
```
$ git checkout 17d
```
has the older version (1.0.0), even though `git status` doesn't report any modified files (nor does `git diff`). So I've got some head-scratching to do. I'm sure I'll figure it out eventually, and will report back. Thanks.

**Comment by bkline** [comment]
Well, somehow `git` has gotten itself tied in knots with all the switching between all the tags with detached HEADs. I wasn't able to see a clear path to untangling the confusion and merge conflicts (where they came from I have no idea, as I've introduced no changes of my own beyond a debugging hack which I immediately backed out, and I've only been switching between repo tags), short of cutting the Gordian knot and creating a fresh clone of this repository. Unfortunately, that undid the connection to the Heroku app. Restoring the `git remote` registrations wasn't sufficient, it seems, as Heroku still refuses to build, so presumably there's some other magic Heroku performs behind the scenes when you run the `heroku` command-line tool. I suppose I could wipe out the Heroku app and start again, and that's what I'd probably do if I didn't have my own servers. It was so much easier to set up the app with `nginx` and `gunicorn` on one of my own servers, though, that I'm just going to walk away from the Heroku path. Not your fault. 😅
