### ISSUE TITLE
Running flask with docker

### ISSUE THREAD

**Issue by Makeem1** [miguelgrinberg/flasky#511]
Hello Miguel, thanks for helping out always. I decide to run my flask app with docker and after i set the docker-compose.yml file and dockerfile, i'm this bunch of error which is causing my app to fail. 

Successfully built 5a42dfb64267
Successfully tagged hospital-management-system_website:latest
Creating hospital-management-system_website_1 ... done
Attaching to hospital-management-system_website_1
website_1  | [2021-04-19 13:11:13 +0000] [1] [INFO] Starting gunicorn 19.4.5
website_1  | [2021-04-19 13:11:13 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
website_1  | [2021-04-19 13:11:13 +0000] [1] [INFO] Using worker: sync
website_1  | [2021-04-19 13:11:13 +0000] [10] [INFO] Booting worker with pid: 10
website_1  | Exception in thread Thread-1:
website_1  | Traceback (most recent call last):
website_1  |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
website_1  |     self.run()
website_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/reloader.py", line 41, in run
website_1  |     for filename in self.get_files():
website_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/reloader.py", line 29, in get_files
website_1  |     for module in list(sys.modules.values())
website_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/reloader.py", line 30, in <listcomp>
website_1  |     if hasattr(module, '__file__')
website_1  |   File "/usr/local/lib/python3.7/re.py", line 192, in sub
website_1  |     return _compile(pattern, flags).sub(repl, string, count)
website_1  | TypeError: expected string or bytes-like object
website_1  |

Below is my docker-compose.yml file configuration
version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:7000
        --access-logfile -
       --reload
        "hms.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/hms'
    ports:
      - '7000:7000'

docker file configuration 

FROM python:3.7.5-slim-buster
MAINTAINER ********** <M*********.com>

ENV INSTALL_PATH /hms
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD gunicorn -b 0.0.0.0:7000 --access-logfile - "hms.app:create_app()"

**Comment by miguelgrinberg** [comment]
Try a newer gunicorn. This looks like https://github.com/benoitc/gunicorn/issues/1951.

**Comment by Makeem1** [comment]
Hello Miguel, I tried the latest gunicorn, it works pretty cool. Thanks
