### ISSUE TITLE
sending of email not working with uWSGI

### ISSUE THREAD

**Issue by wolferikg** [miguelgrinberg/flasky#512]
Hello,

I have copied your auth system code 1:1 into a little project of mine and when i run it locally or on my remote server with the built in werkzeug application server the sending of emails works like a charm.
but once i deploy it with uWSGI (also just tried briefly with gunicorn... same issue) the emails are no longer sent.

i ran the uWSGI process with strace and it appears to me, that the thread that should be created by send_email() never runs.

I've spent the better part of a night and a day fiddling around and trying all sorts of things (--enable-threads, threads = 2, --lazy, --single-interpreter and whatnot) but i just can't seem to get it to work.
would you have an idea what i'm doing wrong here? 

at this point my uwsgi config looks like this:
```
   module = wsgi:app

   master = true
   processes = 5
   threads = 5

   socket = app.sock
   chmod-socket = 660
   vacuum = true

   ; mount apps
   mount = /mustard=wsgi:app
   callable: app

   ; rewrite SCRIPT_NAME and PATH_INFO accordingly
   manage-script-name = true

   die-on-term = true

   env = MAIL_USERNAME=myUser
   env = MAIL_PASSWORD=myPass
   env = MAIL_SERVER=smtp.domain.tld
   env = MUSTARD_CONFIG=unix
   env = DATABASE_URL=sqlite:////home/app/app/db/data-dev.sqlite
```

and i start it like so:

```
uwsgi --uwsgi-socket app.sock -w wsgi:app --honour-stdin --ini app.ini --lazy --enable-threads
```

**Comment by miguelgrinberg** [comment]
The thread that is used for sending the email has nothing to do with the thread support in uWSGI, which is specifically for handling requests. You do not need to change the uWSGI configuration in any way.

Did you look at the uWSGI logs to see if there are any errors? Did you add print statements in the request handler right before the thread is launched, and then another print in the thread itself to make sure it started? There isn't really much to this, it is just a standard thread, there is no reason for this to not work unless something else changed and you are not aware of it.

**Comment by wolferikg** [comment]
OK it works now... after starting over the deployment.
i don't even know what the issue was.
i may have been too deep in the rabbit hole last night (like over whitespace in the smtp pw which i changed to make sure that's not causing an issue)
thanks again for the quick reply which did set my sight straight!!
