### ISSUE TITLE
url_for('static', filename='') error, i don't know where in error?

### ISSUE THREAD

**Issue by labike** [miguelgrinberg/flasky#519]
flask: 1.1.2
jinja2: 2.11.1

<img width="1065" alt="截屏2021-07-13 下午8 27 02" src="https://user-images.githubusercontent.com/15871933/125877971-8ad7e761-d1b6-4338-8ed7-3ee96af3cbf5.png">
<img width="1022" alt="截屏2021-07-13 下午8 35 06" src="https://user-images.githubusercontent.com/15871933/125877989-7b432b3b-41dc-480f-b639-6ff19c79705d.png">

**Comment by miguelgrinberg** [comment]
The error is probably a quote mismatch earlier in your template. The problem does not appear to be in the url_for call.

**Comment by labike** [comment]
thanks, i'm check code
