### ISSUE TITLE
why there is no try... except

### ISSUE THREAD

**Issue by JoshYuJump** [miguelgrinberg/flasky#52]
``` python
db.session.add(user)
try:
    db.session.commit()
except:
    db.session.rollback()
```

**Comment by miguelgrinberg** [comment]
If there is a failure during commit an exception will be thrown. This will cause Flask to respond with a 500 Internal Server Error to the client, and during the teardown of the request Flask-SQLAlchemy will rollback the session.

In my opinion letting the system handle unexpected errors this way is a good idea. Consider that if you do what you suggest, then during development you will not get the debugger when there are unexpected errors.
