### ISSUE TITLE
url_for didn't show right url when I use fcgi and nginx.

### ISSUE THREAD

**Issue by dayiguizhen** [miguelgrinberg/flasky#53]
If I run app using flask-script(python manage.py runserver),it's all right

![pic1][1]

But when I use fcgi and nginx,there are something wrong

![pic2][2]

If I click Profile

![pic3][3]

[1]:http://7rfh5s.com1.z0.glb.clouddn.com/3.jpg
[2]:http://7rfh5s.com1.z0.glb.clouddn.com/4.jpg
[3]:http://7rfh5s.com1.z0.glb.clouddn.com/5.jpg

**Comment by miguelgrinberg** [comment]
FastCGI tends to have issues like this, where for odd reasons the CGI environment variables passed to the application are set incorrectly. Install this middleware, maybe that'll help: http://werkzeug.pocoo.org/docs/0.10/contrib/fixers/#werkzeug.contrib.fixers.CGIRootFix.

**Comment by dayiguizhen** [comment]
Thanks.I add two line in manage.py and it work will in nginx.

    from werkzeug.contrib.fixers import CGIRootFix


    app = CGIRootFix(app,app_root='/')


Thanks a lot.
