### ISSUE TITLE
Local time not rendering using Flask-Moment

### ISSUE THREAD

**Issue by Isaac-Tolu** [miguelgrinberg/flasky#534]
My local time failed to render when I ran the application. It showed a `.` character instead. I inspected the HTML file and saw some span tags around it. I do not understand why it did not render.

I also noticed that someone also had this issue when you made an [article](https://blog.miguelgrinberg.com/post/flask-moment-flask-and-jinja2-integration-with-momentjs) but there was no clear-cut solution to it on the forum.

I've attached some images also..

![flask-moment-issue2](https://user-images.githubusercontent.com/69419425/160288045-a8e90644-8b58-4417-ba74-eafc726e6493.png)

![flask-moment-issue3](https://user-images.githubusercontent.com/69419425/160288115-49b93358-b735-42eb-bc96-2c9fe0f5b5fb.png)

**Comment by miguelgrinberg** [comment]
The moment.js library failed to load, it's right there in your screenshot. Looks for an error message in your console.

**Comment by Isaac-Tolu** [comment]
Thanks, Miguel.

It was an `INTERNET DISCONNECTED` error. It's working now
