### ISSUE TITLE
error when trying to create an user with a pw

### ISSUE THREAD

**Issue by TheBubblePopped** [miguelgrinberg/flasky#535]
the class User has two functions as properties

```
 @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
```
        
  When i try to use User(password='something') as it's written in the tests i get an error.  __init__() got an unexpected keyword argument 'password'
 
 
 Why?

**Comment by miguelgrinberg** [comment]
@TheBubblePopped Have you made any changes to the `__init__()` method in this model?

**Comment by TheBubblePopped** [comment]
Actually yes, i found the bug. Ty
