### ISSUE TITLE
The app has no db file to initialize the database

### ISSUE THREAD

**Issue by tmaczjj** [miguelgrinberg/flasky#541]
![image](https://user-images.githubusercontent.com/22383029/191491081-0d752768-4dd4-42a7-a5d3-f9d7390871f9.png)

**Comment by miguelgrinberg** [comment]
This project is designed to be used when you are reading my Flask Web Development book. Please don't write issues unless you truly have found a bug.

**Comment by tmaczjj** [comment]
ok,fine.By the way, do the book has chinese edition？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miguelgrinberg/flasky"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miguelgrinberg/flasky] The app has no db file to initialize the database (Issue #541)





 
This project is designed to be used when you are reading my Flask Web Development book. Please don't write issues unless you truly have found a bug.

**Comment by miguelgrinberg** [comment]
https://www.amazon.com/development-Python-based-application-combat-Chinese/dp/B00QT2TQCG

**Comment by tmaczjj** [comment]
Thank you for you book and advisement.I've learned a lot from your flasky project and start to build my first website.



发自我的iPhone


------------------ Original ------------------
From: Miguel Grinberg ***@***.***&gt;
Date: Wed,Sep 21,2022 7:40 PM
To: miguelgrinberg/flasky ***@***.***&gt;
Cc: tmaczjj ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [miguelgrinberg/flasky] The app has no db file to initialize thedatabase (Issue #541)





 
https://www.amazon.com/development-Python-based-application-combat-Chinese/dp/B00QT2TQCG
