### ISSUE TITLE
Question on before_request and unconfirmed routes. 

### ISSUE THREAD

**Issue by nneessen** [miguelgrinberg/flasky#547]
I've created a dummy user and intentionally not confirmed my account, however, it stays on that auth/uncofirmed route, and won't let me logout to login as someone else unless i change the render template('auth/uconfirmed') to redirect (url_for('security.login')

**Comment by miguelgrinberg** [comment]
Are you using the code from this project or have you made modifications? There is no `security.login` endpoint in this project. The login and logout routes are in the `auth` blueprint, and this blueprint is exempt from the redirection to the unconfirmed template, so you should be able to logout.

**Comment by nneessen** [comment]
i'm actually using flask-security-too for login/logout/register, etc.

**Comment by miguelgrinberg** [comment]
Then you need to adapt the logic that displays the unconfirmed page.

**Comment by nneessen** [comment]
Got it, thank you!
