### ISSUE TITLE
While testing client requests, how get/post by endpoint instead of url?

### ISSUE THREAD

**Issue by cllen** [miguelgrinberg/flasky#548]
Hi, I want to do like following, is it possible to do so?

for example:

```python
client = app.test_client()
response = client.post('foo.buleprint.endpoint')
```

thanks for help!

**Comment by miguelgrinberg** [comment]
This is more of a Flask question and not related to this tutorial. The answer is no, I don't believe you can pass an endpoint name instead of a URL.

**Comment by cllen** [comment]
thanks!
