### ISSUE TITLE
Unicode issue.

### ISSUE THREAD

**Issue by jeffjzx** [miguelgrinberg/flasky#55]
Hi, I have a problem when deploy the app in production when connecting with MySQL db.

Here is how i did it:
- First i enter MySQL REPL create a new database called "mydatabase"
- Here is my code:

```
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.script import Manager
from flask.ext.migrate import Migrate, MigrateCommand

app = Flask(__name__, static_path='/static')

app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:password@localhost/mydatabase?charset=utf8'

db = SQLAlchemy(app)
from views import *
from models import *
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


if __name__ == '__main__':
    manager.run()
```

Here is what looks like in my models.py:

```
from run import db, app

class Table1(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.Unicode(256))
```
- Then i delete /migrates folder which i use sqlite as database in development and run
  `python run.py db init`
  `python run.py db migrate`
  `python run.py db upgrade`
  Everything looks normal.
- However when test in production, there are some encoding issue, for instance, when i save english words to test_1.name(test_1 is an instance of Table1), it shows correctly. However when i save test_1.name to some Unicode characters, it shows "??????". Here is what is shows in python interpreter:
  
  > > > test_1 = Table1.query.filter_by(id=1).first()
  > > > test_1.name
  > > > u'?????' 

How can i deal with such situation? Thank you.

**Comment by miguelgrinberg** [comment]
Check the `collation` setting in your tables (the command is `SHOW TABLE STATUS FROM <table>` if I remember correctly).
