### ISSUE TITLE
Flask run command doesn't work

### ISSUE THREAD

**Issue by nickmeny** [miguelgrinberg/flasky#559]
Hi,recently i bought your book and i am completly satisfied from your job!!! But, i want to implement your code at my project, specially the file organization. I make the config.py file as you have done in the book at page 87 with the only difference i loaded the var form a .env file . When i want to start the server at my pc i get that error 
```
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Detected factory 'create_app' in module 'app', but could not call it without arguments. Use 'app:create_app(args)' to specify arguments.
```
i have done everything up to page 97!!! pls help me (i have name the flasky.py file to app.py)

**Comment by miguelgrinberg** [comment]
Looks like you did not set your `FLASK_APP` variable.

**Comment by nickmeny** [comment]
> Looks like you did not set your `FLASK_APP` environment variable.

I have set the env var with the command
set FLASK_APP=app.py

**Comment by miguelgrinberg** [comment]
Okay, so then in `app.py` you are not creating an application instance. See flasky.py in this repository and compare that against your app.py.

**Comment by nickmeny** [comment]
i found the solution!!! For dome reason my file name app.py dowsnt work with flask!!! When i rename it to flasky.py and set the FLASK_APP=flasky.py everything worked !!!

**Comment by miguelgrinberg** [comment]
Did you have both `app.py` and the `app` package? That could be the problem, Python will see only one of them, since both have the name `app`.

**Comment by nickmeny** [comment]
Oh yes I had. That was the problem. Thanks any way for your help
