### ISSUE TITLE
Event log for Flasky

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#61]
Hi @miguelgrinberg I want to add event log for flasky, such as logging user activities, such as login/logout, post a blog, add a comment, follow a user, etc. I want to record those activities into database using SQLAlchemy - what do you suggest I use to implement this? I found Flask Signals http://flask.pocoo.org/docs/0.10/signals/ and it seems to be a good candidate, but I want to get the expert's guidance first :).

**Comment by miguelgrinberg** [comment]
Signals help decouple two parts of the application, so if you want the core application to go about its business without knowing there is an event log, then signals will help you achieve that. If, on the other side, the event log is an integral part of the application, I'd say signals are not really necessary, you can just make a direct function or method calls to the event log in the place where you would fire the signals.

Hope this helps!

**Comment by harrywang** [comment]
Thanks a lot for your guidance, Miguel!!
