### ISSUE TITLE
500 error handler is not working under gunicorn

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/flasky#62]
When I run flasky using gunicorn, the 500 error handler configured in /app/main/errors.py does not work. I get a generic "Internal Server Error" message instead of the rendered template.

I'm using a fresh copy of flasky without modifications.

**Comment by coreybrett** [comment]
So locally when running under gunicorn 18, I get the generic 500 error message, but when I push to Heroku, I get my customized 500 page.

**Comment by miguelgrinberg** [comment]
What is your gunicorn start up command?

I'm testing here with:

    FLASK_CONFIG=heroku SSL_DISABLE=1 gunicorn manage:app

And that gives me the expected page for 500 errors.

**Comment by coreybrett** [comment]
Sorry, I figured this one out. I was under the impression that the value of app.debug only applied to the built-in development server, I didn’t realize it would affect the operation of gunicorn. My bad, I’m a beginner.
