### ISSUE TITLE
framework on top of a micro framework?

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/flasky#64]
Could/should Flasky be considered a framework on top of a micro framework?
Does Flasky have any other peers that could be used for comparison/learning purposes?

**Comment by miguelgrinberg** [comment]
I see a framework as something you can use to build an application. From that point of view Flasky is not a framework, it is an application built on Flask, which is the framework.

Now, some parts of Flasky can be thought of generic enough that can be used as a foundation for other applications, so I think it should be possible to extract parts of Flasky and create a slightly higher level framework than Flask. In particular, I think the authentication subsystem is a good candidate.

**Comment by coreybrett** [comment]
BTW, I love the book! For only 200ish pages, it packs a lot of info in. It has more than other larger books I’ve looked at.

**Comment by miguelgrinberg** [comment]
Glad to hear you like it. :)
