### ISSUE TITLE
Bootstrap does not affect the page on refresh. (3b)

### ISSUE THREAD

**Issue by mfrlin** [miguelgrinberg/flasky#66]
When I type url by hand and press enter everything works as it should. Bootstrap is nicely formating the navbar. But then when I press refresh button page reloads without Bootstrap (altough I can see it does get transfered in the network tab)

The only difference I can see is that on refresh request a Cache-Control header gets set with value: max-age=0

This somehow prevents Bootstrap css affecting the page.

Any thoughts on the solution?

**Comment by miguelgrinberg** [comment]
What web browser are you using? Did you try more than one?

**Comment by mfrlin** [comment]
I am using Firefox for Linux Mint 33.0.

In Google Chrome the page works fine (it does not set a Cache-Control header on refresh).

**Comment by miguelgrinberg** [comment]
Couple more questions.

First, I assume this request goes to the CDN URL, not to the Flasky server, correct? The URL should begin with `http://cdnjs.cloudflare.com/...`. So basically there is nothing on the Flask server that can be affecting this.

Next, the expected status code for the response on this request should be 304, which basically means that the file has not changed and can be taken from the browser's cache. Let me know if this is not what you get.

Lastly, the 33.0 release of Firefox is a bit old, it was released almost a year ago. Any reason why you are not letting Firefox upgrade itself to the latest releases? Or maybe Mint does not enable auto-upgrades on Firefox?

**Comment by mfrlin** [comment]
It seems that my wifi is flaky and most of the time it was using cached versions of the static files. But on refresh it tried to grab them from CDN and failed, because there wasn't any internet connection.

Thanks for the help and the cool book. Decided to read it after watching your pycon talks which were also great. I miss your opinions and reasoning on Flask's design and comparisons with other frameworks in the book a little but still it is a nice book so far.
