### ISSUE TITLE
Import Error in Chapter 1

### ISSUE THREAD

**Issue by ZhangHangCN** [miguelgrinberg/flasky#67]
I have done just as Chapter 1, until I typed
```
>>>import flask
```
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "flask/app.py", line 37, in <module>
    from .cli import make_default_cli
  File "flask/cli.py", line 17, in <module>
    import click
ImportError: No module named click

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "flask/app.py", line 26, in <module>
    from . import json

Is there any wrong with my envrionment?

**Comment by miguelgrinberg** [comment]
You don't seem to be using Flask version 0.10.1, which is the official release at this time.

**Comment by ZhangHangCN** [comment]
I have installed flasked in this way ```pip install flask```, is there any thing wrong?

<img width="506" alt="2015-09-04 10 21 54" src="https://cloud.githubusercontent.com/assets/9375385/9675373/1af4c3ea-52ef-11e5-9326-4ee94fa22a43.png">
Another question is after cloning the repository, I can not check out ```1a```. Is there any thing wrong with my git version?

**Comment by miguelgrinberg** [comment]
Try running `git fetch --all` so that all the information about branches/tags is downloaded. After that, repeat the checkout command. Let me know if this helps.

**Comment by ZhangHangCN** [comment]
I have checked my flask version, and it is 0.10.1
<img width="792" alt="2015-09-04 10 30 46" src="https://cloud.githubusercontent.com/assets/9375385/9675441/25517012-52f0-11e5-9631-9bd16d7a7553.png">

**Comment by ZhangHangCN** [comment]
I have tried ```git fetch --all```, then```git checkout 1a```. 
<img width="496" alt="2015-09-04 10 35 47" src="https://cloud.githubusercontent.com/assets/9375385/9675498/d16c268a-52f0-11e5-8d56-a3a3280c0f91.png">

**Comment by miguelgrinberg** [comment]
I think you have cloned `flask` instead of `flasky`, and that is what is giving you all the problems.

Try starting from scratch. Follow these steps:

1. deactivate your virtualenv

        $ deactivate

2. Delete all the files that you cloned. I think for this you need to do this (but check to make sure I got ir right!):

        $ cd ..
        $ rm -rf flask

3. Clone `flasky` (not `flask`):

        $ git clone https://github.com/miguelgrinberg/flasky.git

4. Create and activate the virtualenv:

        $ cd flasky
        $ virtualenv venv
        $ source venv/bin/activate

5. Install Flask:

        $ pip install flask

6. Switch Flasky to tag `1a`:

        $ git checkout 1a

**Comment by ZhangHangCN** [comment]
Oh, that's really the reason. Many thanks!!! ^_^
