### ISSUE TITLE
purpose of line 115 in app/auth/views.py ?

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/flasky#68]
In line 115 of app/auth/views.py, what is the purpose of sending "next=request.args.get('next')" into the send_email function?

**Comment by miguelgrinberg** [comment]
Hmm. That looks like a bit of code that I implemented while working on this application but ended up not using it in the final version.

The purpose of any extra arguments you send to `send_mail` is that these are passed to the `render_template` calls that render the text and html emails, so in those templates `next` would be available to use as placeholder variables. At some point I intended to preserve the `next` argument from Flask-Login (the original URL the user intended to visit before the redirection to the login form), and while this is implemented for the regular login form, doing the same for the reset password flow seemed to complicated and not worth the effort, so I did not do it in the end.
