### ISSUE TITLE
perform an action when checkbox value changes

### ISSUE THREAD

**Issue by alybel** [miguelgrinberg/flasky#69]
Like with submitting forms through the submit button, I would like to trigger an action when changing the value of a checkbox (by clicking on it). My final goal is to have this value change reflected in a mysql database on a per-user basis. 

What I found so far involves a lot of javascript and I was wondering if there is not a more pure-python / pure-flask way of achieving this. 

any help is highly appreciated.

**Comment by miguelgrinberg** [comment]
Yes, unfortunately your findings are correct.

The submit button is special, it is designed to contact the server and submit form data. A checkbox control, however, does not have any of that, so you have to implement it in Javascript.

With the help of a library such as jquery the Javascript code does not need to be too involved, you can just add an event handler for the click event and in it just make an ajax call to the server.

**Comment by alybel** [comment]
Thank you very much for this answer
