### ISSUE TITLE
Login crashes

### ISSUE THREAD

**Issue by Dr762** [miguelgrinberg/flasky#72]

**Comment by miguelgrinberg** [comment]
Do you plan to add some information to this issue?

**Comment by Dr762** [comment]
The issue is solved now

четверг, 10 сентября 2015 г. пользователь Miguel Grinberg написал:

> Do you plan to add some information to this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miguelgrinberg/flasky/issues/72#issuecomment-139286464>
> .
>


-- 
Yours sincerely,
Alex Bondar
mobile: +7-926-715-72-56
skype : desert_eagle_22mm
