### ISSUE TITLE
When does the user model's __init__ actually run?

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/flasky#73]
This may be more of a Flask or Flask-Login question, but...

When does the __init__ for the user model actually run?

I've added some code to it, assuming it would be run during every request, but that doesn't seem to be the case. It appears to only run when creating a new user. Is that so and why? I thought that an object for the user would have to be instantiated during each request.

**Comment by miguelgrinberg** [comment]
Models are special objects that do not follow the regular rules, SQLAlchemy adds some magic behavior to them. The `__init__` method is invoked when you create a model in the normal way, but when SQLAlchemy loads data from the database it skips the constructor.

This behavior is even documented: http://docs.sqlalchemy.org/en/latest/orm/constructors.html. This page tells how to add constructor functionality to a model.

**Comment by coreybrett** [comment]
Ok, that would explain it then. Thanks so much.

~Sent from my Nexus 5
