### ISSUE TITLE
The post window didnot display in the main page

### ISSUE THREAD

**Issue by Neroldy** [miguelgrinberg/flasky#76]
Hi, miguelgrinberg 
After reading the chapter 11, I can add a post window in the main page, and I can comment.
But I didn't see it when I visit the main page.
This is my page:
![mypage](https://cloud.githubusercontent.com/assets/10097081/10095573/57f5f278-639d-11e5-974c-e168007b8c9b.JPG)

I use chrome and IE(include edge), but the same result. And I also checked the chrome developer tools and didn't see any local file load error in the console.
Do you have any idea?
Thanks~

**Comment by miguelgrinberg** [comment]
@Neroldy Sounds like the role/permission bits aren't correctly set for the user.

**Comment by Neroldy** [comment]
@miguelgrinberg 
Thanks for you reply.
I set the `confirmed = db.Column(db.Boolean, default=True)`, so that I can just register and do not need email confirmed because I can't use the gmail smtp. And use `#login_manager.session_protection = 'strong'`.
Can I simply skip the email confirmed? Or there are some role/permission bits operation after email confirmed?

**Comment by miguelgrinberg** [comment]
@Neroldy the shortcut you are taking is not a problem. Check that the `role_id` in the user object is set to  non-zero value. Then check the role with id `user.role_id` and make sure it exists and has the permission bits to allow the user to write posts set.

**Comment by Neroldy** [comment]
@miguelgrinberg Thank you, I will try it~

**Comment by Neroldy** [comment]
@miguelgrinberg How can I create an Administrator account directly? I want to check whether this problem happen when user is Administrator.

**Comment by miguelgrinberg** [comment]
@Neroldy First of all, check your roles table, it should look like this:

    $ sqlite3 data-dev.sqlite
    SQLite version 3.8.5 2014-08-15 22:37:57
    Enter ".help" for usage hints.
    sqlite> select * from roles;
    1|Administrator|0|255
    2|User|1|7
    3|Moderator|0|15

In this example, the administrator role has id=1. So your administrator user needs to have `role_id` set to 1. You can convert any user to an admin by setting its `role_id` to 1.

**Comment by Neroldy** [comment]
@miguelgrinberg Thanks you, problem solved!
