### ISSUE TITLE
groupe by comment count

### ISSUE THREAD

**Issue by belbazuness** [miguelgrinberg/flasky#77]
Hi Miguel,
I want to display most commented Posts, based on Post model.
i try to edit

@main.route('/', methods=['GET', 'POST'])
def index():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        post = Post(body=form.body.data,
                    author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query.order_by(Post.comments.count()).all())    <--------------------------- +
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('index.html', form=form, posts=posts,
                           show_followed=show_followed, pagination=pagination)

but its doesn't work! please help

**Comment by belbazuness** [comment]
query = Post.query
to
query = Post.query.order_by(post.comments.count())

**Comment by miguelgrinberg** [comment]
You need to use a join. Didn't try it, so it may need some tweaking, but the query would be something like this, I think:

    Post.query.outerjoin(Comment).group_by(Post.id).order_by(db.func.count(Comment.post_id).desc())

**Comment by belbazuness** [comment]
Thank you for responding to my questions so quickly. You have been very helpful. :)
