### ISSUE TITLE
User __init__ potential vulnerability

### ISSUE THREAD

**Issue by johnwilson** [miguelgrinberg/flasky#78]
Hello Miguel,

Based on the current code at in [User.**init**](https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L123), users with no email will be automatically given the admin role if the `FLASKY_ADMIN` environment variable isn't set. Would it not be more prudent to check if `User.email` is set as well by updating the line to:

``` python
if self.email and self.email == current_app.config['FLASKY_ADMIN']:
```

Thanks

**Comment by miguelgrinberg** [comment]
It does not hurt to add that check, but a user with an empty email will not be able to register, the registration form does not allow empty emails.

**Comment by johnwilson** [comment]
Yes, you're right. I only spotted this issue when i was using the shell to create users.
