### ISSUE TITLE
Does Flask support routing of multiple views on the same page???

### ISSUE THREAD

**Issue by belbazuness** [miguelgrinberg/flasky#79]
Does Flask support routing of multiple views on the same page??? it's never explained 
This is an example:

    @main.route('/', methods=['GET', 'POST'])
    def index():
        form = PostForm()
        if current_user.can(Permission.WRITE_ARTICLES) and \
                form.validate_on_submit():
            post = Post(body=form.body.data,
                        author=current_user._get_current_object())
            db.session.add(post)
            return redirect(url_for('.index'))
        page = request.args.get('page', 1, type=int)
        show_followed = False
        if current_user.is_authenticated:
            show_followed = bool(request.cookies.get('show_followed', ''))
        if show_followed:
            query = current_user.followed_posts
        else:
            query = Post.query
        pagination = query.order_by(Post.timestamp.desc()).paginate(
            page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
            error_out=False)
        posts = pagination.items
        return render_template('index.html', form=form, posts=posts,
                               show_followed=show_followed, pagination=pagination)
    
    @main.route('/', methods=['GET'])
    def MostComment():
        page = request.args.get('page', 1, type=int)
        query = Post.query.outerjoin(Comment).group_by(Post.id).order_by(db.func.count(Comment.post_id).desc())
        pagination = query.order_by(Post.timestamp.desc()).paginate(
            page, per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False)
        posts = pagination.items
        return render_template('MostComment.html', posts=posts, pagination=pagination)

**Comment by miguelgrinberg** [comment]
You can do what you want, but not in the way you describe it. Your solution is incomplete, it does not define how the different templates are to be combined to build the final page presented to the user.

You can do something similar using template includes. You define a parent template that includes several others (like the two in your example). You can define exactly where in the page each template goes. And you don't use multiple views, you use a single view function and render the parent template, which will cause the children templates to render as well. See the Jinja2 documentation for template includes: http://jinja.pocoo.org/docs/dev/templates/#include.

**Comment by belbazuness** [comment]
Thank you, Miguel
