### ISSUE TITLE
flash message shows up again using back button 

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#81]
According to Flask docs: "The flashing system basically makes it possible to record a message at the end of a request and access it next request and only next request."

When I change my profile in Flasky, I see the following flash message:

![screenshot 2015-10-10 06 20 14](https://cloud.githubusercontent.com/assets/595772/10410683/46f2a39c-6f17-11e5-8814-093ec7abb639.png)

Then I click home, and use the back button of the browser to go back, the message is still there (or shows up again), which is not correct. Is there a way to force the message to show up only once?

Thanks!!

**Comment by miguelgrinberg** [comment]
@harrywang this is a web browser behavior. When you hit the back button, the browser is showing you a cached copy of the page you saw before, the server does not get a chance to provide an updated version. If instead of using the back button, you go to the Profile page by clicking on the navigation bar, you should not see the flashed message.

**Comment by harrywang** [comment]
Thanks, Miguel!

**Comment by harrywang** [comment]
Hi @miguelgrinberg , is it possible to tell the browser not to cache certain pages in flask to avoid this behavior?

**Comment by miguelgrinberg** [comment]
This is really browser implementation, but my understanding is that to be complaint with the HTTP specification the browser needs to implement the back button as you have seen it.

Here is a relevant excerpt from the [HTTP spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.13), where clients are encouraged to use cached material when the user is reviewing the history, even if that content is stale:

> ### 13.13 History Lists

> User agents often have history mechanisms, such as "Back" buttons and history lists, which can be used to redisplay an entity retrieved earlier in a session.

> History mechanisms and caches are different. In particular history mechanisms SHOULD NOT try to show a semantically transparent view of the current state of a resource. Rather, a history mechanism is meant to show exactly what the user saw at the time when the resource was retrieved.

> By default, an expiration time does not apply to history mechanisms. If the entity is still in storage, a history mechanism SHOULD display it even if the entity has expired, unless the user has specifically configured the agent to refresh expired history documents.

**Comment by harrywang** [comment]
Thanks. Do you think the following solution may work? http://stackoverflow.com/questions/13768007/browser-caching-issues-in-flask

**Comment by harrywang** [comment]
Or any other flash message approach that flask can use to avoid this situation? Thanks a lot for your help!

**Comment by miguelgrinberg** [comment]
@harrywang the server does not control the behavior of the back button, the browser does. The question you referenced deals with caching, you can see above in the snippet of the spec I pasted that history mechanism are detached from caching. If you try it you may find that it works on some browsers and it doesn't in others, as this largely depends on finer details of the browser's implementation.

**Comment by harrywang** [comment]
Thanks, @miguelgrinberg
