### ISSUE TITLE
Error in Example 3-3 / Rendering Templates

### ISSUE THREAD

**Issue by justvidyadhar** [miguelgrinberg/flasky#84]
The code for *hello.py* in **Example 3-3** does not return anything for **'/index'** but the code contains only **'/'**. 

The return script for *'git checkout 3a'* needs to be updated.

**Comment by miguelgrinberg** [comment]
Are you referring to this?

    @app.route('/index')
    def index():
        return render_template('index.html')

You can see that it does return something. I don't understand what the problem is.

**Comment by justvidyadhar** [comment]
I'm going through the whole tutorial right now and the code returned when i did the checkout was just, 

```
@app.route('/')
def index():
    return render_template('index.html')
```
instead of the one you pasted above.

**Comment by miguelgrinberg** [comment]
Oh, okay, I see, it's an inconsistency between the book and the code. Got it. I'll update the code.

**Comment by justvidyadhar** [comment]
Cool. :)
