### ISSUE TITLE
Solution to SMTPAuthenticationError: in Chapter 6 due to Gmail's Security

### ISSUE THREAD

**Issue by justvidyadhar** [miguelgrinberg/flasky#85]
Trying to send mail from shell and for examples from 6-3, the server throws an Authentication Error. The reason being that Gmail and other email providers have updated their login security to new standards. The tutorial uses an old one. 

To make it work, Go to 'My Account' > Sign in and Security Setting and activate the following to 'ON' to make the examples work. I have noticed that none of the email authentication works without setting this up. 
![screen shot 2015-10-21 at 9 27 13 pm](https://cloud.githubusercontent.com/assets/13300052/10642486/88ff6d2e-783b-11e5-991f-7feebe2cb0ee.png)

Thank You.

**Comment by Neroldy** [comment]
@justvidyadhar 
Great!
