### ISSUE TITLE
Redirect ignored in resend_confirmation()

### ISSUE THREAD

**Issue by ar-anvd** [miguelgrinberg/flasky#86]
In resend_confirmation(): we have return redirect(url_for('main.index'))

https://github.com/miguelgrinberg/flasky/blob/579ecd9435b392df114110985f514ad173a315f2/app/auth/views.py#L85

I think this redirect will be ignored since we have this before_app_request and we are authenticated.

```
@auth.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.ping()
        if not current_user.confirmed \
                and request.endpoint[:5] != 'auth.' \
                and request.endpoint != 'static':
            return redirect(url_for('auth.unconfirmed'))
```

So we will be redirected again to auth.unconfirmed

This makes any sense, or I am missing something?

**Comment by justvidyadhar** [comment]
Yes, you are right. Once the **resend_confirmation()** is executed and return request is sent, 
the **before_request()** is executed leading you back to **auth.confirmed**. 

Hope this makes sense.

**Comment by miguelgrinberg** [comment]
It really does not matter what view you redirect to, what matters is that the flash message will be displayed, even if the main.index view cannot be shown. Do you have any suggestion to improve this view? I think the fact that the view makes no assumptions about how the before_request event works is good, it provides encapsulation.

**Comment by DmonteiroD** [comment]
@miguelgrinberg the point is that doesn't make sense, at least for me, lock the main.index even if account is not activated. That page should be public in any case right?  

A possible solution could be a temporary variable in session to identify this particular case and make the validation in before_request.

Something like session['resend_confirmation'] = True.

**Comment by miguelgrinberg** [comment]
Closing this issue, as it is over two years old.
