### ISSUE TITLE
Editing a blog post in flasky/app/main/views.py Tag 11h

### ISSUE THREAD

**Issue by samoei** [miguelgrinberg/flasky#88]
Am wondering Miguel at line 95 - 96 is it supposed to ```if current_user != post.author or not current_user.can(Permission.ADMINISTER):``` instead of ```if current_user != post.author and  not current_user.can(Permission.ADMINISTER):```

**Comment by miguelgrinberg** [comment]
This is actually correct in the code. The conditional ensures that the user is either the author or an adminsitrator, but the if statements tests the reverse case. So "author or admin" becomes "not author and not admin".

**Comment by samoei** [comment]
I finally figured that it was correct, I should have closed this issue. Thanks for getting back to me though and keep up the good work Miguel.
