### ISSUE TITLE
Not able to send confirmation emails in Chapter 10

### ISSUE THREAD

**Issue by justvidyadhar** [miguelgrinberg/flasky#89]
Im failing to make the server work. I had made the email settings work during the test in previous chapters and it was just fine. But now, for the confirmation emails with the same settings, I'm not able to get any mail. it throws the following error. 

```
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/answer/14257 yi8sm24570880pab.22 - gsmtp', 'FLASKY ADMIN <flasky@example.com')

```

Tried different settings for port but that didn't help either.  

I use Mac with OS X El Capitan and Surprisingly, the export command is no longer working for setting environment variables. 
```
(venv)$ export FLASKY_ADMIN = myemail@gmail.com
-bash: export: `=': not a valid identifier
-bash: export: `myemail@gmail.com': not a valid identifier

```

But the 'set' command recommended for WIndows users is accepting the arguments. 

Not sure what I'm doing wrong. Can you please help?

**Comment by justvidyadhar** [comment]
I got it working, thanks.

**Comment by JulyUp** [comment]
@justvidyadhar  I encounter a same as yours. How do you solve this problem? And how do the variables for class Config be set in your config.py?
