### ISSUE TITLE
deploy with gunicorn

### ISSUE THREAD

**Issue by moos3** [miguelgrinberg/flasky#90]
How would you construct a app.py to make gunicorn work for hosting this ?

**Comment by miguelgrinberg** [comment]
The chapter on deployment shows how to deploy this application on Heroku using gunicorn. If you don't have the book, see in the commit history the commit that implements Heroku. In this commit you can find a Procfile, where the command to start gunicorn is shown.

**Comment by moos3** [comment]
Yeah I'm trying to get this to work in docker
