### ISSUE TITLE
How could I add a worker script that has access to the models?

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/flasky#91]
Not interested in anything like celery just yet.
Just a simple .py file with a loop and access to my models.

**Comment by alejoar** [comment]
Hi @coreybrett,

You can try something like this:
```python
#!/usr/bin/env python
from flask import Flask, current_app
import app
from config import config
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()
app = Flask(__name__)
app.config.from_object(config['default'])
db.init_app(app)
from app.models import User

with app.app_context():
    for user in User.query.all():
        print user.username
```

Whatever you want the worker app to do, it must be done within the [flask's app context](http://flask.pocoo.org/docs/0.10/appcontext/). In the example above I print a list of the user's usernames.

**Comment by coreybrett** [comment]
Thanks for the input.

It dawned on me that I already had (I think) the framework in place with
Flask-Script.
So I added a new command to it with a loop inside.
Seems to be working at the moment, but I'm still writing the code for the
actual tasks that I need done.

**Comment by miguelgrinberg** [comment]
I think using Flask-Script as a framework is the best solution for application related tasks. But it any case, if you wanted to write a standalone script, you can create a Flask application instance and a database instance, just like the real application does. Example:

    from app import create_app, db
    from app.models import User, Follow, Role, Permission, Post, Comment

    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
    with app.app_context():
        # you can work with the database here as you do in the real app

**Comment by coreybrett** [comment]
I ended up doing something like this in my manage.py file

    class Worker:
        alive = True
        def __init__(self):
            signal.signal(signal.SIGINT, self.die)
            signal.signal(signal.SIGTERM, self.die)
        def die(self, signum, frame):
            self.alive = False

    @manager.command
    def tasks():
        bob = Worker()
        timeout = 60
        while bob.alive:
            print 'looping...'
            do_task()
            print 'bob is sleeping for %s sec' % timeout
            time.sleep(timeout)
        print "bob died gracefully :)"

This will get the job done for now, but I realized that it doesn't scale. If I ever wanted to spread the load out among multiple nodes, I would have to scrap this and start over. I see now that is where something like Celery would come into play.
