### ISSUE TITLE
adding users to cls in setUp or setUpClass

### ISSUE THREAD

**Issue by benjh33** [miguelgrinberg/flasky#93]
Why can't I set up some users in setUpClass or setUp and pass the assertions checking that a regular user can follow and write articles? 

This has mystified me for so long, I usually try to follow a book to the letter and but make small changes that make sense to me. In this case, if I don't create the user in the actual test, the role attribute is always None, so all checks on the "can" method fail.

No big deal, but if you've got a quick answer I'd really appreciate it. 

Thanks, I'm enjoying the book a lot.

**Comment by miguelgrinberg** [comment]
You should be able to create users in the set up methods of a test case class, that should not be a problem. Do you want to show me what you did, and the complete stack trace of the error, if you are getting one?

**Comment by benjh33** [comment]
I was calling `Role.insert_roles()` after creating my test users. Thanks again.
