### ISSUE TITLE
pep8 always warning,imports not on top of file

### ISSUE THREAD

**Issue by tkisme** [miguelgrinberg/flasky#94]
imports not on top of file
according to [this](https://github.com/PyCQA/pep8/pull/304#issuecomment-66939162) is it any idea to avoid warnings

**Comment by miguelgrinberg** [comment]
There are a few specific situations where I have made the choice of importing not at the top of the file. These are done this way to avoid circular dependency imports, if you move them to the top then you will get errors.

In my opinion it does not make sense to flag these imports as errors. Sometimes there are legitimate reasons to move imports down.

**Comment by Cabalist** [comment]
https://www.python.org/dev/peps/pep-0008/#id15

:)
