### ISSUE TITLE
Using current_user in form logic

### ISSUE THREAD

**Issue by tomkun** [miguelgrinberg/flasky#95]
Hey Miguel,

When implementing the change password feature (tag 8f), is it ok to put current password check as a custom form validator instead of keeping the logic [in the view function](https://github.com/miguelgrinberg/flasky/blob/8f/app/auth/views.py#L91)?

    from flask.ext.login import current_user

    class ChangePasswordForm(Form):
        old_password = PasswordField('Old password', validators=[Required()])
        password = PasswordField('New password', validators=[
            Required(), EqualTo('password2', message='Passwords must match')])
        password2 = PasswordField('Confirm new password', validators=[Required()])
        submit = SubmitField('Update Password')

        def validate_old_password(self, field):    
            if not current_user.verify_password(field.data):
                raise ValidationError('Invalid password.')    

I'm unsure if it's just a matter of preference or is the book implementation *the* proper practice here.

**Comment by miguelgrinberg** [comment]
I think this is a matter of preference.

My thinking is that whenever possible, coupling between different modules in the application should be kept to a minimum. In many cases it is necessary for forms to obtain data from models, so I think this is an unavoidable dependency.

But doing what you suggest above not only requires a dependency on the `User` model, but also on Flask-Login, which provides the `current_user` context variable, and indirectly also with the `session` object. In my view, doing it this way makes the code a bit more entangled with the rest of the application. My preference is to code the different parts of the application to function as fairly independent entities, that makes the code more portable. But as I said, in the end it is a matter of preference.

Hope this helps!

**Comment by tomkun** [comment]
That cleared it up perfectly, thanks!
