### ISSUE TITLE
Installation via requirements.txt

### ISSUE THREAD

**Issue by priyankamandikal** [miguelgrinberg/flasky#96]
Towards the end of chapter 7, the author advises us to check installations by directly installing from the requirements.txt file like this:
 pip install -r requirements.txt
But this step installs older versions of modules irrespective of whether a newer version has been installed or not. In my case, although most modules had already been installed and running fine, I now have two copies of several  modules. How do I undo this step? Since now I am unsure of which modules are dependent on which other ones. My dist-packages folder is a bit too messy now. :(
Any suggestions?

**Comment by miguelgrinberg** [comment]
I think you are mistaken on how requirements work. If you have foo v1.1 installed in your virtualenv, and have `foo==v1.0` in your requirements.txt file, when you do `pip install -r requirements.txt`, pip will uninstall version 1.1 and then install 1.0. You will never end up with two versions installed.

The reason why requirements.txt files are useful is that they indicate the exact versions that were tested against the application. Newer versions will likely work too, but it isn't that uncommon that a new versions of a package breaks compatibility.

**Comment by priyankamandikal** [comment]
Oh. It seemed like there were a lot of modules when I checked my dist-packages folder.
Thanks for clarifying!
