### ISSUE TITLE
Sending emails via the app

### ISSUE THREAD

**Issue by priyankamandikal** [miguelgrinberg/flasky#97]
I am having trouble sending emails via the app. However, if I individually test it in the shell, it's working.

Let's say the admin id is 'admin@example.com' and password is 'password'.
Then the only variables that are to  be changed are:
env variable MAIL_USERNAME (admin)
env variable MAIL_PASSWORD (password)
env variable FLASKY_ADMIN (admin@example.com)
in config.py: FLASKY_MAIL_SENDER = 'Flasky Admin admin@example.com'

Is this all? I think I might be missing something or not setting one of the variables correctly.

**Comment by miguelgrinberg** [comment]
If it works for you on the console, then clearly the configuration is okay.

The variables that you show above are not the only ones, the configuration for Flask-Mail needs a few more variables, but if you are using gmail as your server, all these are set correctly in the application. If you are not using gmail as your server, then you need to configure Flask-Mail appropriately for the email server that you are using. You can see the entire list of variables here: https://pythonhosted.org/Flask-Mail/#configuring-flask-mail.

**Comment by priyankamandikal** [comment]
I just realized my mistake. The terminal where I had set my environment variables was different from the one where I had started the server. Can't believe I spent so much time on this!

I create a new virtual environment in every terminal that I use for the project. Is this the right way to be doing things? I haven't faced any problems before, except in this case.

**Comment by miguelgrinberg** [comment]
Is there a reason you use a different virtual environment for every console? There is absolutely no problem in activating a virtualenv in multiple terminals. That way you are guaranteed to always use the same configuration and packages.

**Comment by priyankamandikal** [comment]
No specific reason. I just thought we need to be using a virtual env while working on this project.

**Comment by miguelgrinberg** [comment]
Yes, using a virtualenv is the best way, but use one virtualenv per project, if you open multiple terminals you should use the same virtualenv in all of them.

**Comment by priyankamandikal** [comment]
I mean I have created just one virtual environment in the beginning of the project.
When I instantiate it, as in source/bin/activate, aren't those different instances of the same virtual env?

**Comment by miguelgrinberg** [comment]
Sure, you can think of all these activated virtualenvs as different instances. For some reason the way you described what you were doing made me think you had a different virtualenv per terminal (not a different instance of one virtualenv).

Forget what I said, you are doing it right. :)

**Comment by priyankamandikal** [comment]
Oh cool then!

Also, I had this doubt regarding database migrations. Somehow, I am not very clear with the entire database concept. But I guess I need more practice on that. However I have this one clarification. What is the sqlalchemy equivalent of "select * from table". I found this link.
http://stackoverflow.com/questions/21310549/list-database-tables-with-sqlalchemy
But that's such a roundabout way for such a basic operation. 
Can you direct me to better resources on working with sqlalchemy?

**Comment by miguelgrinberg** [comment]
If you use the Flask-SQLAlchemy, you can get all the entries in a table with the following statement:

    users = User.query.all()

This sends the `select * from users` query to your database. You can also send SQL statements directly to SQLAlchemy if you like.

**Comment by priyankamandikal** [comment]
Oh well. I remember reading something similar in the book. My bad.

Thanks!

**Comment by priyankamandikal** [comment]
Oh but when I do that I the output is something like
[<User 'user1'>, <User 'user2'>]
It doesn't return all the columns

**Comment by miguelgrinberg** [comment]
Yes, it does return all the columns. What you are seeing is `User` instances, each of the elements of the array is a full `User` instance. You can access all the fields on all of them. The `User 'user 1'` text that you see on the console is how the User object converts itself to a string for presentation, you could change it to show more data if you like, see the method `__repl__` in the User class for that.
