### ISSUE TITLE
Returning the user object in load user function costs too much.

### ISSUE THREAD

**Issue by alex1007** [miguelgrinberg/flasky#98]
Hi everyone. I recently extended flasky. As a result, the User table grows a lot which makes the `load_user` function in the `models` file very inefficient, since it returns every thing related to the user. I was wondering whether the user can be loaded in a more efficient way or I should improve the model design reducing the scale of the user table.

```
@login_manager.user_loader
# cost 0.5 ms
def load_user(user_id):
    return User.query.get(int(user_id))
```

**Comment by miguelgrinberg** [comment]
@alex1007 Flask-Login does not require that you load everything you know about the user. The only requirement is that the user object you return has the id and implements the required properties (`is_authenticated`, `is_anonymous`, etc.).

If your database user is too large, you can create a lighter user object that you give to Flask-Login.

**Comment by alex1007** [comment]
@miguelgrinberg Thank you very much. I modify the return exp, and it returns the user object which only has id. However, the `current_user` produce an AttributeError.
`'result' object has no attribute 'is_authenticated'`. This is related to what you mentioned above. I tried to get a clue from your book and the doc of flask-login, but lost. Did I miss something?

**Comment by miguelgrinberg** [comment]
@alex1007 the link to the official documentation regarding the methods that you need to implement in the user object you pass to Flask-Login is here: https://flask-login.readthedocs.org/en/latest/#your-user-class. In the book I opted to inherit from the `UserMixin`, which is an option that will also likely work for your lightweight user class.
